// Real mobile controller/API parser, fake DOM and an in-memory ledger: no ERP data or browser.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const mobile=fs.readFileSync('static/mobile_erp.html','utf8'),script=fs.readFileSync('static/ui/mobile-dimension-stock.js','utf8');
const apiSource=mobile.slice(mobile.indexOf('      async function apiPost('),mobile.indexOf('      async function logout()'));
const key=id=>`tm-dimension-take-pending-v2:${id}`,legacyKey='tm-dimension-take-pending-v1';
const clone=value=>JSON.parse(JSON.stringify(value)),tick=()=>new Promise(setImmediate);
class Element {
 constructor(id,nodes){Object.assign(this,{id,nodes,value:'',hidden:false,disabled:false,dataset:{},textContent:''});}
 set innerHTML(value){this.html=value;for(const m of value.matchAll(/<[^>]*\bid="([^"]+)"[^>]*>/g)){const element=new Element(m[1],this.nodes);element.hidden=/\bhidden\b/.test(m[0]);this.nodes.set(m[1],element);}}
 get innerHTML(){return this.html;}
 querySelector(s){return this.nodes.get(s.slice(1));}
 querySelectorAll(s){return s==='button'?this.buttons||[]:[];}
 replaceChildren(){this.html='';this.buttons=[];}scrollIntoView(){}reset(){}
}
function harness(){
 const state={actor:101,available:20,version:1,movements:new Map(),storage:new Map(),posts:[],gets:[],mode:'normal',resolveMode:'normal',failStorage:'',failRefresh:false};
 const nodes=new Map(),root=new Element('dimensionStock',nodes);nodes.set(root.id,root);const get=id=>nodes.get(id);
 const body={quantity:3,purpose:'sample',expected_version:1,location_id:6,address_version:1,idempotency_key:'legacy_key_0123456789'};
 const signature=b=>JSON.stringify([b.quantity,b.purpose,b.expected_version,b.location_id,b.address_version]);
 const item=()=>({id:1,product_id:5,version:state.version,location_id:6,address_version:1,code:'SYNTHETIC-LONG-CODE',name:'合成库存',customer:'合成客户',dimensions:[500,300,200],unit:'只',available:state.available,reserved:0,physical:state.available,damaged:0,status:'active',can_take:true,location_name:'隔离测试位置'});
 const response=(status,value,headers={})=>({status,ok:status>=200&&status<300,text:async()=>typeof value==='string'?value:JSON.stringify(value),headers:{get:n=>headers[n]||null}});
 const recordMovement=(b,actor=state.actor)=>{const row={movement_id:state.movements.size+1,quantity:b.quantity,actor_id:actor,account:`合成账号${actor}`,signature:signature(b)};state.movements.set(b.idempotency_key,row);state.available-=b.quantity;state.version++;return row;};
 const apiGet=async url=>{
  state.gets.push(url);if(url.endsWith('/history'))return {items:[]};if(url.endsWith('/detail')){if(state.detailMode==='fail')throw Error('合成货位读取失败');const row=item();if(state.detailMode==='moved')row.location_id=7;if(state.detailMode==='missing')row.unit='';return {item:row,can_execute:true};}
  if(state.failRefresh)throw new Error('合成刷新失败');
  get('dsResults').buttons=[Object.assign(new Element('result',nodes),{dataset:{index:'0'}})];return {total:1,items:[item()],can_execute:true};
 };
 const window={location:{replace:()=>state.redirected=true}};
 const ctx=vm.createContext({window,document:{getElementById:id=>nodes.get(id)},URLSearchParams,Uint8Array,AbortController,crypto:crypto.webcrypto,console,
  sessionStorage:{getItem:k=>{if(state.failStorage==='get')throw Error('read unavailable');return state.storage.get(k)||null;},setItem:(k,v)=>{if(state.failStorage==='set'||(state.failStorage==='confirmed-set'&&JSON.parse(v).outcome==='confirmed'))throw Error('write unavailable');state.storage.set(k,v);},removeItem:k=>{if(state.failStorage==='remove')throw Error('remove unavailable');state.storage.delete(k);}},
  clearMobilePortalState(){window.TmDimensionStock.destroy();},
  fetch:async(url,options)=>{
   const b=JSON.parse(options.body),resolve=url.endsWith('/resolve');state.posts.push({url,body:clone(b),actor:state.actor});
   if(state.defer){await state.defer.promise;}
   if(resolve){
    const malformed={empty:'',invalid:'<html>truncated',null:'null',object:'{}',missingActor:'{"status":"not_recorded","can_continue":true}',stringActor:'{"current_actor_id":"101"}'};
    if(Object.hasOwn(malformed,state.resolveMode))return response(200,malformed[state.resolveMode]);
    if(state.resolveMode==='deny')return response(403,{detail:'无权限'});
    if(state.resolveMode==='conflict')return response(409,{detail:'请求冲突'},{'X-Stock-Take-Preserve':'1'});
    const previous=state.movements.get(b.idempotency_key);
    if(previous&&previous.signature!==signature(b))return response(409,{detail:'请求冲突'},{'X-Stock-Take-Preserve':'1'});
    if(previous)return response(200,{...previous,status:'completed',replayed:true,observed_at:'2026-10-10T10:00:00',current_actor_id:state.actor});
    return response(200,{status:'not_recorded',observed_at:'2026-10-10T10:00:00',current_actor_id:state.actor,can_continue:state.resolveMode!=='ineligible',continue_reason:state.resolveMode==='ineligible'?'库存已变化':null});
   }
   if(state.mode==='401')return response(401,{detail:'登录失效'});
   if(b.expected_actor_id!==state.actor)return response(409,{detail:'账号已变化'},{'X-Stock-Take-Actor-Mismatch':'1','X-Stock-Take-Preserve':'1'});
   if(state.mode==='network-before')throw Error('合成发送前断网');
   if(state.mode.startsWith('reject-')){const status=Number(state.mode.split('-')[1]);return response(status,{detail:'合成拒绝'},state.mode.endsWith('marked')?{'X-Stock-Take-Rejected':'1'}:{});}
   const previous=state.movements.get(b.idempotency_key);
   if(previous&&(previous.signature!==signature(b)||previous.actor_id!==state.actor))return response(409,{detail:'请求冲突'},{'X-Stock-Take-Preserve':'1'});
   if(!previous&&b.expected_version!==state.version)return response(409,{detail:'库存已变化'},{'X-Stock-Take-Rejected':'1'});
   const row=previous||recordMovement(b),result={movement_id:row.movement_id,quantity:b.quantity,replayed:!!previous};
   if(state.mode==='network-after')throw Error('合成提交后响应丢失');
   const malformed={empty:'',invalid:'<html>truncated',null:'null',object:'{}',missing:'{"quantity":3,"movement_id":1}',wrongQty:'{"quantity":4,"movement_id":1,"replayed":false}',wrongType:'{"quantity":3,"movement_id":"1","replayed":false}'};
   return response(200,Object.hasOwn(malformed,state.mode)?malformed[state.mode]:result);
  }});
 vm.runInContext(apiSource,ctx);vm.runInContext(script,ctx);
 function mount(id=state.actor){window.TmDimensionStock.mount({userId:id,displayName:`合成账号${id}`,apiGet,apiPost:ctx.apiPost});}
 async function search(){get('dsKind').value='board';get('dsFlute').value='';for(const axis of ['length','width','height']){get('ds-'+axis).value=axis==='length'?'500':'';get('ds-'+axis+'-op').value='ge';}get('dsForm').onsubmit({preventDefault(){}});await tick();get('dsResults').buttons[0].onclick();await tick();}
 async function submit(){get('dsQuantity').value='3';get('dsPurpose').value='sample';await get('dsTake').onclick();await tick();}
 const legacy=()=>state.storage.set(legacyKey,JSON.stringify({lotId:1,body}));
 return {state,get,window,mount,search,submit,body,legacy,recordMovement,takeCount:()=>state.posts.filter(p=>p.url.endsWith('/take')).length};
}
const cases=[];
async function test(name,fn){await fn();cases.push(name);}
(async()=>{
 await test('normal complete receipt clears owner cache and updates inventory',async()=>{const h=harness();h.mount();await h.search();await h.submit();assert.equal(h.state.movements.size,1);assert.equal(h.state.storage.size,0);assert.match(h.get('dsReceipt').textContent,/流水 1/);assert.match(h.get('dsStatus').textContent,/库存已更新/);assert.equal(h.state.posts[0].body.expected_actor_id,101);});
 for(const mode of ['empty','invalid','null','object','missing','wrongQty','wrongType','network-after'])await test(`${mode}: incomplete/lost receipt keeps exact key and retry replays once`,async()=>{const h=harness();h.mount();await h.search();h.state.mode=mode;await h.submit();const saved=h.state.storage.get(key(101));assert.ok(saved);assert.equal(h.get('dsReceipt').hidden,true);assert.equal(h.state.movements.size,1);h.state.mode='normal';await h.submit();assert.deepEqual(h.state.posts[0].body,h.state.posts[1].body);assert.equal(h.state.movements.size,1);assert.equal(h.state.storage.size,0);});
 await test('network before commit preserves key and retry records once',async()=>{const h=harness();h.mount();await h.search();h.state.mode='network-before';await h.submit();assert.equal(h.state.movements.size,0);h.state.mode='normal';await h.submit();assert.equal(h.state.movements.size,1);assert.equal(h.state.posts[0].body.idempotency_key,h.state.posts[1].body.idempotency_key);});
 for(const mode of ['reject-409','reject-409-marked','reject-403','reject-404','reject-422'])await test(`${mode}: rejection after unknown retains earlier fact and routes to readonly resolve`,async()=>{const h=harness();h.mount();await h.search();h.state.mode='network-after';await h.submit();h.state.mode=mode;await h.submit();assert.ok(h.state.storage.has(key(101)));const n=h.takeCount();h.state.mode='normal';await h.get('dsRecover').onclick();assert.equal(h.takeCount(),n);assert.equal(h.state.movements.size,1);assert.equal(h.state.storage.size,0);});
 for(const mode of ['reject-409-marked','reject-403'])await test(`${mode}: first definite rejection may clear unsent history`,async()=>{const h=harness();h.mount();await h.search();h.state.mode=mode;await h.submit();assert.equal(h.state.movements.size,0);assert.equal(h.state.storage.size,0);});
 await test('unmarked409 remains unknown',async()=>{const h=harness();h.mount();await h.search();h.state.mode='reject-409';await h.submit();assert.ok(h.state.storage.has(key(101)));});
 for(const failure of ['get','set'])await test(`storage ${failure} fails closed before business POST`,async()=>{const h=harness();h.state.failStorage=failure;h.mount();await h.search();await h.submit();assert.equal(h.takeCount(),0);assert.equal(h.get('dsTake').disabled,true);assert.equal(h.get('dsReloadRecovery').hidden,false);});
 for(const storageKey of [key(101),legacyKey])for(const raw of ['null','"invalid-record"','{truncated'])await test(`invalid stored ${storageKey} ${raw} is preserved and blocks POST`,async()=>{const h=harness();h.state.storage.set(storageKey,raw);h.mount();await h.search();await h.submit();assert.equal(h.takeCount(),0);assert.equal(h.state.storage.get(storageKey),raw);assert.equal(h.get('dsTake').disabled,true);});
 await test('cache changed after mount is not overwritten by a fresh request',async()=>{const h=harness();h.mount();await h.search();const other=JSON.stringify({version:2,ownerId:101,lotId:2,body:{...h.body,expected_actor_id:101},outcome:'unknown',sent:true});h.state.storage.set(key(101),other);await h.submit();assert.equal(h.takeCount(),0);assert.equal(h.state.storage.get(key(101)),other);assert.equal(h.get('dsTake').disabled,true);});
 for(const failure of ['remove','confirmed-set'])await test(`known success + storage ${failure} cannot retry take, only readonly resolve`,async()=>{const h=harness();h.mount();await h.search();h.state.failStorage=failure;await h.submit();assert.equal(h.state.movements.size,1);assert.match(h.get('dsReceipt').textContent,/流水 1/);assert.equal(h.takeCount(),1);h.state.failStorage='';h.get('dsReloadRecovery').onclick();await h.get('dsRecover').onclick();assert.equal(h.takeCount(),1);assert.equal(h.state.storage.size,0);});
 await test('successful deduction + failed list refresh keeps success and refresh sends GET only',async()=>{const h=harness();h.mount();await h.search();h.state.failRefresh=true;await h.submit();assert.equal(h.state.storage.size,0);assert.match(h.get('dsReceipt').textContent,/已取用 3/);assert.match(h.get('dsStatus').textContent,/库存尚未刷新/);assert.equal(h.get('dsRefresh').hidden,false);h.state.failRefresh=false;await h.get('dsRefresh').onclick();assert.equal(h.takeCount(),1);});
 await test('owner caches survive account switch and B cannot see or adopt A request',async()=>{const h=harness();h.mount();await h.search();h.state.mode='network-before';await h.submit();const a=h.state.storage.get(key(101));h.state.actor=202;h.mount();assert.equal(h.get('dsRecover').hidden,true);await h.search();h.state.mode='normal';await h.submit();assert.equal(h.state.storage.get(key(101)),a);assert.equal(h.state.posts[1].body.expected_actor_id,202);assert.notEqual(h.state.posts[0].body.idempotency_key,h.state.posts[1].body.idempotency_key);});
 await test('401 destroys old controller without clearing pending',async()=>{const h=harness();h.mount();await h.search();h.state.mode='401';await h.submit();assert.ok(h.state.storage.has(key(101)));assert.equal(h.state.redirected,true);h.state.mode='normal';await h.submit();assert.equal(h.takeCount(),1);});
 await test('late take after destroy/remount does not clear old key or change new DOM',async()=>{const h=harness();h.mount();await h.search();let release;h.state.defer={promise:new Promise(r=>release=r)};const wait=h.submit();await tick();const a=h.state.storage.get(key(101));h.window.TmDimensionStock.destroy();h.state.actor=202;h.mount();const text=h.get('dsStatus').textContent;h.state.defer=null;release();await wait;assert.equal(h.state.storage.get(key(101)),a);assert.equal(h.get('dsStatus').textContent,text);assert.equal(h.get('dsReceipt').hidden,true);});
 await test('late old POST401 cannot destroy or redirect newly mounted account B',async()=>{const h=harness();h.mount();await h.search();let release;h.state.defer={promise:new Promise(r=>release=r)};const wait=h.submit();await tick();const old=h.state.storage.get(key(101));h.window.TmDimensionStock.destroy();h.state.actor=202;h.mount();h.state.mode='401';h.state.defer=null;release();await wait;assert.equal(h.state.redirected,undefined);assert.equal(h.state.storage.get(key(101)),old);h.state.mode='normal';await h.search();await h.submit();assert.equal(h.state.posts.at(-1).body.expected_actor_id,202);});
 await test('real apiGet parser ignores stale401 before global logout side effects',async()=>{let clears=0,redirects=0;const source=mobile.slice(mobile.indexOf('      async function apiGet('),mobile.indexOf('      async function apiPost('));const ctx=vm.createContext({window:{location:{replace:()=>redirects++}},clearMobilePortalState:()=>clears++,fetch:async()=>({status:401}),URLSearchParams});vm.runInContext(source,ctx);await assert.rejects(ctx.apiGet('/synthetic',{isCurrent:()=>false}),{name:'AbortError'});assert.equal(clears,0);assert.equal(redirects,0);});
 await test('legacy completed historical A is displayed to current B and cleared only by explicit ack',async()=>{const h=harness();h.legacy();h.recordMovement(h.body,101);h.state.actor=202;h.mount();await h.get('dsRecover').onclick();assert.match(h.get('dsReceipt').textContent,/合成账号101已取用 3/);assert.ok(h.state.storage.has(legacyKey));assert.equal(h.takeCount(),0);h.get('dsRecoveryAck').onclick();assert.equal(h.state.storage.size,0);});
 await test('legacy not_recorded requires explicit continue with same key/body and current actor',async()=>{const h=harness();h.legacy();h.state.actor=202;h.mount();await h.get('dsRecover').onclick();assert.equal(h.takeCount(),0);assert.ok(h.state.storage.has(legacyKey));assert.equal(h.get('dsContinue').hidden,false);await h.get('dsContinue').onclick();assert.equal(h.takeCount(),1);const b=h.state.posts[1].body;for(const name of Object.keys(h.body))assert.equal(b[name],h.body[name]);assert.equal(b.expected_actor_id,202);assert.equal(h.state.storage.size,0);assert.equal(h.state.movements.size,1);assert.equal(h.get('dsRecovery').hidden,true);});
 for(const mode of ['ineligible','conflict','deny'])await test(`legacy resolve ${mode} retains original unknown and never probes take`,async()=>{const h=harness();h.legacy();h.state.resolveMode=mode;h.mount();const old=h.state.storage.get(legacyKey);await h.get('dsRecover').onclick();assert.equal(h.state.storage.get(legacyKey),old);assert.equal(h.get('dsContinue').hidden,true);await h.get('dsContinue').onclick();assert.equal(h.takeCount(),0);});
 for(const mode of ['empty','invalid','null','object','missingActor','stringActor'])await test(`resolve ${mode} incomplete actor keeps key and permits readonly retry`,async()=>{const h=harness();h.legacy();h.state.resolveMode=mode;h.mount();const old=h.state.storage.get(legacyKey);await h.get('dsRecover').onclick();assert.equal(h.state.storage.get(legacyKey),old);assert.equal(h.get('dsRecover').disabled,false);h.state.resolveMode='normal';await h.get('dsRecover').onclick();assert.equal(h.get('dsContinue').hidden,false);assert.equal(h.takeCount(),0);});
 for(const mode of ['fail','moved','missing'])await test(`legacy detail ${mode} cannot offer an uninformed continue; readonly retry recovers`,async()=>{const h=harness();h.legacy();h.state.detailMode=mode;h.mount();const old=h.state.storage.get(legacyKey);await h.get('dsRecover').onclick();assert.equal(h.get('dsContinue').hidden,true);await h.get('dsContinue').onclick();assert.equal(h.takeCount(),0);assert.equal(h.state.storage.get(legacyKey),old);h.state.detailMode='normal';await h.get('dsRecover').onclick();assert.equal(h.get('dsContinue').hidden,false);assert.match(h.get('dsRecoveryItem').textContent,/SYNTHETIC-LONG-CODE.*合成库存/);assert.match(h.get('dsRecoveryItem').textContent,/原取用 3只 · 免费打样/);});
 await test('same mounted A but cookies B: actor mismatch preserves key and freezes take',async()=>{const h=harness();h.mount();await h.search();h.state.actor=202;await h.submit();assert.ok(h.state.storage.has(key(101)));assert.equal(h.state.movements.size,0);await h.submit();assert.equal(h.takeCount(),1);});
 await test('resolve current_actor mismatch retains old record and cannot continue/ack',async()=>{const h=harness();h.legacy();h.mount();h.state.actor=202;await h.get('dsRecover').onclick();assert.ok(h.state.storage.has(legacyKey));assert.equal(h.get('dsContinue').hidden,true);await h.get('dsContinue').onclick();assert.equal(h.takeCount(),0);});
 await test('late resolve after remount cannot acknowledge or clear other owner',async()=>{const h=harness();h.legacy();h.recordMovement(h.body,101);h.mount();let release;h.state.defer={promise:new Promise(r=>release=r)};const wait=h.get('dsRecover').onclick();await tick();h.window.TmDimensionStock.destroy();h.state.actor=202;h.mount();const old=h.state.storage.get(legacyKey);h.state.defer=null;release();await wait;assert.equal(h.state.storage.get(legacyKey),old);assert.equal(h.get('dsReceipt').hidden,true);assert.equal(h.get('dsRecoveryAck').hidden,true);});
 assert.match(mobile,/clearMobilePortalState\(\) \{\s*window\.TmDimensionStock\?\.destroy\(\)/);
 assert.match(mobile,/TmDimensionStock\?\.mount\(\{apiGet, apiPost, userId:user\.id/);
 assert.equal((mobile.match(/TmDimensionStock\?\.mount/g)||[]).length,1);
 console.log(`${cases.length} recovery scenarios passed: real DOM handlers/API parser, synthetic ledger and account/storage boundaries`);
 if(process.env.TM_RECOVERY_EVIDENCE)fs.writeFileSync(process.env.TM_RECOVERY_EVIDENCE,JSON.stringify({scope:'Synthetic VM DOM handlers and in-memory ledger; no formal data writes or administrator acceptance',sourceHashes:{mobile:crypto.createHash('sha256').update(mobile).digest('hex'),dimension:crypto.createHash('sha256').update(script).digest('hex')},cases},null,2));
})().catch(error=>{console.error(error);process.exitCode=1});
