const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),baseline=process.env.TM_STOCKTAKE_BASELINE,html=baseline?require('node:child_process').execFileSync('git',['show',`${baseline}:static/mobile_stocktake.html`],{cwd:root,encoding:'utf8'}):fs.readFileSync(path.join(root,'static/mobile_stocktake.html'),'utf8');
const modulePath=path.join(root,'static/ui/mobile-stocktake-recovery.js');
const clone=value=>JSON.parse(JSON.stringify(value)),tick=()=>new Promise(r=>setImmediate(r));
class Element{
 constructor(id,dom){this.id=id;this.dom=dom;this.value='';this.textContent='';this.disabled=false;this.hidden=false;this.dataset={};this.classes=new Set();this.attrs={};this.listeners={};this.options=[];this.firstElementChild={textContent:''};this.classList={add:c=>this.classes.add(c),remove:c=>this.classes.delete(c),contains:c=>this.classes.has(c),toggle:(c,on)=>on?this.classes.add(c):this.classes.delete(c)};}
 set innerHTML(value){this.markup=value;if(this.id==='lotList')this.dom.clearCounts();for(const match of value.matchAll(/<input[^>]*id="(count-[^"]+)"[^>]*>/g)){const node=this.dom.get(match[1]);node.value=match[0].match(/value="([^"]*)"/)?.[1]||'';node.dataset.lotId=match[0].match(/data-lot-id="([^"]*)"/)?.[1];node.disabled=/\sdisabled/.test(match[0]);}}
 get innerHTML(){return this.markup||'';}
 setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k]??null;}
 addEventListener(k,fn){this.listeners[k]=fn;}removeEventListener(k){delete this.listeners[k];}scrollIntoView(){this.scrolls=(this.scrolls||0)+1;}focus(){}append(){}replaceChildren(){}
}
function harness({actor=101,role='admin',storage=new Map()}={}){
 const nodes=new Map(),dom={get(id){if(!nodes.has(id))nodes.set(id,new Element(id,dom));return nodes.get(id);},clearCounts(){for(const key of nodes.keys())if(key.startsWith('count-'))nodes.delete(key);}};
 for(const match of html.slice(0,html.indexOf('<script>')).matchAll(/id="([^"]+)"/g))dom.get(match[1]);
 const data={actor,role,mode:'normal',resolveMode:'normal',posts:[],gets:[],storage,failStorage:'',ledger:new Map(),refreshFail:false,deferred:null,redirects:[],writes:[],messages:[],mutate:null};
 const location={id:42,layout_version:1,address_version:2,position_status:'active',published_map_revision:'synthetic-map',employee_location_name:'三楼 北区 A货架 第2层 第1格',floor_name:'三楼',floor_code:'3F',area_code:'A',area_name:'北区'};
 const lots=[{inventory_lot_id:7,version:3,quantity_available:18,quantity_reserved:2,system_quantity:20,unit:'boxes',inventory_code:'SYNTHETIC-80011946-LONG-CODE',product_name:'合成纸箱',customer_id:1,customer_short_name:'合成客户',specification:'500×300×200'}];
 const storageApi={get length(){if(data.failStorage==='get')throw Error('synthetic storage read failure');return storage.size;},key:i=>[...storage.keys()][i]||null,getItem(k){if(data.failStorage==='get')throw Error('synthetic storage read failure');return storage.get(k)??null;},setItem(k,v){if(data.failStorage==='set'||(data.failStorage==='confirmed-set'&&JSON.parse(v).outcome==='confirmed'))throw Error('synthetic storage write failure');storage.set(k,v);data.writes.push({k,v});},removeItem(k){if(data.failStorage==='remove')throw Error('synthetic storage remove failure');storage.delete(k);}};
 const response=(status,raw,headers={})=>({status,ok:status>=200&&status<300,text:async()=>typeof raw==='string'?raw:JSON.stringify(raw),headers:{get:k=>headers[k]||null}});
 const receipt=(body,action,owner=actor)=>({id:9001,stocktake_number:'ST-SYNTHETIC-001',location_id:body.location_id,location_layout_version:body.location_layout_version,location_address_version:body.location_address_version,location_position_status:body.location_position_status,published_map_revision:body.published_map_revision,status:action==='confirm'?'approved':'submitted',version:3,submitted_by:owner,submitted_by_name:'合成班长',reviewed_by:action==='confirm'?owner:null,reviewed_at:action==='confirm'?'2026-10-10T12:00:00Z':null,idempotency_key:action==='confirm'?'mobile-confirm-'+crypto.createHash('sha256').update(body.idempotency_key).digest('hex'):body.idempotency_key,request_action:action,request_idempotency_key:body.idempotency_key,current_actor_id:data.actor,items:body.items.map(row=>({inventory_lot_id:row.inventory_lot_id,counted_quantity:row.counted_quantity,lot_version_snapshot:row.expected_version,quantity_available_snapshot:row.expected_available,quantity_reserved_snapshot:row.expected_reserved})),reviews:action==='confirm'?[{id:1,reviewed_by:owner,reviewed_at:'2026-10-10T12:00:00Z',from_status:'submitted',action:'approve',to_status:'approved'}]:[]});
 const window={location:{search:'?location_id=42&return_floor=3F&return_area=A',origin:'http://synthetic',assign:url=>data.redirects.push(url)},localStorage:storageApi,parent:{postMessage(){}},addEventListener(){},removeEventListener(){}};
 const document={getElementById:id=>dom.get(id),documentElement:{classList:{add(){}}},querySelector:selector=>selector.includes('.header-link')?dom.get('header-link'):selector.startsWith('[data-lot-id=')?[...nodes.values()].find(n=>n.dataset.lotId===selector.match(/"(.*?)"/)?.[1]):dom.get(selector.replace('#','')),querySelectorAll:selector=>selector==='.count-input'?[...nodes.values()].filter(n=>n.id.startsWith('count-')):[],createElement:()=>new Element('',dom)};
 const context=vm.createContext({window,document,localStorage:storageApi,sessionStorage:storageApi,URLSearchParams,AbortController,Uint8Array,TextEncoder,crypto:crypto.webcrypto,CSS:{escape:v=>String(v)},console,setTimeout,clearTimeout,
 fetch:async(url,options={})=>{
  if(options.method!=='POST'){data.gets.push(url);if(data.refreshFail)throw Error('synthetic read failure');if(url==='/api/auth/me')return response(200,{user:{id:data.actor,role:data.role}});if(url==='/api/warehouse/stocktake/locations')return response(200,{items:[location,{...location,id:43,employee_location_name:'三楼 北区 A货架 第2层 第2格'}]});const other=url.endsWith('/43');return response(200,{...location,id:other?43:42,employee_location_name:other?'三楼 北区 A货架 第2层 第2格':location.employee_location_name,items:other?[{...lots[0],inventory_lot_id:8,version:4,quantity_available:40,quantity_reserved:0,system_quantity:40}]:clone(lots)});}
  const body=JSON.parse(options.body),resolving=url.endsWith('/resolve'),action=resolving?body.action:url.endsWith('/confirm')?'confirm':'submit',request=resolving?body.body:body;
  data.posts.push({url,body:clone(body)});if(data.deferred)await data.deferred;
  if(data.mode==='network-before')throw Error('synthetic disconnected');
  if(data.mode.startsWith('error-'))return response(Number(data.mode.slice(6)),{detail:{code:data.mode==='error-409'?'STOCKTAKE_DRIFT':'SYNTHETIC_ERROR',message:'合成拒绝'}});
  if(request.expected_actor_id!==undefined&&request.expected_actor_id!==data.actor)return response(409,{detail:{code:'STOCKTAKE_ACTOR_MISMATCH',message:'账号已变化'}},{'X-Stocktake-Preserve':'1','X-Stocktake-Actor-Mismatch':'1'});
  if(resolving){const malformed={empty:'',invalid:'{broken',null:'null',partial:{status:'not_found'}};if(Object.hasOwn(malformed,data.resolveMode))return response(200,malformed[data.resolveMode]);const order=data.ledger.get(request.idempotency_key);const result={status:order?'found':'not_found',request_action:action,request_idempotency_key:request.idempotency_key,current_actor_id:data.actor,observed_at:'2026-10-10T12:00:00Z',order:order?{...order,current_actor_id:data.actor}:null};if(data.mutate)data.mutate(result,true);return response(200,result);}
  const order=data.ledger.get(request.idempotency_key)||receipt(request,action);data.ledger.set(request.idempotency_key,order);
  if(data.mode==='network-after')throw Error('synthetic response lost');
  const malformed={empty:'',invalid:'{broken',null:'null',partial:{stocktake_number:'ST-SYNTHETIC-001'}};
  const result=clone(order);if(data.mutate)data.mutate(result,false);return response(201,Object.hasOwn(malformed,data.mode)?malformed[data.mode]:result);
 }});
 if(!baseline&&fs.existsSync(modulePath))vm.runInContext(fs.readFileSync(modulePath,'utf8'),context);
 const inline=html.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/;init\(\);\s*$/, ';');
 vm.runInContext(inline+'\nwindow.__page={state,submitStocktake,openLocation,showLogin,init,fillAll};',context);
 vm.runInContext(`state.user={id:${actor},role:${JSON.stringify(role)}};state.locations=${JSON.stringify([location])};state.selectedLocation=${JSON.stringify(location)};state.lots=${JSON.stringify(lots)};captureLotSnapshots(state.lots);renderLots();if(typeof mountStocktakeRecovery==='function')mountStocktakeRecovery();`,context);
 dom.get('count-7').value='20';
 return {data,window,context,get:id=>dom.get(id),page:window.__page,submit:()=>window.__page.submitStocktake(),receipt,tick,controller:()=>vm.runInContext('stocktakeRecovery',context),run:source=>vm.runInContext(source,context),writes:()=>data.posts.filter(row=>!row.url.endsWith('/resolve'))};
}
const cases=[],failures=[];
async function test(name,fn){try{await fn();cases.push(name);}catch(error){failures.push({name,error:error.stack});}}
(async()=>{
 for(const mode of ['empty','invalid','null','partial'])await test(`${mode} 2xx stays unknown, preserves input and owner request`,async()=>{const h=harness();h.data.mode=mode;await h.submit();assert.doesNotMatch(h.get('message').innerHTML,/已确认|提交成功/);assert.ok(h.data.storage.size);assert.equal(h.get('count-7').value,'20');assert.equal(h.get('count-7').disabled,true);});
 await test('first409 drift cannot discard original request',async()=>{const h=harness();h.data.mode='error-409';await h.submit();assert.ok(h.data.storage.size);assert.equal(h.get('count-7').value,'20');});
 await test('network unknown survives page reload with exact original request',async()=>{const h=harness();h.data.mode='network-after';await h.submit();const saved=[...h.data.storage.values()][0];assert.ok(saved);const reloaded=harness({storage:h.data.storage});assert.equal([...reloaded.data.storage.values()][0],saved);assert.equal(reloaded.get('count-7').disabled,true);});
 if(!baseline){
 for(const broken of ['lot-zero','lot-missing','address-zero','status-long','map-empty','unsafe-count'])await test(`invalid new body ${broken} is neither stored nor sent`,async()=>{const h=harness();if(broken==='lot-zero')h.run('state.lotSnapshots[7].expected_version=0');if(broken==='lot-missing')h.run('delete state.lotSnapshots[7].expected_version');if(broken==='address-zero')h.run('state.selectedLocation.address_version=0');if(broken==='status-long')h.run("state.selectedLocation.position_status='a'.repeat(31)");if(broken==='map-empty')h.run("state.selectedLocation.published_map_revision=''");if(broken==='unsafe-count')h.get('count-7').value='9007199254740992';await h.submit();assert.equal(h.writes().length,0);assert.equal(h.data.storage.size,0);});
 await test('normal admin full receipt confirms with no subtle and clears only its original record',async()=>{const h=harness();h.context.crypto={randomUUID:crypto.randomUUID};await h.submit();assert.equal(h.data.storage.size,0);assert.equal(h.data.ledger.size,1);assert.match(h.get('message').innerHTML,/库存已按实盘数量更新/);assert.equal(h.data.posts[0].body.expected_actor_id,101);assert.equal(h.get('count-7').value,'');});
 await test('normal employee submission reports waiting review without claiming stock updated',async()=>{const h=harness({role:'warehouse'});await h.submit();assert.equal(h.data.storage.size,0);assert.match(h.get('message').innerHTML,/等待仓库审核/);assert.doesNotMatch(h.get('message').innerHTML,/库存已按/);assert.equal(h.writes()[0].url,'/api/warehouse/stocktakes');});
 for(const mode of ['empty','invalid','null','partial','network-after'])await test(`${mode} readonly resolve finds original, not a second write`,async()=>{const h=harness();h.data.mode=mode;await h.submit();const original=clone(h.writes()[0].body);h.data.mode='normal';await h.get('stocktakeResolve').onclick();assert.equal(h.writes().length,1);assert.equal(h.data.storage.size,0);assert.deepEqual(h.data.posts[1].body,{action:'confirm',body:original});});
 for(const [field,value] of [['id',0],['stocktake_number',''],['version','3'],['location_id',43],['location_layout_version',2],['location_address_version',3],['location_position_status','unplaced'],['published_map_revision','other'],['request_action','submit'],['request_idempotency_key','other'],['idempotency_key','other'],['submitted_by',202],['current_actor_id',null],['current_actor_id','101'],['status','submitted'],['reviews',[]]])await test(`receipt ${field}=${JSON.stringify(value)} cannot clear original`,async()=>{const h=harness();h.data.mutate=order=>order[field]=value;await h.submit();assert.equal(h.data.storage.size,1);assert.doesNotMatch(h.get('message').innerHTML,/已确认并更新|管理员盘点已确认/);});
 for(const field of ['counted_quantity','lot_version_snapshot','quantity_available_snapshot','quantity_reserved_snapshot','inventory_lot_id'])await test(`wrong frozen ${field} stays unknown`,async()=>{const h=harness();h.data.mutate=order=>order.items[0][field]++;await h.submit();assert.equal(h.data.storage.size,1);});
 await test('duplicate receipt lot cannot collapse into success',async()=>{const h=harness();h.data.mutate=order=>order.items.push(clone(order.items[0]));await h.submit();assert.equal(h.data.storage.size,1);});
 await test('client_line_id is preserved on retry without requiring it on receipt',async()=>{const h=harness();h.data.mode='network-before';await h.submit();const original=clone(h.writes()[0].body);h.data.mode='normal';await h.get('stocktakeResolve').onclick();assert.match(h.get('stocktakeRecoveryStatus').textContent,/原条件若已变化/);assert.equal(h.writes().length,1);await h.get('stocktakeRetry').onclick();assert.deepEqual(h.writes()[1].body,original);assert.equal(h.data.storage.size,0);});
 for(const status of [401,403,404,409,422,500])await test(`HTTP ${status} always preserves original, including first drift`,async()=>{const h=harness();h.data.mode=`error-${status}`;await h.submit();assert.equal(h.data.storage.size,1);if(status!==401)assert.equal(h.get('count-7').value,'20');});
 for(const mode of ['empty','invalid','null','partial'])await test(`resolve ${mode} incomplete stays retryable readonly`,async()=>{const h=harness();h.data.mode='network-after';await h.submit();const saved=[...h.data.storage.values()][0];h.data.mode='normal';h.data.resolveMode=mode;await h.get('stocktakeResolve').onclick();assert.equal([...h.data.storage.values()][0],saved);assert.equal(h.get('stocktakeResolve').disabled,false);h.data.resolveMode='normal';await h.get('stocktakeResolve').onclick();assert.equal(h.data.storage.size,0);});
 for(const outcome of ['approved','rejected'])await test(`employee original later ${outcome} displays actual state`,async()=>{const h=harness({role:'warehouse'});h.data.mode='network-after';await h.submit();const order=[...h.data.ledger.values()][0];order.status=outcome;order.reviewed_by=301;order.reviewed_at='2026-10-10T13:00:00Z';order.reviews=[{id:1,reviewed_by:301,reviewed_at:order.reviewed_at,from_status:'submitted',action:outcome==='approved'?'approve':'reject',to_status:outcome}];h.data.mode='normal';await h.get('stocktakeResolve').onclick();assert.equal(h.data.storage.size,0);assert.match(h.get('message').innerHTML,outcome==='approved'?/库存已按/:/审核退回/);});
 for(const failure of ['get','set'])await test(`storage ${failure} prevents all business sends`,async()=>{const h=harness();h.data.failStorage=failure;if(failure==='get')h.run('mountStocktakeRecovery()');await h.submit();assert.equal(h.writes().length,0);});
 for(const failure of ['remove','confirmed-set'])await test(`confirmed cleanup ${failure}: only same location frozen, no business retry`,async()=>{const h=harness();h.data.failStorage=failure;await h.submit();assert.equal(h.data.ledger.size,1);assert.equal(h.controller().state().pending.outcome,'confirmed');h.data.failStorage='';h.controller().reload();h.data.ledger.clear();await h.get('stocktakeResolve').onclick();assert.equal(h.get('stocktakeRetry').classList.contains('hidden'),true);await h.get('stocktakeRetry').onclick();assert.equal(h.writes().length,1);});
 await test('successful commit plus failed refresh preserves success; retry reads GET only',async()=>{const h=harness();h.data.refreshFail=true;await h.submit();assert.equal(h.data.storage.size,0);assert.match(h.get('message').innerHTML,/库存尚未刷新/);assert.equal(h.get('stocktakeRefreshReceipt').classList.contains('hidden'),false);assert.equal(h.get('stocktakeRecoveryTitle').textContent,'盘点已确认，库存待刷新');assert.equal(h.page.state.selectedLocation.employee_location_name,'三楼 北区 A货架 第2层 第1格');h.data.refreshFail=false;await h.get('stocktakeRefreshReceipt').onclick();assert.equal(h.writes().length,1);assert.equal(h.get('stocktakeRecoveryPanel').classList.contains('hidden'),true);});
 await test('unknown current result scrolls message into view',async()=>{const h=harness();h.data.mode='empty';await h.submit();assert.equal(h.get('message').scrolls,1);});
 await test('A readonly late receipt leaves B focus and input alone',async()=>{const h=harness();h.data.mode='network-after';await h.submit();h.data.mode='normal';let release;h.data.deferred=new Promise(r=>release=r);const result=h.get('stocktakeResolve').onclick();await tick();h.run("state.selectedLocation={...state.selectedLocation,id:43}");h.get('count-7').value='39';const before=h.get('message').scrolls;release();await result;assert.equal(h.get('message').scrolls,before);assert.equal(h.get('count-7').value,'39');});
 await test('pending double click sends one immutable body',async()=>{const h=harness();let release;h.data.deferred=new Promise(r=>release=r);const first=h.submit();await tick();await h.submit();assert.equal(h.writes().length,1);release();await first;});
 await test('unknown edit/fill/reset cannot change saved quantity or key',async()=>{const h=harness();h.data.mode='network-before';await h.submit();const saved=[...h.data.storage.values()][0];h.get('count-7').value='99';h.get('count-7').oninput();h.page.fillAll();h.run('resetMobileSubmitAttempt()');assert.equal(h.get('count-7').value,'20');assert.equal([...h.data.storage.values()][0],saved);await h.submit();assert.equal(h.writes().length,1);});
 await test('A late success after account remount cannot clear A record or overwrite B input',async()=>{const h=harness();let release;h.data.deferred=new Promise(r=>release=r);const first=h.submit();await tick();const original=[...h.data.storage.values()][0];h.run("state.user={id:202,role:'admin'};mountStocktakeRecovery()");h.get('count-7').value='35';release();await first;assert.equal([...h.data.storage.values()][0],original);assert.equal(h.get('count-7').value,'35');});
 await test('late old401 cannot log out newly mounted account',async()=>{const h=harness();let release;h.data.deferred=new Promise(r=>release=r);const first=h.submit();await tick();h.run("state.user={id:202,role:'admin'};mountStocktakeRecovery()");h.data.mode='error-401';release();await first;assert.equal(h.page.state.user.id,202);assert.equal(h.data.storage.size,1);});
 await test('actual cookie actor change locks account and keeps original record',async()=>{const h=harness();h.data.actor=202;await h.submit();assert.equal(h.controller().state().accountChanged,true);assert.equal(h.data.storage.size,1);await h.submit();assert.equal(h.writes().length,1);});
 await test('shared storage second tab cannot overwrite same-location unknown',async()=>{const store=new Map(),a=harness({storage:store}),b=harness({storage:store});a.data.mode='network-before';await a.submit();const original=[...store.values()][0];await b.submit();assert.equal(b.writes().length,0);assert.equal(store.size,1);assert.equal([...store.values()][0],original);});
 await test('other account does not read or clear A records',async()=>{const store=new Map(),a=harness({storage:store});a.data.mode='network-before';await a.submit();const original=[...store.entries()][0];const b=harness({actor:202,storage:store});await b.submit();assert.equal(store.get(original[0]),original[1]);assert.equal(store.size,1);});
 await test('A unknown does not lock B location; both records survive and A resolve does not overwrite B input',async()=>{const h=harness();h.data.mode='network-after';await h.submit();const aBody=clone(h.writes()[0].body);h.run("state.selectedLocation=null;stocktakeRecoveryState.blocked=false;resetToLocations('');state.selectedLocation={...state.locations[0],id:43};state.lots=[{inventory_lot_id:7,version:3,quantity_available:18,quantity_reserved:2,system_quantity:20,unit:'boxes'}];captureLotSnapshots(state.lots);renderLots()");h.get('count-7').value='25';await h.submit();assert.equal(h.data.storage.size,2);assert.notEqual(h.writes()[0].body.idempotency_key,h.writes()[1].body.idempotency_key);assert.equal(h.writes()[1].body.location_id,43);const a=h.controller().state().records.find(row=>row.body.location_id===42);h.controller().select(h.controller().keyFor(a));h.run("renderedStocktakeRequest=stocktakeRecoveryState.pending.body.idempotency_key;state.selectedLocation={...state.selectedLocation,id:43};state.lots=[{inventory_lot_id:7,unit:'boxes'}]");h.get('count-7').value='25';h.data.mode='normal';await h.get('stocktakeResolve').onclick();assert.equal(h.get('count-7').value,'25');assert.equal(h.page.state.selectedLocation.id,43);assert.equal(h.data.storage.size,1);assert.equal(JSON.parse([...h.data.storage.values()][0]).body.location_id,43);assert.equal(h.writes().length,2);assert.equal(aBody.location_id,42);});
 await test('A confirmed cleanup failure permits B latest-location submission and retains known A success',async()=>{const h=harness();h.data.failStorage='remove';await h.submit();const aKey=[...h.data.storage.keys()][0];h.data.failStorage='';h.run("state.selectedLocation=null;stocktakeRecoveryState.blocked=false;state.locked=false;resetToLocations('');state.selectedLocation={...state.locations[0],id:43};state.lots=[{inventory_lot_id:7,version:3,quantity_available:18,quantity_reserved:2,system_quantity:20,unit:'boxes'}];captureLotSnapshots(state.lots);renderLots()");h.get('count-7').value='25';await h.submit();assert.equal(h.writes().length,2);assert.equal(h.data.storage.size,1);assert.ok(h.data.storage.has(aKey));h.controller().select(aKey);assert.equal(h.controller().state().pending.outcome,'confirmed');});
 await test('visible change-location then actual B detail releases A input/add locks and saves independent body',async()=>{const h=harness();h.data.mode='network-before';await h.submit();const original=[...h.data.storage.entries()][0];h.get('stocktakeChangeLocation').onclick();await tick();await h.page.openLocation(43);assert.equal(h.page.state.selectedLocation.id,43);assert.equal(h.get('count-8').disabled,false);assert.equal(h.get('inboundFields').disabled,false);assert.equal(h.get('initialInbound').inert,false);h.get('count-8').value='39';h.get('count-8').oninput();assert.equal(h.get('submitButton').disabled,false);h.data.mode='normal';await h.submit();assert.equal(h.writes().length,2);assert.equal(h.writes()[1].body.location_id,43);assert.equal(h.writes()[1].body.items[0].inventory_lot_id,8);assert.equal(h.writes()[1].body.items[0].expected_version,4);assert.equal(h.data.storage.get(original[0]),original[1]);assert.match(h.get('stocktakeRecoveryStatus').textContent,/这些请求仍未确认/);assert.match(h.get('message').innerHTML,/第2层 第2格/);});
 await test('true cold init selectedLocation null immediately freezes recovered original inputs',async()=>{const old=harness();old.data.mode='network-before';await old.submit();const h=harness({storage:old.data.storage});h.run('destroyStocktakeRecovery();state.user=null;state.selectedLocation=null;state.lots=[]');await h.page.init();assert.equal(h.page.state.selectedLocation.id,42);assert.equal(h.get('count-7').value,'20');assert.equal(h.get('count-7').disabled,true);assert.equal(h.get('submitButton').disabled,true);assert.equal(h.get('inboundFields').disabled,true);assert.equal(h.get('stocktakeResolve').disabled,false);});
 for(const [field,value] of [['id',0],['reviewed_by',202],['reviewed_at',''],['from_status','approved'],['action','reject']])await test(`truncated or conflicting review ${field} remains unknown`,async()=>{const h=harness();h.data.mutate=order=>order.reviews[0][field]=value;await h.submit();assert.equal(h.data.storage.size,1);});
 for(const key of ['abc','test-key-0123456789','中文盘点键-甲-🚚','a'.repeat(120)])await test(`LAN pure UTF8 SHA256 matches trusted digest: ${key.slice(0,15)}`,async()=>{const h=harness();assert.equal(h.window.TmStocktakeRecovery.sha256(key),crypto.createHash('sha256').update(key).digest('hex'));});
 }
 if(failures.length){console.error(JSON.stringify({passed:cases.length,failed:failures},null,2));process.exitCode=1;}else console.log(`${cases.length} stocktake recovery scenarios passed`);
 if(process.env.TM_STOCKTAKE_EVIDENCE)fs.writeFileSync(process.env.TM_STOCKTAKE_EVIDENCE,JSON.stringify({cases,failures,sourceHash:crypto.createHash('sha256').update(html).digest('hex')},null,2));
})();

