const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),crypto=require('node:crypto');
const repo=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(repo,'static/index.html'),'utf8');
const source=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).find(x=>x.trim());
const store=new Map();const storage={get length(){return store.size},key:i=>[...store.keys()][i]??null,getItem:k=>store.get(k)??null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const box={axios:{defaults:{},interceptors:{response:{use(){}}}},Vue:{createApp(d){box.methods=d.methods;return{component(){return this},mixin(d){Object.assign(box.methods,d.methods);return this},mount(){return this}}}},localStorage:storage,window:{},TMOrderReference:{component:{}},console,URLSearchParams,setTimeout,clearTimeout};
box.axios.create=config=>{box.lastHttpConfig=config;return box.axios};
vm.createContext(box);vm.runInContext(source,box);
vm.runInContext(fs.readFileSync(path.join(repo,'static/ui/pdf-workspace.js'),'utf8'),box);box.window.ERPPdfWorkspace.install({mixin(d){Object.assign(box.methods,d.methods)}});
const moduleFile=path.join(repo,'static/ui/order-import-save-recovery.js');if(fs.existsSync(moduleFile))vm.runInContext(fs.readFileSync(moduleFile,'utf8'),box);
function draft(name='one'){return{source_name:name,file_hash:name,order_date:'2026-10-10',confirmed:true,matched_customer_id:1,customer_po:'PO-'+name,preview_safety_token:'synthetic-token',integrity_check:{integrity_status:'passed'},items:[{matched_product_id:1,quantity:10,unit_price:1}],_save_status:'idle'};}
function context(ds){return {...box.methods,user:{id:7},authGeneration:1,modal:{type:'orderPdfImport'},orderImportDrafts:ds,orderImportBatch:{retryDraft:null},toasts:[],canConfirmImportDraft:()=>true,prepareMoldRepairConfirmation:async()=>({confirmed:true,confirmation_token:null}),refreshImportDraftInventoryForSave:async()=>{},refreshPdfPriceConflict(){},inventoryDecisionRequired:()=>'',pdfImportItemMaterialCode:()=>'',buildReservationPlan:()=>({finished:[],semi:[]}),loadOrders:async()=>{},loadKpi:async()=>{},showToast(m,b){this.toasts.push({message:m,error:!!b})},showOrderNextStepGuide(){},refreshEmailQueueCount(){},normalizeOrderSaveError:()=> 'synthetic failure'};}
const results=[];let posts=[];
function receipt(body,owner=7,pricing=true,alias=false){
 const api=box.window.ERPOrderImportSaveRecovery;
 const lines=body.items.map((i,n)=>({request_client_line_id:i.client_line_id,original_client_line_id:alias?'original-'+n:i.client_line_id,order_item_id:n+10,request_product_id:i.product_id??null,is_new_product:!!i.is_new_product,product_id:i.product_id||50,quantity:String(i.quantity),...(pricing?{unit_price:String(i.unit_price)}:{})}));
 const order={id:1,order_number:'SO-TEST-001',customer_id:body.customer_id,customer_po:(body.customer_po||'').trim()||null,items:lines.map((l,n)=>({id:l.order_item_id,item_sequence:n+1,client_line_id:l.original_client_line_id,product_id:l.product_id,quantity:l.quantity,...(pricing?{unit_price:l.unit_price}:{})}))};
 return {id:1,customer_id:body.customer_id,current_actor_id:owner,save_receipt:{schema:'order-import-save-v1',request_key:body.idempotency_key,actor_id:owner,payload_digest:'a'.repeat(64),proof_status:'complete',source_replay:alias,pricing_visible:pricing,request_match:true,request:api.projection(body,pricing,body.readback_contract==='a01-v1'),order,lines,line_count:lines.length,source:body.import_draft?{id:1,kind:'pdf',hash:String(body.customer_po||'').replace(/^PO-/,''),name:'synthetic.pdf'}:null}};
}
async function test(name,f){store.clear();posts=[];box.axios.get=async()=>({data:{status:'not_found'}});box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:{}}};try{await f();results.push({name,passed:true})}catch(e){results.push({name,passed:false,error:e.message})}}
(async()=>{
 if(box.window.ERPOrderImportSaveRecovery){
  const api=box.window.ERPOrderImportSaveRecovery;
  const payload=(key='original-key',owner=7)=>JSON.stringify({idempotency_key:key,expected_actor_id:owner,customer_id:1,items:[{client_line_id:'row-one',product_id:1,quantity:10,unit_price:1}]});
  await test('storage-original-body-exact-and-independent-keys',async()=>{const s=api.createStore(storage,7),a=s.prepare('fileA',payload(),{fileName:'A.pdf'}),b=s.prepare('fileB',payload('other-key'),{fileName:'B.xlsx'});assert.equal(s.find('fileA')[0].bodyJson,payload());assert.equal(s.all().length,2);assert.notEqual(a.storageKey,b.storageKey);assert.throws(()=>s.prepare('fileA',payload('third-key'),{}));assert.equal(s.all().length,2)});
  await test('shared-storage-two-pages-never-overwrite-records',async()=>{const a=api.createStore(storage,7),b=api.createStore(storage,7);a.prepare('fileA',payload(),{});b.prepare('fileB',payload('other-key'),{});assert.equal(a.all().length,2);assert.throws(()=>b.prepare('fileA',payload('new-key'),{}));assert.equal(a.find('fileA')[0].key,'original-key')});
  await test('different-actors-are-isolated',async()=>{const a=api.createStore(storage,7),b=api.createStore(storage,8);a.prepare('fileA',payload(),{});assert.equal(b.all().length,0);b.prepare('fileA',payload('other-key',8),{});assert.equal(a.all().length,1);assert.equal(b.all().length,1)});
  await test('legacy-v1-preserved-without-inventing-body',async()=>{storage.setItem('erp.pdf-save.v1:7:fileA','original-key');const s=api.createStore(storage,7),r=s.find('fileA')[0];assert.equal(r.legacy,true);assert.equal(r.bodyJson,null);assert.throws(()=>s.prepare('fileA',payload('new-key'),{}));s.complete(r,1);assert.equal(storage.getItem(r.storageKey),'original-key')});
  await test('confirmed-clear-failure-does-not-delete-other-file',async()=>{const broken={...storage,get length(){return store.size},removeItem(){throw Error('storage denied')}},s=api.createStore(broken,7),a=s.prepare('fileA',payload(),{});s.prepare('fileB',payload('other-key'),{});const r=s.complete(a,1);assert.equal(r.retained,true);assert.equal(s.find('fileA')[0].phase,'confirmed');assert.equal(s.find('fileB')[0].phase,'unknown')});
  await test('changed-record-is-not-cleared',async()=>{const s=api.createStore(storage,7),a=s.prepare('fileA',payload(),{}),raw=JSON.parse(storage.getItem(a.storageKey));raw.bodyJson=payload().replace('quantity":10','quantity":22');storage.setItem(a.storageKey,JSON.stringify(raw));assert.equal(s.complete(a,1).retained,true);assert.equal(JSON.parse(storage.getItem(a.storageKey)).bodyJson,raw.bodyJson)});
 }
 await test('empty-2xx-keeps-original-body-unknown',async()=>{const d=draft(),c=context([d]);await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'unknown');assert.ok(d._save_payload);assert.equal(c.isImportDraftLocked(d),true);assert.ok(!c.toasts.some(t=>t.message.includes('已保存 1')))});
 await test('body-durable-before-first-post',async()=>{const d=draft(),c=context([d]);let seen;box.axios.post=async(u,p)=>{seen=[...store.values()].some(raw=>{try{return JSON.parse(raw).bodyJson===JSON.stringify(p)}catch{return false}});throw Error('response lost')};await c.saveConfirmedImportDrafts(d);assert.equal(seen,true)});
 await test('refresh-restores-original-body-not-new-quantity',async()=>{const d=draft(),c=context([d]);box.axios.post=async()=>{throw Error('response lost')};await c.saveConfirmedImportDrafts(d);const original=d._save_payload,next=draft();next.items[0].quantity=22;const reloaded=context([next]);reloaded.restorePdfSaveAttempt(next);assert.equal(next._save_payload,original);assert.equal(next._save_status,'unknown')});
 await test('incomplete-completed-does-not-post-write',async()=>{const d=draft(),c=context([d]);d._create_key='original-key';d._save_actor_id=7;d._save_status='unknown';d._save_payload=JSON.stringify({idempotency_key:'original-key',customer_id:1,items:[{product_id:1,quantity:10,unit_price:1}]});box.axios.get=async()=>({data:{status:'completed'}});await c.retryFailedImportDraft(d);assert.equal(posts.filter(r=>r.url==='/api/orders').length,0);assert.equal(d._save_status,'unknown');assert.ok(d._save_payload)});
 await test('normal-full-receipt-and-source-alias-accepted',async()=>{for(const alias of [false,true]){store.clear();const d=draft(),c=context([d]);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:receipt(p,7,true,alias)}};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'success');assert.equal(d._saved_order_id,1);assert.equal(store.size,0)}});
 await test('no-price-valid-complete-is-success',async()=>{const d=draft(),c=context([d]);box.axios.post=async(u,p)=>({data:receipt(p,7,false)});await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'success');assert.equal(d._saved_order_id,1)});
 await test('new-product-null-request-maps-real-product',async()=>{const d=draft(),c=context([d]);d.items[0].is_new_product=true;box.axios.post=async(u,p)=>({data:receipt(p)});await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'success')});
 for(const change of ['actor','key','customer','quantity','price','line','echo','incomplete','digest'])await test('bad-receipt-'+change+'-retains-original',async()=>{const d=draft(),c=context([d]);box.axios.post=async(u,p)=>{const r=receipt(p);if(change==='actor')r.current_actor_id=8;if(change==='key')r.save_receipt.request_key='other-key';if(change==='customer')r.save_receipt.order.customer_id=2;if(change==='quantity')r.save_receipt.lines[0].quantity='11';if(change==='price')r.save_receipt.lines[0].unit_price='2';if(change==='line')r.save_receipt.lines[0].request_client_line_id='wrong';if(change==='echo')r.save_receipt.request.items[0].reservation_plan={};if(change==='incomplete')delete r.save_receipt.order.items;if(change==='digest')r.save_receipt.payload_digest='bad';return{data:r}};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'unknown');assert.ok(d._save_payload);assert.equal(store.size,1)});
 await test('query-not-found-is-readonly-and-continue-explicit-original',async()=>{const d=draft(),c=context([d]);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});throw Error('lost')};await c.saveConfirmedImportDrafts(d);const original=d._save_payload;box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:{status:'not_found',current_actor_id:7,request_key:d._create_key,proof_status:null,save_receipt:null,order:null}}};const before=posts.length;await c.queryPdfSaveAttempt(d);assert.equal(posts.length,before+1);assert.ok(posts.at(-1).url.endsWith('/resolve'));assert.equal(d._save_payload,original);assert.equal(d._save_status,'unknown');assert.equal(d._save_continue_allowed,true);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});throw{response:{status:409}}};await c.continuePdfSaveAttempt(d);assert.equal(posts.at(-1).url,'/api/orders');assert.equal(JSON.stringify(posts.at(-1).body),original);assert.equal(d._save_payload,original);assert.equal(d._save_status,'unknown')});
 await test('reload-open-import-shows-original-without-recognition',async()=>{const d=draft('A.pdf'),c=context([d]);box.axios.post=async()=>{throw Error('lost')};await c.saveConfirmedImportDrafts(d);const body=d._save_payload,fresh=context([]);fresh.openOrderPdfImport();assert.equal(fresh.orderImportRecoveryRows.length,1);assert.equal(fresh.orderImportRecoveryRows[0].bodyJson,body);assert.equal(fresh.pdfRecoveryDetachedRows().length,1);assert.ok(fresh.pdfRecoveryLabel(fresh.orderImportRecoveryRows[0]).includes('A.pdf'))});
 await test('late-success-after-account-change-does-not-clean-key',async()=>{const d=draft(),c=context([d]);let reply;box.axios.post=async(u,p)=>await new Promise(r=>{reply=()=>r({data:receipt(p)})});const run=c.saveConfirmedImportDrafts(d);while(!reply)await new Promise(r=>setTimeout(r,0));c.user={id:8};c.authGeneration++;reply();await run;assert.equal(d._save_status,'unknown');assert.equal(store.size,1);assert.equal(d._saved_order_id,undefined)});
 await test('late-success-after-modal-or-file-change-is-ignored',async()=>{for(const change of ['modal','file']){store.clear();const d=draft(),c=context([d]);let reply;box.axios.post=async(u,p)=>await new Promise(r=>{reply=()=>r({data:receipt(p)})});const run=c.saveConfirmedImportDrafts(d);while(!reply)await new Promise(r=>setTimeout(r,0));if(change==='modal')c.modal={type:'other'};else c.pdfActiveDraftKey='other-file';reply();await run;assert.equal(store.size,1);assert.equal(d._saved_order_id,undefined)}});
 await test('save-success-list-refresh-failure-keeps-proof-and-link',async()=>{const d=draft(),c=context([d]);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:receipt(p)}};c.loadOrders=async()=>{throw Error('refresh failed')};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'success');assert.equal(d._saved_order_id,1);assert.ok(d._save_message.includes('列表未刷新'));assert.equal(posts.length,1)});
 await test('storage-first-write-error-sends-zero-orders',async()=>{const d=draft(),c=context([d]),old=storage.setItem;storage.setItem=()=>{throw Error('denied')};try{await c.saveConfirmedImportDrafts(d);assert.equal(posts.length,0);assert.equal(d._save_status,'failed')}finally{storage.setItem=old}});
 await test('unknown-file-A-does-not-block-file-B',async()=>{const a=draft('A.pdf'),b=draft('B.xlsx'),c=context([a,b]);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});if(p.customer_po==='PO-A.pdf')throw Error('lost');return{data:receipt(p)}};await c.saveConfirmedImportDrafts();assert.equal(a._save_status,'unknown');assert.equal(b._save_status,'success');assert.equal(store.size,1);assert.equal(posts.length,2)});
 await test('first-proven-rejected-version-conflict-can-correct-same-key',async()=>{const d=draft(),c=context([d]);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});throw{response:{status:409,headers:{'x-order-save-rejected':'1'}}}};await c.saveConfirmedImportDrafts(d);const key=d._create_key;assert.equal(d._save_status,'failed');assert.equal(c.isImportDraftLocked(d),false);assert.equal(d.confirmed,false);assert.equal(store.size,0);d.items[0].quantity=11;d.confirmed=true;box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:receipt(p)}};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'success');assert.equal(posts.at(-1).body.idempotency_key,key);assert.equal(posts.at(-1).body.items[0].quantity,11)});
 await test('old-unknown-then-rejected-marker-still-frozen',async()=>{const d=draft(),c=context([d]);box.axios.post=async()=>{throw Error('lost')};await c.saveConfirmedImportDrafts(d);const original=d._save_payload;d._save_record.canContinue=true;box.axios.post=async()=>{throw{response:{status:409,headers:{'x-order-save-rejected':'1'}}}};await c.continuePdfSaveAttempt(d);assert.equal(d._save_status,'unknown');assert.equal(d._save_payload,original);assert.equal(store.size,1)});
 await test('unmarked-or-preserve-422-does-not-unlock',async()=>{for(const headers of [{},{'x-order-save-rejected':'1','x-order-save-preserve':'1'}]){store.clear();const d=draft(),c=context([d]);box.axios.post=async()=>{throw{response:{status:422,headers}}};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'unknown');assert.ok(d._save_payload)}});
 await test('finite-timeout-exits-busy-with-original-retained',async()=>{const d=draft(),c=context([d]);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});throw Object.assign(Error('timeout'),{code:'ECONNABORTED'})};await c.saveConfirmedImportDrafts(d);assert.equal(box.lastHttpConfig.timeout,60000);assert.equal(box.lastHttpConfig.withCredentials,true);assert.equal(c.loading,false);assert.equal(d._save_status,'unknown');assert.ok(d._save_payload);assert.equal(posts.length,1)});
 await test('resolve-complete-applies-full-original-proof-with-zero-order-post',async()=>{const d=draft(),c=context([d]);box.axios.post=async()=>{throw Error('lost')};await c.saveConfirmedImportDrafts(d);const body=JSON.parse(d._save_payload),r=receipt(body);box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:{status:'completed',current_actor_id:7,request_key:d._create_key,proof_status:'complete',save_receipt:r.save_receipt,order:{id:1,order_number:'SO-TEST-001',customer_id:1}}}};await c.queryPdfSaveAttempt(d);assert.equal(d._save_status,'success');assert.equal(store.size,0);assert.equal(posts.filter(x=>x.url==='/api/orders').length,0);assert.equal(posts.length,1)});
 await test('same-file-multiple-existing-records-preserved-and-no-new-post',async()=>{const api=box.window.ERPOrderImportSaveRecovery,s=api.createStore(storage,7),body=JSON.stringify({idempotency_key:'request-A',expected_actor_id:7,customer_id:1,items:[{client_line_id:'a',product_id:1,quantity:10,unit_price:1}]}),a=s.prepare('one',body,{}),b=s.prepare('other',body.replace('request-A','request-B'),{});const record=JSON.parse(storage.getItem(b.storageKey));record.fileHash='one';storage.setItem(b.storageKey,JSON.stringify(record));const d=draft(),c=context([d]);c.restorePdfSaveAttempt(d);assert.equal(d._save_status,'unknown');assert.equal(d._save_record,undefined);c.reloadPdfSaveRecovery();assert.equal(c.orderImportRecoveryRows.length,2);assert.equal(c.pdfRecoveryDetachedRows().length,2);await c.saveConfirmedImportDrafts(d);assert.equal(posts.length,0);assert.equal(s.find('one').length,2);assert.equal(storage.getItem(a.storageKey)!==null,true)});
 await test('confirmed-cache-clean-failure-B-still-saves-A-cannot-post-again',async()=>{const a=draft('A.pdf'),b=draft('B.xlsx'),c=context([a,b]),old=storage.removeItem;storage.removeItem=()=>{throw Error('denied')};try{box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:receipt(p)}};await c.saveConfirmedImportDrafts(a);assert.equal(a._save_status,'success');assert.equal(c.pdfSaveStore().find('A.pdf')[0].phase,'confirmed');await c.saveConfirmedImportDrafts(b);assert.equal(b._save_status,'success');await c.saveConfirmedImportDrafts(a);assert.equal(posts.length,2)}finally{storage.removeItem=old}});
 await test('late-401-never-triggers-current-account-login-flow',async()=>{const d=draft(),c=context([d]);let reject,calls=0;box.window.erpAuthRequired=()=>calls++;box.axios.post=async()=>await new Promise((r,j)=>{reject=j});const job=c.saveConfirmedImportDrafts(d);while(!reject)await new Promise(r=>setTimeout(r,0));c.user={id:8};c.authGeneration++;reject({response:{status:401}});await job;assert.equal(calls,0);assert.equal(store.size,1);delete box.window.erpAuthRequired});
 await test('read-or-write-storage-failure-never-sends-first-order',async()=>{storage.setItem('erp.pdf-save.v1:7:one','original-key');const old=storage.getItem;storage.getItem=()=>{throw Error('denied')};try{const d=draft(),c=context([d]);await c.saveConfirmedImportDrafts(d);assert.equal(posts.length,0);assert.equal(d._save_status,'unknown');c.reloadPdfSaveRecovery();assert.ok(c.orderImportRecoveryError);assert.equal(c.orderImportRecoveryRows.length,0)}finally{storage.getItem=old}});
 await test('partial-not-found-cannot-enable-original-continue',async()=>{const d=draft(),c=context([d]);box.axios.post=async()=>{throw Error('lost')};await c.saveConfirmedImportDrafts(d);box.axios.post=async()=>({data:{status:'not_found',current_actor_id:7,request_key:d._create_key}});await c.queryPdfSaveAttempt(d);assert.equal(d._save_status,'unknown');assert.equal(d._save_continue_allowed,false);assert.ok(d._save_payload)});
 await test('file-switch-before-post-has-safe-visible-reentry',async()=>{const d=draft(),c=context([d]);let release;c.refreshImportDraftInventoryForSave=async()=>await new Promise(r=>{release=r});const job=c.saveConfirmedImportDrafts(d);while(!release)await new Promise(r=>setTimeout(r,0));c.pdfActiveDraftKey='other-file';release();await job;assert.equal(posts.length,0);assert.equal(store.size,0);assert.equal(c.loading,false);c.pdfOpenDraft(d);assert.equal(d._save_status,'idle');assert.equal(c.isImportDraftLocked(d),false)});
 await test('wrong-file-hash-proof-keeps-original',async()=>{const d=draft(),c=context([d]);box.axios.post=async(u,p)=>{const r=receipt(p);r.save_receipt.source.hash='other-file';return{data:r}};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'unknown');assert.equal(store.size,1)});
 await test('new-account-storage-error-never-shows-old-account-record',async()=>{const d=draft(),c=context([d]);box.axios.post=async()=>{throw Error('lost')};await c.saveConfirmedImportDrafts(d);assert.equal(c.orderImportRecoveryRows.length,1);c.user={id:8};const old=storage.getItem;storage.setItem('erp.pdf-save.v1:8:one','other-key');storage.getItem=()=>{throw Error('denied')};try{c.reloadPdfSaveRecovery();assert.equal(c.orderImportRecoveryRows.length,0);assert.ok(c.orderImportRecoveryError)}finally{storage.getItem=old}});
 await test('nine-digit-price-actual-six-digits-complete-and-visible',async()=>{const d=draft(),c=context([d]);d.items[0].unit_price='1.123456789';box.axios.post=async(u,p)=>{const r=receipt(p),line=r.save_receipt.lines[0];Object.assign(line,{requested_unit_price:p.items[0].unit_price,unit_price:'1.123457',unit_price_scale:6,price_normalized:true});r.save_receipt.order.items[0].unit_price='1.123457';return{data:r}};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'success');assert.ok(d._save_message.includes('单价按系统6位精度保存'))});
 for(const [input,actual,valid] of [['1.123456789','1.123457',true],['1.0000005','1.000001',true],['1.0000004999','1.000001',false],['1.123456789','1.123458',false],['1.123456789','1.123456789',false],['0','0.000000',true],['1e-7','0.000000',true]])await test('exact-decimal-price-bound-'+input+'-'+actual,async()=>assert.equal(box.window.ERPOrderImportSaveRecovery.priceMatches(input,actual),valid));
 for(const field of ['requested','scale','flag'])await test('price-proof-invalid-'+field+'-retains-original',async()=>{const d=draft(),c=context([d]);d.items[0].unit_price='1.123456789';box.axios.post=async(u,p)=>{const r=receipt(p),line=r.save_receipt.lines[0];Object.assign(line,{requested_unit_price:p.items[0].unit_price,unit_price:'1.123457',unit_price_scale:6,price_normalized:true});r.save_receipt.order.items[0].unit_price='1.123457';if(field==='requested')line.requested_unit_price='1.123456';if(field==='scale')line.unit_price_scale=9;if(field==='flag')line.price_normalized=false;return{data:r}};await c.saveConfirmedImportDrafts(d);assert.equal(d._save_status,'unknown');assert.ok(d._save_payload)});
 await test('detached-recovery-confirmed-keeps-number-and-link-after-cleanup-refresh-failure',async()=>{const first=draft(),c=context([first]);box.axios.post=async()=>{throw Error('lost')};await c.saveConfirmedImportDrafts(first);const fresh=context([]);fresh.openOrderPdfImport();const r=fresh.orderImportRecoveryRows[0],body=JSON.parse(r.bodyJson),proof=receipt(body);fresh.loadOrders=async()=>{throw Error('refresh failed')};box.axios.post=async(u,p)=>{posts.push({url:u,body:p});return{data:{status:'completed',current_actor_id:7,request_key:r.key,proof_status:'complete',save_receipt:proof.save_receipt,order:{id:1,order_number:'SO-TEST-001',customer_id:1}}}};await fresh.runPdfRecovery(r,'resolve');assert.equal(store.size,0);assert.equal(fresh.pdfRecoveryDetachedRows().length,1);assert.equal(r.cacheCleared,true);assert.equal(r.phase,'confirmed');assert.equal(r.traceOrderId,1);assert.equal(r.traceOrderNumber,'SO-TEST-001');assert.ok(r.message.includes('列表未刷新'));assert.equal(posts.length,1);assert.ok(posts[0].url.endsWith('/resolve'));fresh.user={id:8};fresh.reloadPdfSaveRecovery();assert.equal(fresh.orderImportRecoveryRows.length,0)});
 await test('actual-old-log-shape-empty-mapping-allows-trace-only-keeps-v1',async()=>{const d=draft(),c=context([d]);storage.setItem('erp.pdf-save.v1:7:one','old-log');c.restorePdfSaveAttempt(d);const body={idempotency_key:'old-log',customer_id:1,items:[{client_line_id:'old-line',product_id:1,quantity:10,unit_price:1}]},p=receipt(body).save_receipt;Object.assign(p,{proof_status:'legacy',request_match:false,request:null,lines:[],line_count:1});box.axios.post=async(u,b)=>{posts.push({url:u,body:b});return{data:{status:'completed',current_actor_id:7,request_key:'old-log',proof_status:'legacy',save_receipt:p,order:{id:1,order_number:'SO-TEST-001',customer_id:1}}}};await c.queryPdfSaveAttempt(d);assert.equal(d._saved_order_id,1);assert.equal(d._save_status,'unknown');assert.equal(store.size,1);assert.equal(d._save_payload,null);assert.equal(posts.length,1);assert.ok(posts[0].url.endsWith('/resolve'));assert.equal(d._save_record.canContinue,false)});
 for(const proofStatus of ['legacy','restricted'])await test('v2-'+proofStatus+'-trace-link-keeps-full-original-unknown-without-write',async()=>{const d=draft(),c=context([d]);d.items[0].unit_price='1.123456789';box.axios.post=async()=>{throw Error('lost')};await c.saveConfirmedImportDrafts(d);const original=d._save_payload,p=receipt(JSON.parse(original)).save_receipt;Object.assign(p,{proof_status:proofStatus,request_match:false,request:null,lines:[],line_count:1});box.axios.post=async(u,b)=>{posts.push({url:u,body:b});return{data:{status:'completed',current_actor_id:7,request_key:d._create_key,proof_status:proofStatus,save_receipt:p,order:{id:1,order_number:'SO-TEST-001',customer_id:1}}}};await c.queryPdfSaveAttempt(d);assert.equal(d._saved_order_id,1);assert.equal(d._save_status,'unknown');assert.equal(d._save_payload,original);assert.equal(d._save_record.traceOrderId,1);assert.equal(d._save_record.phase,'unknown');assert.equal(d._save_record.canContinue,false);assert.ok(d._save_message.includes('原保存证明不足'));assert.equal(store.size,1);assert.equal(posts.length,1);assert.ok(posts[0].url.endsWith('/resolve'));assert.equal(JSON.parse([...store.values()][0]).bodyJson,original)});
 const contracts=process.env.ORDER_IMPORT_API_CONTRACT_DIR;
 if(contracts){
  for(const name of ['normal','source-alias-after-edit','no-price','new-null',...(fs.existsSync(path.join(contracts,'precision.json'))?['precision']:[])])for(const mode of ['write','resolve'])await test('real-http-contract-'+name+'-'+mode,async()=>{
   const evidence=JSON.parse(fs.readFileSync(path.join(contracts,name+'.json'),'utf8')),body=evidence.originalBody,d=draft(),c=context([d]);c.user={id:evidence.actorId};d.file_hash=evidence.fileHash||'non-import-contract';
   const r=c.pdfSaveStore().prepare(d.file_hash,JSON.stringify(body),{fileName:'aaaa.pdf'});Object.assign(d,{_save_status:'unknown',_save_record:r,_save_payload:r.bodyJson,_create_key:r.key,_save_actor_id:r.actorId});r.canContinue=true;
   box.axios.post=async(u,p)=>{posts.push({url:u,body:p});if(mode==='write')assert.equal(JSON.stringify(p),r.bodyJson);else assert.equal(JSON.stringify(p.original_request),r.bodyJson);return{data:evidence.responses[mode].body}};
   await c.runPdfRecovery(r,mode==='write'?'continue':'resolve',d);assert.equal(d._save_status,'success');assert.equal(d._saved_order_id,evidence.responses[mode].body.save_receipt.order.id);assert.equal(store.size,0);assert.equal(posts.length,1);
  });
  for(const name of ['legacy-v1','source-located'])await test('real-http-contract-'+name+'-trace-only-retains-v1',async()=>{
   const evidence=JSON.parse(fs.readFileSync(path.join(contracts,name+'.json'),'utf8')),d=draft(),c=context([d]);c.user={id:evidence.actorId};d.file_hash=evidence.fileHash||'non-import-contract';d.preview_safety_token=evidence.originalBody.pdf_import_confirmation.preview_safety_token;d.source_name='aaaa.pdf';storage.setItem(`erp.pdf-save.v1:${evidence.actorId}:${evidence.fileHash}`,evidence.originalBody.idempotency_key);c.restorePdfSaveAttempt(d);
   box.axios.post=async(u,p)=>{posts.push({url:u,body:p});assert.equal(p.original_request,undefined);return{data:evidence.responses.resolve.body}};await c.queryPdfSaveAttempt(d);assert.equal(d._save_status,'unknown');assert.equal(d._saved_order_id,evidence.responses.resolve.body.order.id);assert.equal(store.size,1);assert.equal(d._save_payload,null);assert.equal(posts.length,1);assert.ok(posts[0].url.endsWith('/resolve'));if(name==='source-located')assert.ok(d._save_message.includes('尚未证明原请求键已执行'));
  });
 }
 const reviews=process.env.ORDER_IMPORT_API_REVIEW_DIR;
 if(reviews)for(const name of ['actual-old-log','actual-v2-alias-legacy'])await test('real-http-review-'+name+'-actual-ui-trace-only',async()=>{const e=JSON.parse(fs.readFileSync(path.join(reviews,name+'.json'),'utf8')),d=draft(),c=context([d]);c.user={id:e.actorId};d.file_hash=e.fileHash;if(e.originalBody)c.pdfSaveStore().prepare(e.fileHash,JSON.stringify(e.originalBody),{fileName:'real-http-review.xlsx'});else storage.setItem(`erp.pdf-save.v1:${e.actorId}:${e.fileHash}`,e.key);c.restorePdfSaveAttempt(d);const original=d._save_payload;box.axios.post=async(u,b)=>{posts.push({url:u,body:b});if(e.originalBody)assert.equal(JSON.stringify(b.original_request),original);else assert.equal(b.original_request,undefined);return{data:e.body}};await c.queryPdfSaveAttempt(d);assert.equal(d._saved_order_id,e.body.order.id);assert.equal(d._save_record.traceOrderNumber,e.body.order.order_number);assert.equal(d._save_status,'unknown');assert.equal(d._save_payload,original);assert.equal(store.size,1);assert.equal(d._save_record.canContinue,false);assert.equal(posts.length,1);assert.ok(posts[0].url.endsWith('/resolve'))});
 const output=process.env.ORDER_IMPORT_UI_EVIDENCE;if(output){fs.mkdirSync(output,{recursive:true});const fingerprints=['static/index.html','static/ui/pdf-workspace.js','static/ui/order-import-save-recovery.js'].map(file=>({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(repo,file))).digest('hex')}));fs.writeFileSync(path.join(output,'node-results.json'),JSON.stringify({source:'actual index.html Vue methods + actual pdf-workspace mixin',fingerprints,results},null,2));const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]));fs.writeFileSync(path.join(output,'node-results.xml'),`<testsuite name="order_import_save_recovery" tests="${results.length}" failures="${results.filter(r=>!r.passed).length}">${results.map(r=>`<testcase name="${esc(r.name)}">${r.passed?'':`<failure message="${esc(r.error)}"/>`}</testcase>`).join('')}</testsuite>`);}
 console.log(JSON.stringify({total:results.length,passed:results.filter(r=>r.passed).length,failures:results.filter(r=>!r.passed)},null,2));if(results.some(r=>!r.passed))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=2});
