// Run real Vue methods in a network-free VM. No ERP database or server.
const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict');
const html=fs.readFileSync('static/index.html','utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.trim());
const sandbox={axios:{defaults:{},interceptors:{response:{use(){}}}},Vue:{createApp(d){sandbox.definition=d;return{component(){return this},mount(){return this}}}},localStorage:{getItem(){return ''},setItem(){},removeItem(){}},window:{},console,URLSearchParams,setTimeout,clearTimeout,TMOrderReference:{component:{}}};
vm.createContext(sandbox);vm.runInContext(script,sandbox);
const ctx={...sandbox.definition.methods,canViewSalesAmounts:true};
const line={matched_product_id:1,quantity:60,_inventory:ctx.newOrderInventoryState()};
line._inventory.authoritative={finished_stock_on_hand_quantity:100,finished_stock_reserved_quantity:20,finished_stock_available_quantity:80,finished_stock_line_allocated_quantity:60,finished_stock_allocated_quantity:60,finished_stock_remaining_quantity:20,finished_stock_batch_remaining_quantity:20,finished_stock_unit:'只'};
assert.equal(ctx.pdfInventoryBalanceText(line),'20 只');
assert.match(ctx.pdfInventoryBalanceHint(line),/实存 100 只/);
assert.match(ctx.pdfInventoryBalanceHint(line),/已预占 20 只/);
line._inventory.finished.skipped=true;
assert.equal(ctx.pdfInventoryBalanceText(line),'20 只');
assert.match(ctx.pdfInventoryBalanceHint(line),/本行未抵扣/);
line._inventory.finished._batch_auto_skipped=true;
line._inventory.authoritative.finished_stock_batch_remaining_quantity=0;
assert.equal(ctx.pdfInventoryBalanceText(line),'0 只');
assert.equal(ctx.pdfFinishedInventoryExplicitlySkipped(line),false);
line._inventory.finished._batch_auto_skipped=false;
for(const [key,value,text] of [['loading',true,'计算中'],['stale',true,'待刷新'],['api_error',true,'查询失败'],['authoritative_loading',true,'计算中'],['authoritative_error','failed','查询失败']]){
 line._inventory[key]=value;assert.equal(ctx.pdfInventoryBalanceText(line),text);line._inventory[key]=typeof value==='boolean'?false:'';
}
line._inventory.authoritative.finished_stock_batch_remaining_quantity=null;
assert.equal(ctx.pdfInventoryBalanceText(line),'待核对');
line._inventory.authoritative.finished_stock_batch_remaining_quantity=0;
assert.equal(ctx.pdfInventoryBalanceText(line),'0 只');
line._inventory.authoritative.finished_stock_reference={status:'red',min_quantity:30,max_quantity:50,sample_count:3,quantity_unit:'只',samples:[{delivery_number:'D1',delivery_date:'2026-10-01',quantity:30}]};
assert.equal(ctx.pdfInventoryReserveLevel(line),'red');
assert.equal(ctx.pdfInventoryReferenceText(line),'近期单次 30～50 只');
assert.match(ctx.pdfInventoryBalanceHint(line),/D1：30 只/);
for(const [quantity,status] of [[29,'red'],[30,'yellow'],[49,'yellow'],[50,'green']]){
 line._inventory.authoritative.finished_stock_batch_remaining_quantity=quantity;
 line._inventory.authoritative.finished_stock_reference.status=status;
 assert.equal(ctx.pdfInventoryReserveLevel(line),status);
}
line._inventory.authoritative.finished_stock_reference.quantity_unit='箱';assert.equal(ctx.pdfInventoryReserveLevel(line),'unknown');
line._inventory.authoritative.finished_stock_reference.quantity_unit='只';
line._inventory.stale=true;assert.equal(ctx.pdfInventoryReserveLevel(line),'unknown');line._inventory.stale=false;
line._inventory.authoritative.finished_stock_reference={status:'unknown',reason:'暂无参考'};assert.equal(ctx.pdfInventoryReferenceText(line),'暂无参考');
line.matched_product_id=null;assert.equal(ctx.pdfInventoryBalanceText(line),'待匹配');assert.equal(ctx.pdfInventoryReserveLevel(line),'unknown');
assert.equal(ctx.pdfDraftColumnCount({}),10);ctx.canViewSalesAmounts=false;assert.equal(ctx.pdfDraftColumnCount({}),8);
let reallocations=0;
const draft={items:[line]};
ctx.isImportDraftLocked=()=>false;ctx.invalidateImportDraftConfirmation=()=>{};ctx.syncOrderImportReminderVisibility=()=>{};ctx.reallocateAllDraftInventory=()=>{reallocations++};
ctx.removeImportDraftItem(draft,line);assert.equal(draft.items.length,0);assert.equal(reallocations,1);
assert(html.indexOf('class="pdf-balance-col"')>html.indexOf('<th class="pdf-requisition-col"'));
assert(html.indexOf('class="pdf-balance-col"')<html.indexOf('<th class="pdf-issue-col"'));
console.log('PASS: balance, skipped/zero/missing/error states, units, colspan, delete refresh, column order');
(async()=>{
 const make=(qty)=>({matched_product_id:1,client_line_id:'same-id',quantity:qty,_inventory:ctx.newOrderInventoryState()});
 const first={matched_customer_id:1,items:[make(20)]},second={matched_customer_id:1,items:[make(10)]},other={matched_customer_id:2,items:[make(99)]};
 const context={...sandbox.definition.methods,orderImportDrafts:[first,other,second],orderImportBatch:{},pdfImportItemMaterialCode:()=>'',buildReservationPlan:()=>({finished:[],semi:[]}),errorMessage:e=>e.message};
 let sent;
 sandbox.axios.post=async(url,payload)=>{sent=payload;return {data:{items:payload.items.map((i,n)=>({...i,finished_stock_remaining_quantity:80-n*10,finished_stock_unit:'只'}))}}};
 await context.loadPdfDraftInventoryAuthority(second);
 assert.equal(sent.items.length,2);assert.equal(new Set(sent.items.map(i=>i.client_line_id)).size,2);
 assert.equal(second.items[0]._inventory.authoritative.finished_stock_remaining_quantity,70);
 assert.equal(first.items[0]._inventory.authoritative,null);
 await context.loadPdfDraftInventoryAuthority(first);
 assert.equal(sent.items.length,2,'the first document also includes later same-customer demand');
 assert.equal(first.items[0]._inventory.authoritative.finished_stock_remaining_quantity,80);
 let resolve;
 sandbox.axios.post=()=>new Promise(r=>resolve=r);
 const old=context.loadPdfDraftInventoryAuthority(second);
 context.schedulePdfDraftInventoryAuthority(second);clearTimeout(second._inventory_authority_timer);
 resolve({data:{items:[{client_line_id:'preview-1',finished_stock_remaining_quantity:999}]}});await old;
 assert.equal(second.items[0]._inventory.authoritative.finished_stock_remaining_quantity,70,'old response ignored after scheduling');
 assert.equal(second.items[0]._inventory.authoritative_loading,true);
 first.items=Array.from({length:200},()=>make(1));
 sandbox.axios.post=async(url,payload)=>{sent=payload;return {data:{items:payload.items.map(i=>({...i}))}}};
 await context.loadPdfDraftInventoryAuthority(second);
 assert.equal(sent.items.length,1);assert.equal(context.pdfInventoryBalanceText(second.items[0]),'分批查看');
 assert.match(context.pdfInventoryBalanceHint(second.items[0]),/200行/);
 assert.equal(context.pdfInventoryRequisitionText(second.items[0]),'分批核对');
 first.items[0]._inventory.api_error=true;
 context.schedulePdfDraftInventoryAuthority(second);clearTimeout(second._inventory_authority_timer);
 await context.loadPdfDraftInventoryAuthority(second);
 assert.equal(second.items[0]._inventory.authoritative_loading,false);
 assert.equal(second.items[0]._inventory.authoritative,null);
 assert.match(second.items[0]._inventory.authoritative_error,/库存未就绪/);
 context.orderImportDrafts=[second];second.items=Array.from({length:201},()=>make(1));
 let called=false;sandbox.axios.post=async()=>{called=true;throw Error('must not send oversized request')};
 await context.loadPdfDraftInventoryAuthority(second);assert.equal(called,false);
 assert.match(second.items[0]._inventory.authoritative_error,/200行/);
 second.matched_customer_id=null;
 context.schedulePdfDraftInventoryAuthority(second);clearTimeout(second._inventory_authority_timer);
 await context.loadPdfDraftInventoryAuthority(second);assert.equal(second.items[0]._inventory.authoritative_loading,false);
 assert.match(second.items[0]._inventory.authoritative_error,/客户/);
 console.log('PASS: cross-draft stock scope, customer separation, duplicate wire IDs, stale response, 200-row safe fallback');
})().catch(e=>{console.error(e);process.exitCode=1});
