const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('static/index.html','utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.trim());
const box={console, setTimeout,clearTimeout,AbortController,URLSearchParams,localStorage:{getItem(){return ''},setItem(){},removeItem(){}},window:{},TMOrderReference:{component:{}},axios:{defaults:{},interceptors:{response:{use(){}}},get:async()=>({data:{items:[]}}),post:async()=>({data:{items:[]}})}};
vm.createContext(box);vm.runInContext(fs.readFileSync('static/vendor/vue-3.5.40.global.prod.js','utf8'),box);
const reactive=box.Vue.reactive;
box.Vue.createApp=d=>{box.definition=d;return{component(){return this},mount(){return this}}};vm.runInContext(script,box);
const ctx={...box.definition.methods,orderForm:{customer_id:1,items:[]},money:v=>v||0,materialName:()=>'',spec:()=>'',orderSpecificationText:v=>v,recalculateOrderCost:async()=>{},refreshOrderLineInventory:async()=>{},refreshOrderNumberPreview:async()=>{}};
const parent={id:1,product_name:'纸箱',sale_unit_price:5};
box.axios.get=async url=>({data:url.endsWith('/bom')?{inventory_mode:'manufactured',components:[{component_product_id:2,quantity_per_set:1,inventory_relation:'accompany'},{component_product_id:3,quantity_per_set:2,inventory_relation:'accompany'}]}:{id:Number(url.split('/').at(-1)),product_name:'实物',sale_unit_price:2}});
(async()=>{
 ctx.orderForm.items=[{product_id:1,quantity:10}];
 await ctx.expandComponentPricedOrderLine(0,parent,ctx.orderForm.items[0]);
 assert.deepEqual(Array.from(ctx.orderForm.items,r=>r.product_id),[1,2,3]);
 assert.deepEqual(Array.from(ctx.orderForm.items,r=>r.quantity),[10,10,20]);
 assert.equal(new Set(ctx.orderForm.items.map(r=>r.combination_group_key)).size,1);
 const imported={product_id:2,quantity:10,unit_price:9,production_notes:'原录入内容'};
 ctx.orderForm.items=[imported,{product_id:1,quantity:10}];
 await ctx.expandComponentPricedOrderLine(1,parent,ctx.orderForm.items[1]);
 assert.equal(ctx.orderForm.items.length,3);
 assert.equal(ctx.orderForm.items.find(r=>r.product_id===2).unit_price,9);
 assert.equal(ctx.orderForm.items.find(r=>r.product_id===2).production_notes,'原录入内容');
 ctx.orderForm.items=[{product_id:1,quantity:10},{...imported,quantity:11}];
 const before=JSON.stringify(ctx.orderForm.items);
 await assert.rejects(ctx.expandComponentPricedOrderLine(0,parent,ctx.orderForm.items[0]),/数量不一致/);
 assert.equal(JSON.stringify(ctx.orderForm.items),before);
 ctx.orderForm.items=[{product_id:1,quantity:10}];
 const original=JSON.stringify(ctx.orderForm.items);
 ctx.recalculateOrderCost=async()=>{throw Error('cost failed')};
 await assert.rejects(ctx.expandComponentPricedOrderLine(0,parent,ctx.orderForm.items[0]),/cost failed/);
 assert.equal(JSON.stringify(ctx.orderForm.items),original);
 console.log('PASS R03 physical parent + two children; shared group; imported-child dedup retains input; mismatch/error keeps draft');
})().catch(e=>{console.error(e);process.exit(1)});
