const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync('static/index.html','utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.trim());
const sandbox={axios:{defaults:{},interceptors:{response:{use(){}}}},Vue:{createApp(d){sandbox.definition=d;return{component(){return this},mount(){return this}}}},TMOrderReference:{component:{}},localStorage:{getItem(){return ''},setItem(){},removeItem(){}},window:{},console,URLSearchParams,setTimeout,clearTimeout};
vm.createContext(sandbox);vm.runInContext(script,sandbox);
const ctx={...sandbox.definition.methods,inventoryComponents:()=>['whole'],inventoryPlanApplies:()=>true,reallocateAllDraftInventory(){},invalidatePdfDraftForItem(){}};
const a={lot_id:861,version:2,source:'customer_generic',available_stock_quantity:121,warehouse_location:{id:1251,employee_location_name:'三楼 北K-04'},board_length_mm:1345,board_width_mm:1300,flute_type:'B',material_code:'R7A',sheet_type:'semi_finished',signature_differences:['customer']};
const b={...a,lot_id:862,available_stock_quantity:300,warehouse_location:{id:1256,employee_location_name:'三楼 北K-03'}};
const line={product_id:206,quantity:500,_inventory:ctx.newOrderInventoryState()};
const part=line._inventory.semi.whole;part.candidates=[a,b];part.manual_candidates=[a];
assert.equal(ctx.orderLineSemiAvailable(line),421);
assert.match(ctx.orderLineInventoryAutoSummary(line),/半成品可用421张/);
assert.equal(ctx.orderLineInventoryButtonClass(line),'inventory-semi-yellow');
assert.equal(ctx.semiStockGroups(line,'whole').length,2);
ctx.chooseSemiStockGroup(line,'whole',ctx.semiStockGroups(line,'whole')[0],true);
assert.equal(part.selected_candidates.length,1);assert.equal(part.manual_override,true);
ctx.chooseSemiStockGroup(line,'whole',ctx.semiStockGroups(line,'whole')[1],true);
assert.equal(part.selected_candidates.length,2);
part.allocations=part.selected_candidates.map(candidate=>({candidate,requested_qty:10,stock_quantity:10}));
assert(ctx.buildReservationPlan(line).semi.every(p=>p.override&&p.warning_acknowledged_codes.includes('SEMI_SIGNATURE_OVERRIDE')));
ctx.chooseSemiStockGroup(line,'whole',ctx.semiStockGroups(line,'whole')[0],false);
assert.equal(part.selected_candidates.length,1);assert.equal(part.selected_candidates[0].lot_id,862);
ctx.chooseSemiStockGroup(line,'whole',ctx.semiStockGroups(line,'whole')[1],false);
assert.equal(part.skipped,true);assert.equal(ctx.buildReservationPlan(line).semi.length,0);
ctx.chooseSemiStockGroup(line,'whole',ctx.semiStockGroups(line,'whole')[0],true);assert.equal(part.skipped,false);
const c={...a,lot_id:863,available_stock_quantity:8,material_code:'K8K'};part.candidates=[a,c];part.manual_candidates=[];
assert.equal(ctx.semiStockGroups(line,'whole').length,1);assert.equal(ctx.semiStockGroups(line,'whole')[0].quantity,129);
assert.equal(ctx.semiStockGroups(line,'whole')[0].candidates.length,2);
line._inventory.api_error=true;assert.equal(ctx.orderLineInventoryButtonClass(line),'danger');
line._inventory.api_error=false;
const auto={...a,automatic_recommendation:true,direct_deduction_eligible:true};part.candidates=[auto];part.selected_candidates=[];part.selected=null;part.skipped=false;
ctx.chooseSemiStockGroup(line,'whole',ctx.semiStockGroups(line,'whole')[0],true);
part.allocations=[{candidate:auto,requested_qty:10,stock_quantity:10}];
assert.equal(ctx.buildReservationPlan(line).semi[0].direct_deduction,true);assert.equal(ctx.buildReservationPlan(line).semi[0].override,false);
assert(!html.includes('处理库存例外'));
const section=html.split('<!-- compact semi stock -->')[1].split('<!-- /compact semi stock -->')[0];
assert(!section.includes('lot_number'));assert(!section.includes('signature_differences'));assert(section.includes('btn small success'));assert(section.includes('btn small danger'));
console.log('semi stock UI: quantity, grouping, adopt/reject, batch payload, safety and rendering passed');
