const fs=require('fs'),vm=require('vm'),assert=require('assert');
const html=fs.readFileSync(process.argv[2]||'static/index.html','utf8');
const script=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(m=>m[1]).find(s=>s.trim());
const sandbox={axios:{defaults:{},interceptors:{response:{use(){}}}},Vue:{createApp(d){sandbox.definition=d;return{component(){return this},mount(){return this}}}},TMOrderReference:{component:{}},localStorage:{getItem(){return ''},setItem(){},removeItem(){}},window:{},console,URLSearchParams,setTimeout,clearTimeout};
vm.createContext(sandbox);vm.runInContext(script,sandbox);
const ctx={...sandbox.definition.methods,inventoryComponents:()=>['whole','base'],inventoryPlanApplies:()=>true,inventoryStateMatchesLine:()=>true,reallocateAllDraftInventory(){},invalidatePdfDraftForItem(){},isImportDraftLocked:d=>!!d.saved};
const general={lot_id:1,customer_id:null,customer_bound:false,source:'customer_generic',automatic_recommendation:true,direct_deduction_eligible:true,available_stock_quantity:100,signature_differences:[],warning_codes:[]};
assert.equal(ctx.isSafeSystemInventoryCandidate('whole',general),false,'general stock must never auto-adopt');
assert.equal(ctx.isSafeSystemInventoryCandidate('whole',{...general,customer_bound:true}),true);
const line={product_id:1,quantity:10,_inventory:ctx.newOrderInventoryState()};
for(const part of Object.values(line._inventory.semi))part.candidates=[general];
assert.equal(ctx.inventoryDecisionRequired(line),'','unadopted general stock must not block save');
const finished={lot_id:9,version:1,quantity_available:20};line._inventory.finished.selected_candidates=[finished];line._inventory.finished.allocations=[{candidate:finished,requested_qty:2}];
const second={product_id:2,quantity:10,_inventory:ctx.newOrderInventoryState()};
ctx.skipImportedSheets({items:[line,second]});
assert(Object.values(line._inventory.semi).every(p=>p.skipped&&!p.selected_candidates.length));
assert(second._semi_all_declined);assert.equal(ctx.buildReservationPlan(line).finished[0].requested_qty,2);
ctx.chooseSemiStockGroup(line,'whole',{candidates:[general]},true);
assert(!line._semi_all_declined);assert(!line._inventory.semi.whole.skipped);assert(line._inventory.semi.base.skipped);
line._inventory.semi.whole.allocations=[{candidate:general,requested_qty:3,stock_quantity:3}];
assert.equal(ctx.buildReservationPlan(line).semi.length,1);
const snapshot=ctx.importDraftInventoryDecisionSnapshot(line);
line._inventory=ctx.newOrderInventoryState();line._inventory.semi.whole.candidates=[general];
(async()=>{
 await ctx.restoreImportDraftInventoryDecision(line,snapshot,1);
 assert.equal(line._inventory.semi.whole.selected_candidates[0].lot_id,1);assert(line._inventory.semi.base.skipped);
 ctx.skipAllLineSheets(line);assert.equal(ctx.buildReservationPlan(line).semi.length,0);
 const locked={saved:true,items:[{_semi_all_declined:false}]};ctx.skipImportedSheets(locked);assert(!locked.items[0]._semi_all_declined);
 ctx.inventoryCandidatePayload=()=>({});ctx.inventoryPayloadUnavailableReason=()=>'';ctx.errorMessage=e=>String(e);
 sandbox.axios.get=async()=>({data:{items:[]}});sandbox.axios.post=async()=>({data:{items:[general]}});
 line._inventory.context={product_id:1,customer_id:1,quantity:10};
 await ctx.loadOrderLineInventory(line,1);
 assert(Object.values(line._inventory.semi).every(p=>p.skipped));
 ctx.chooseSemiStockGroup(line,'whole',{candidates:[general]},true);
 await ctx.loadOrderLineInventory(line,1);
 assert.equal(line._inventory.semi.whole.selected_candidates.length,1);assert(line._inventory.semi.base.skipped);
 let resolveProduct;sandbox.axios.get=()=>new Promise(resolve=>{resolveProduct=resolve});
 const pending=ctx.loadOrderLineInventory(line,1);ctx.skipAllLineSheets(line);
 sandbox.axios.get=async()=>({data:{items:[]}});resolveProduct({data:{}});await pending;
 assert(Object.values(line._inventory.semi).every(p=>p.skipped&&!p.selected_candidates.length));
 for(const cell of html.matchAll(/<td class="semi-stock-actions">([\s\S]*?)<\/td>/g))assert(!cell[1].includes('match_reason'));
 assert(html.includes('min-width:150px;white-space:nowrap!important'));
 assert(html.includes('本次导入片料全部不采用'));assert(html.includes('本行全部不采用片料'));
 console.log('general opt-in, batch decline, re-adopt, refresh, finished preservation and action layout passed');
})().catch(e=>{console.error(e);process.exit(1)});
