const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const page=fs.readFileSync('static/index.html','utf8');
for(const match of page.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/gi)) if(match[1].trim()) new vm.Script(match[1]);
const calls=[];
const ctx=vm.createContext({console,Symbol,setTimeout,axios:{get:(url)=>new Promise((resolve,reject)=>calls.push({url,resolve,reject}))}});
vm.runInContext(fs.readFileSync('static/vendor/vue-3.5.40.global.prod.js','utf8'),ctx);
const htmlStart=page.indexOf('<div v-else-if="(modal.type === \'supplierOrderPrint\''),htmlEnd=page.indexOf('<div v-else-if="modal.type === \'requisitionMaterial\'"',htmlStart);
ctx.template=page.slice(htmlStart,htmlEnd).replace('v-else-if=','v-if=');
vm.runInContext('Vue.compile(template,{decodeEntities:text=>text,onError(error){throw error}})',ctx);
const start=page.indexOf('openSupplierOrderBatch(orders) {'),end=page.indexOf('printSupplierOrderArea() {',start);
vm.runInContext(`var methods=({${page.slice(start,end)}});var app=Vue.reactive({modal:null,supplierPreview:{},...methods});`,ctx);
const app=ctx.app;
(async()=>{
 app.openSupplierOrderBatch([{supplier_order_id:1,supplier_name:'甲',supplier_order_number:'SRO-A'},{supplier_order_id:2,supplier_name:'乙',supplier_order_number:'SRO-B'}]);
 assert.equal(app.supplierPreview.orders.length,2);assert.equal(app.supplierPreview.showInternal,false);
 const second=app.selectSupplierPreview(1);
 calls[1].resolve({data:{id:2,lines:[{requisition_qty:20}]}});await second;
 calls[0].resolve({data:{id:1,lines:[{requisition_qty:10}]}});await new Promise(r=>setImmediate(r));
 assert.equal(app.modal.data.id,2,'late first response overwrote selected supplier');assert.equal(app.supplierPreview.loading,false);
 const failed=app.selectSupplierPreview(0);calls[2].reject(new Error('network'));await failed;
 assert(app.supplierPreview.error.includes('不要重复报料'));assert.equal(app.supplierPreview.orders.length,2);
 const retry=app.selectSupplierPreview(0);calls[3].resolve({data:{id:1,lines:[]}});await retry;
 assert.equal(app.supplierPreview.error,'');assert.equal(app.modal.data.id,1);
 app.toggleSupplierInternal();assert.equal(app.supplierPreview.showInternal,true);assert(calls[4].url.endsWith('/1/internal-trace'));
 const switched=app.selectSupplierPreview(1);calls[5].resolve({data:{id:2,lines:[]}});await switched;
 calls[4].resolve({data:{sources:['stale']}});await new Promise(r=>setImmediate(r));assert.equal(app.supplierPreview.trace,null);
 calls[6].resolve({data:{sources:['current']}});await new Promise(r=>setImmediate(r));assert.equal(app.supplierPreview.trace.sources[0],'current');
 console.log('Two-supplier navigation, reactive request identity, late response, retry, independent internal trace and inline syntax passed');
})().catch(error=>{console.error(error);process.exitCode=1});
