from pathlib import Path


INDEX = Path("static/index.html").read_text(encoding="utf-8")


def _body(start: str, end: str) -> str:
    begin = INDEX.index(start)
    return INDEX[begin : INDEX.index(end, begin)]


def test_supplier_settlement_is_embedded_in_existing_payables_workspace() -> None:
    payables = _body(
        '<template v-else-if="financeView===\'payables\'">',
        '<template v-else-if="financeView===\'invoice_tasks\'">',
    )
    assert "供应商 20 日月结" in payables
    assert "上月 21 日至本月 20 日" in payables
    assert "生成 / 刷新草稿" in payables
    assert "核对账单" in payables
    assert "确认应付" in payables
    assert "登记发票" in payables
    assert "上传 PDF 原件" in payables
    assert "登记付款" in payables
    assert 'ref="supplierInvoicePdfInput"' in payables
    assert "供应商应付登记（原应付流程）" in payables


def test_supplier_settlement_mutations_reuse_keys_until_success() -> None:
    load = _body(
        "async loadSupplierSettlements(autoGenerate = true) {",
        "async generateSupplierSettlements(silent = false) {",
    )
    assert 'axios.get("/api/finance/supplier-settlements"' in load
    assert "signal:controller.signal" in load
    assert "latestRequestControllers.get(requestKey)" in load
    assert "data.default_month === this.supplierSettlementMonth" in load
    assert "autoGeneratedMonth" in load
    assert "generateSupplierSettlements(true)" in load

    mutation = _body(
        "async mutateSupplierSettlement(row,action,url,payload,successMessage) {",
        "reviewSupplierSettlement(row) {",
    )
    assert "supplierSettlementAttempt(action,row,payload)" in mutation
    assert "idempotency_key:attempt.key" in mutation
    assert "delete attempts[attempt.slot]" in mutation


def test_supplier_statement_keeps_decimal_payloads_and_one_confirm_gate() -> None:
    assert 'supplier_statement_amount:String(row._reviewAmount||"")' in INDEX
    assert 'amount:String(row._adjustAmount||"")' in INDEX
    assert 'allocated_amount:String(row._invoiceAllocated||"")' in INDEX
    assert 'amount:String(row._paymentAmount||"")' in INDEX
    confirm_body = _body(
        "confirmSupplierSettlement(row) {",
        "reopenSupplierSettlement(row) {",
    )
    assert confirm_body.count("confirm(") == 1
    assert "确认后将冻结实收来源" in confirm_body
