import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawnSync} from 'node:child_process';

test('isolated layout keeps search, map, two-card elevation and inspector readable without overlays',()=>{
  const css=['styles.css','warehouseTwin.css','warehouseWorkspace.css'].map(file=>readFileSync(new URL('../src/'+file,import.meta.url),'utf8')).join('\n');
  const dir=mkdtempSync(join(tmpdir(),'tm-workspace-layout-')),fixture=join(dir,'fixture.html');
  const cards=[1,2].map(n=>`<article class="shelf-product-card"><div class="shelf-product-summary"><span class="shelf-product-customer">驿力</span><span class="shelf-product-name">风机纸箱加长产品名称${n}</span><span class="shelf-specification">630×480×520mm</span><span class="shelf-product-batches">1 批</span></div><div class="shelf-product-code-row"><button class="shelf-product-label-button"><strong class="shelf-inventory-code">Z.001.00013${n}-LONG</strong></button><strong class="shelf-product-quantity">120只</strong></div></article>`).join('');
  writeFileSync(fixture,`<!doctype html><meta charset="utf-8"><style>${css}</style><body class="warehouse-twin-page"><main id="warehouse-twin-root" class="warehouse-twin-shell embedded-shell">
  <section class="twin-toolbar"><div class="twin-floor-area-row"><label>楼层<select><option>3F</option></select></label><label>区域<select><option>南A1</option></select></label></div><div class="twin-top-search"><input placeholder="全仓查货"><button>查找</button></div><div class="twin-operation-modes"><button>移货</button><button>盘点</button><details class="twin-workspace-more" open><summary>更多</summary><div><button>区域规划</button><button>合并同款栈板</button><button>特殊地堆 / 大件存放</button><button>操作帮助</button><button>图层</button><button>等距视图</button><button class="last-more-action">全图复位</button></div></details></div></section>
  <section class="twin-workspace rack-focused context-open"><aside class="twin-context-rail"><header><h2>全仓搜索结果</h2><button>收起结果</button></header><div class="twin-global-search"><div class="twin-search-result-list"><button>驿力 · Z.001.000131 · 三楼A区</button></div></div></aside><div class="twin-stage rack-focused"><div class="twin-map-pane">地图</div><section class="twin-rack-focus-panel twin-rack-stage"><header>货架正视图</header><div class="twin-rack-content"><div class="twin-elevation-shell"><div class="twin-height-ruler"><b>2400 mm</b></div><div class="twin-elevation-frame"><div class="twin-elevation-level"><span>第 1 层 · 1 格</span><div><div class="mold-rack-cell"><div class="shelf-cell-heading"><b>1格</b><small>混放 · 3款</small></div><div class="shelf-product-cards">${cards}<button class="shelf-view-all-products">查看全部 3 款</button></div></div></div></div></div><div class="twin-width-ruler"><b>2600 mm</b></div></div></div></section></div><aside class="twin-inspector"><section class="twin-move-control-panel">移动货物</section><section class="twin-location-card"><warehouse-costs>费用折叠</warehouse-costs><div class="twin-location-card-title">当前货位</div><div class="twin-location-item">货物标签</div></section></aside></section></main><pre id="result"></pre>
  <script>
  const checks=[];const rect=s=>document.querySelector(s).getBoundingClientRect();
  const width=window.innerWidth;const map=rect('.twin-map-pane'),rack=rect('.twin-rack-focus-panel'),label=rect('.twin-inspector'),search=rect('.twin-context-rail');checks.push({searchVisible:search.width>250&&search.height>30,searchDoesNotCoverMap:search.bottom<=map.top+2,mapVisible:map.width>120&&map.height>100,labelVisible:label.width>250,rackVisible:rack.width>150&&rack.height>100,notOverlapping:width<=880?label.top>=rack.bottom-2:label.left>=rack.right-2,floorAreaSameRow:Math.abs(rect('.twin-floor-area-row label:first-child').top-rect('.twin-floor-area-row label:last-child').top)<2,productsFirst:rect('.twin-location-card').top<rect('.twin-move-control-panel').top,debug:{width,map:map.toJSON(),rack:rack.toJSON(),label:label.toJSON(),search:search.toJSON()}});
  const cell=document.querySelector('.mold-rack-cell'),cardsNode=document.querySelector('.shelf-product-cards'),elevation=document.querySelector('.twin-elevation-frame'),viewAll=document.querySelector('.shelf-view-all-products');const viewAllRect=viewAll.getBoundingClientRect();const hitViewAll=document.elementFromPoint(viewAllRect.left+viewAllRect.width/2,viewAllRect.top+viewAllRect.height/2);const readable=[...document.querySelectorAll('.shelf-product-customer,.shelf-product-name,.shelf-specification,.shelf-inventory-code')].every(node=>parseFloat(getComputedStyle(node).fontSize)>=10);checks.push({twoCards:document.querySelectorAll('.shelf-product-card').length===2,viewAllVisible:viewAllRect.width>80&&viewAllRect.height>=30,viewAllClickable:hitViewAll===viewAll||viewAll.contains(hitViewAll),noCellScroll:['visible','clip'].includes(getComputedStyle(cell).overflowY)&&['visible','clip'].includes(getComputedStyle(cardsNode).overflowY),cellFitsText:cell.scrollHeight<=cell.clientHeight+2,wholeElevationScrolls:['auto','scroll'].includes(getComputedStyle(elevation).overflowY),readable,debug:{cell:{clientHeight:cell.clientHeight,scrollHeight:cell.scrollHeight,overflow:getComputedStyle(cell).overflowY},cards:{overflow:getComputedStyle(cardsNode).overflowY},elevation:{overflow:getComputedStyle(elevation).overflowY},viewAll:viewAllRect.toJSON()}});
  const toolbar=rect('.twin-toolbar'),more=rect('.twin-workspace-more > div'),last=rect('.last-more-action');const hit=document.elementFromPoint(last.left+last.width/2,last.top+last.height/2);checks.push({toolbarAllowsMenu:getComputedStyle(document.querySelector('.twin-toolbar')).overflowY==='visible',menuEscapesToolbar:more.bottom>toolbar.bottom+20,lastActionInViewport:last.bottom<=window.innerHeight,lastActionClickable:hit===document.querySelector('.last-more-action')||document.querySelector('.last-more-action').contains(hit),debug:{toolbar:toolbar.toJSON(),more:more.toJSON(),last:last.toJSON(),overflowY:getComputedStyle(document.querySelector('.twin-toolbar')).overflowY,hit:hit?.className||hit?.tagName}});
  document.querySelector('#result').textContent=JSON.stringify(checks);
  </script></body>`);
  for(const [width,height] of [[1920,1080],[1440,950],[1024,950],[600,950]]) {
  const result=spawnSync(process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--force-device-scale-factor=1',`--window-size=${width},${height}`,'--user-data-dir='+join(dir,'profile-'+width),'--dump-dom',pathToFileURL(fixture).href],{encoding:'utf8',timeout:30000});
  assert.equal(result.status,0,result.error?.message||result.stderr);
  const checks=JSON.parse(result.stdout.match(/<pre id="result">([^<]+)/)?.[1]||'null');
  assert.ok(checks, result.stdout.slice(-1200));
  assert.ok(checks.every(row=>Object.entries(row).every(([key,value])=>key==='debug'||value===true)),JSON.stringify(checks));
  }
});
