"""Persistent original-order delivery backlog; additive, no historical backfill."""
from alembic import op
import sqlalchemy as sa

revision='db0919'
down_revision='rp0919'
branch_labels=None
depends_on=None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_backlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=250), nullable=False),
    sa.Column('customer_order_no', sa.String(length=150), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('original_quantity', sa.Integer(), nullable=False),
    sa.Column('target_quantity', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('cancelled_reason', sa.String(length=500), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("status IN ('active','cancelled') AND version > 0 AND original_quantity > 0 AND target_quantity >= original_quantity", name='ck_delivery_backlog'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['sales_order_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_index('ix_delivery_backlog_scope', 'delivery_backlogs', ['customer_id', 'status', 'due_date', 'created_at'], unique=False)
    op.create_table('delivery_backlog_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backlog_id', sa.Integer(), nullable=False),
    sa.Column('import_item_id', sa.Integer(), nullable=False),
    sa.Column('requested_quantity', sa.Integer(), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('requested_quantity > 0', name='ck_backlog_source_quantity'),
    sa.ForeignKeyConstraint(['backlog_id'], ['delivery_backlogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['import_item_id'], ['tianhua_pre_delivery_import_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('import_item_id')
    )
    op.create_index(op.f('ix_delivery_backlog_sources_backlog_id'), 'delivery_backlog_sources', ['backlog_id'], unique=False)
    op.create_table('delivery_backlog_fulfillments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backlog_id', sa.Integer(), nullable=False),
    sa.Column('delivery_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='posted', nullable=False),
    sa.Column('reversed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("quantity > 0 AND status IN ('posted','reversed')", name='ck_backlog_fulfillment'),
    sa.ForeignKeyConstraint(['backlog_id'], ['delivery_backlogs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['delivery_item_id'], ['sales_delivery_items.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backlog_id', 'delivery_item_id', 'dispatched_at', name='uq_backlog_dispatch')
    )
    op.create_index(op.f('ix_delivery_backlog_fulfillments_backlog_id'), 'delivery_backlog_fulfillments', ['backlog_id'], unique=False)
    op.create_index(op.f('ix_delivery_backlog_fulfillments_delivery_item_id'), 'delivery_backlog_fulfillments', ['delivery_item_id'], unique=False)
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == 'sqlite':
        op.execute("CREATE TRIGGER delivery_backlogs_immutable BEFORE UPDATE OF id, customer_id, product_id, order_item_id, stock_code, product_name, customer_order_no, due_date, original_quantity, reason, created_by, created_at ON delivery_backlogs BEGIN SELECT RAISE(ABORT,'backlog source is immutable'); END")
        op.execute("CREATE TRIGGER delivery_backlog_sources_immutable BEFORE UPDATE ON delivery_backlog_sources BEGIN SELECT RAISE(ABORT,'backlog source is immutable'); END")
        op.execute("CREATE TRIGGER delivery_backlog_fulfillments_immutable BEFORE UPDATE OF id, backlog_id, delivery_item_id, quantity, dispatched_at, created_by ON delivery_backlog_fulfillments BEGIN SELECT RAISE(ABORT,'backlog dispatch is immutable'); END")
        for table in ('delivery_backlogs','delivery_backlog_sources','delivery_backlog_fulfillments'):
            op.execute(f"CREATE TRIGGER {table}_no_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT,'backlog history cannot be deleted'); END")


def downgrade():
    db=op.get_bind()
    tables=('delivery_backlog_fulfillments','delivery_backlog_sources','delivery_backlogs')
    for table in tables:
        if db.execute(sa.text(f'SELECT 1 FROM {table} LIMIT 1')).first():
            raise RuntimeError('已有待补送或发货核销事实，禁止删除历史；请使用已验证恢复备份')
    for table in tables:
        if db.dialect.name=='sqlite':
            op.execute(f'DROP TRIGGER {table}_immutable')
            op.execute(f'DROP TRIGGER {table}_no_delete')
        op.drop_table(table)
