'use strict';
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict'),cp=require('child_process');
const {test}=require('node:test');
const root=path.resolve(__dirname,'../..'),baseline=process.argv.includes('--baseline')||process.env.DELIVERY_DISPATCH_BASELINE==='1';
const html=baseline?cp.execFileSync('git',['show','069ce9f5:static/index.html'],{cwd:root,encoding:'utf8',maxBuffer:16*1024*1024}):fs.readFileSync(path.join(root,'static/index.html'),'utf8');
const moduleSource=fs.readFileSync(path.join(root,'static/ui/delivery-dispatch-recovery.js'),'utf8');
function storage(){const values=new Map();return{get length(){return values.size},key:i=>[...values.keys()][i]??null,getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k),values};}
function method(name){const start=new RegExp('^[ \\t]*(?:async )?'+name+'\\([^\\n]*\\) \\{','m').exec(html);if(!start)return null;const end=/^          \},?$/m.exec(html.slice(start.index));assert.ok(end,name);return html.slice(start.index,start.index+end.index+end[0].length).trim().replace(/,$/,'');}
const names=['loadDeliveries','showDeliveryStockWarnings','deliveryDispatchIsBusy','deliveryDispatchController','refreshDeliveryDispatchRecovery','deliveryDispatchContext','deliveryDispatchRequest','deliveryDispatchLines','deliveryDispatchCurrentText','currentDeliveryDraftRow','dispatchCurrentDeliveryDraft','dispatchDelivery','sendDeliveryDispatchPreview','refreshDeliveryDispatchAfterSuccess','sendDeliveryDispatchRecord','queryDeliveryDispatchResult','closeDeliveryDispatchRequest','viewDeliveryDispatchOriginal'];
function packet(id=71,version=1){return{schema_version:1,current_actor_id:1,snapshot_hash:'a'.repeat(64),snapshot:{schema_version:1,delivery:{id,customer_id:3,status:'pending',version,source_mode:'order',delivery_date:'2026-10-10',vehicle_number:null},items:[{delivery_item_id:17,revision_number:1,source_type:'order',order_item_id:11,product_id:null,source_product_id:null,customer_id:3,customer_quantity:3,physical_quantity:3,customer_unit:null,physical_unit:null,quantity_contract:null,goods:[{component_snapshot_id:null,source_product_id:null,customer_id:3,physical_quantity:3,physical_unit:null}],semi_requirements:[],direct_completion_sources:[],order_delivered_quantity:null,allocation_mode:'on_dispatch',allocations:[]}],pick_task:null,pick_action:'none',expected_final_items:[{delivery_item_id:17,customer_quantity:3,physical_quantity:3,customer_unit:null,physical_unit:null,goods:[{component_snapshot_id:null,source_product_id:null,customer_id:3,physical_quantity:3,physical_unit:null}]}]},display:{delivery_number:'送货合成单',customer_name:'合成客户',items:[{delivery_item_id:17,product_code:'TEST-17',product_name:'合成纸箱',original_customer_quantity:3,original_physical_quantity:3,final_customer_quantity:3,final_physical_quantity:3,customer_unit:null,physical_unit:null,allocation_mode:'on_dispatch'}]}};}
function body(id=71,key='test-dispatch-0001'){const p=packet(id);return{expected_actor_id:1,idempotency_key:key,expected_version:1,snapshot_hash:p.snapshot_hash,snapshot:p.snapshot,confirm_pick_exception:false};}
function setup(shared=storage(),options={}){
 const calls=[],toasts=[],prints=[];let handler=async()=>({data:packet()});
 const window={localStorage:shared,erpAuthRequired:()=>toasts.push('current401')};
 const axios={get:(u,o)=>{calls.push({method:'get',url:u,...o});return handler({method:'get',url:u,...o})},create:()=>({request:c=>{calls.push(c);return handler(c)}}),post:(u,b)=>{calls.push({method:'post',url:u,data:b});return handler({method:'post',url:u,data:b})},put:(u,b)=>{calls.push({method:'put',url:u,data:b});return handler({method:'put',url:u,data:b})}};
 const context=vm.createContext({window,axios,console,setTimeout:options.setTimeout||setTimeout,clearTimeout:options.clearTimeout||clearTimeout,confirm:()=>true,alert:m=>toasts.push('alert:'+m),createIdempotencyKey:()=> options.key||'test-ui-'+Math.random().toString(36).slice(2),Number,Date,URLSearchParams});vm.runInContext(moduleSource,context);
 const methods=vm.runInContext('({'+names.map(method).filter(Boolean).join(',\n')+'})',context);
 const state={...methods,user:{id:1},authGeneration:1,activePage:'deliveries',modal:null,deliveryDispatchEpoch:0,deliveryDispatchBusy:false,deliveryDispatchRecords:[],deliveryDispatchStorageError:'',deliveryDispatchPreview:null,deliveryDispatchNotice:null,deliveryDispatchNotRecorded:{},deliveryOperationState:{action:''},receiptOperationState:{action:''},deliveryInlineEdit:null,deliveries:[],expandedDeliveryRows:{},pages:{deliveries:1},deliveryListState:{request_token:0},deliveryListFilters:{},deliveryDetailedFilters:{},deliveryListPageSize:()=>20,showToast:m=>toasts.push(m),errorMessage:e=>e.response?.data?.detail||e.message,normalizeDeliveryPickTask:r=>r.pick_task||null,invalidateDeliveryListDetail:()=>{},openDeliveryPrintTab:async()=>({activate:()=>prints.push('activate'),abort:()=>prints.push('abort')}),loadOrders:async()=>true,loadKpi:async()=>true,hasPermission:()=>false};
 return{state,window,api:window.TmDeliveryDispatchRecovery,calls,toasts,prints,storage:shared,handler:f=>handler=f};
}
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject};};
test('actual dispatch opens a read-only preview before any write; no independent apply/prepare',async()=>{const h=setup();await h.state.dispatchDelivery({id:71,version:1},{confirmAction:false});assert.equal(h.calls.length,1);assert.equal(h.calls[0].method,'get');assert.match(h.calls[0].url,/dispatch-snapshot/);assert.equal(h.state.modal.type,'deliveryDispatch');assert.equal(h.storage.length,0)});
test('actual bad snapshot and changed known version stop before a write',async()=>{for(const p of [{},packet(71,2)]){const h=setup();h.handler(async()=>({data:p}));await h.state.dispatchDelivery({id:71,version:1});assert.equal(h.state.modal,null);assert.equal(h.calls.some(c=>c.method==='put'),false);assert.equal(h.toasts.length,1)}});
test('saved form must bind complete persistent line identities before dispatch preview',async()=>{const h=setup(),form={customer_id:3,version:1,lines:[{delivered_quantity:3}]};h.state.deliveryForm=form;await h.state.dispatchDelivery({id:71,version:1},{expectedForm:form});assert.equal(h.state.modal,null);assert.match(h.toasts[0],/原草稿/)});
test('storage unavailable blocks the actual preview-send before any PUT',async()=>{const h=setup();await h.state.dispatchDelivery({id:71,version:1});h.storage.setItem=()=>{throw Error('quota')};assert.equal(await h.state.sendDeliveryDispatchPreview(),false);assert.equal(h.calls.some(c=>c.method==='put'),false);assert.match(h.toasts.at(-1),/存储/)});
test('actual partial write ack remains unknown across new page/controller, query never silently retries business PUT',async()=>{const h=setup();await h.state.dispatchDelivery({id:71,version:1});h.handler(async()=>({data:{}}));await h.state.sendDeliveryDispatchPreview();const record=h.api.create(1,h.storage).list()[0];assert.equal(record.state,'unknown');assert.ok(record.body.snapshot.items.length);const page=setup(h.storage);page.state.refreshDeliveryDispatchRecovery();assert.equal(page.state.deliveryDispatchRecords.length,1);page.handler(async()=>({data:{}}));await page.state.queryDeliveryDispatchResult(record);assert.equal(page.calls.length,1);assert.equal(page.calls[0].method,'post');assert.match(page.calls[0].url,/\/resolve$/);assert.equal(page.state.deliveryDispatchNotRecorded[record.key],undefined);assert.equal(page.api.create(1,page.storage).get(record.key).state,'unknown')});
test('same original delivery is blocked, unrelated delivery remains available; actor records do not mix',()=>{const h=setup(),a=h.api.create(1,h.storage);a.prepare(body(),packet().display);a.unknown('test-dispatch-0001');assert.throws(()=>a.prepare(body(71,'another-key-0001'),packet().display),/已有待核对/);assert.equal(a.prepare(body(72,'other-delivery-0001'),packet(72).display).deliveryId,72);assert.equal(h.api.create(2,h.storage).list().length,0)});
test('actual late snapshot from A cannot open B window; late current401 is ignored while current401 still acts',async()=>{const h=setup(),d=deferred();h.handler(()=>d.promise);const pending=h.state.dispatchDelivery({id:71,version:1});h.state.user={id:2};h.state.authGeneration=2;h.state.modal={type:'customer'};d.reject({response:{status:401},message:'late401'});await pending;assert.equal(h.state.modal.type,'customer');assert.equal(h.toasts.includes('current401'),false);const c=setup();c.handler(async()=>{throw{response:{status:401},message:'current401'}});await c.state.dispatchDelivery({id:71,version:1});assert.equal(c.toasts.includes('current401'),true)});
test('actual in-flight PUT double click is blocked; late account response does not activate or close new modal',async()=>{const h=setup(),d=deferred();await h.state.dispatchDelivery({id:71,version:1});h.handler(()=>d.promise);const sending=h.state.sendDeliveryDispatchPreview();await Promise.resolve();await Promise.resolve();await h.state.sendDeliveryDispatchPreview();assert.equal(h.calls.filter(c=>c.method==='put').length,1);h.state.user={id:2};h.state.authGeneration=2;h.state.modal={type:'customer'};d.resolve({data:{}});await sending;assert.equal(h.state.modal.type,'customer');assert.equal(h.prints.includes('activate'),false);assert.equal(h.api.create(1,h.storage).list().length,1)});
test('independent unknown and confirmed credentials are monotonic under a late pending writer',()=>{const h=setup(),a=h.api.create(1,h.storage),b=h.api.create(1,h.storage);const record=a.prepare(normal.originalBody,normal.snapshot.body.display);a.sending(record.key);b.unknown(record.key);assert.equal(a.get(record.key).state,'unknown');a.confirm(record.key,normal.write.body.dispatch_receipt,null);b.unknown(record.key);assert.equal(a.get(record.key).state,'confirmed');assert.throws(()=>b.sending(record.key),/已确认/)});
test('actual HTML recovery is outside the empty list and dedicated preview has an explicit send control',()=>{const {parseHTML}=require('linkedom'),{document}=parseHTML(html);function find(scope,selector){const direct=scope.querySelector(selector);if(direct)return direct;for(const t of scope.querySelectorAll('template')){const nested=find(t.content,selector);if(nested)return nested;}return null;}const recovery=find(document,'[data-delivery-dispatch-recovery]'),preview=find(document,'[data-delivery-dispatch-preview]');assert.ok(recovery);assert.ok(preview?.querySelector('[data-delivery-dispatch-send]'));assert.equal(recovery.closest('table'),null);assert.match(preview.textContent,/本次发货/);assert.ok(document.querySelector('script[src^="/static/ui/delivery-dispatch-recovery.js?"]'))});

const normal=JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/delivery-dispatch-recovery/normal.json'),'utf8'));
const json=value=>JSON.parse(JSON.stringify(value));
function realSetup(shared=storage(),options={}){const h=setup(shared,{key:normal.originalBody.idempotency_key,...options});h.handler(async c=>({data:c.url.includes('dispatch-snapshot')?normal.snapshot.body:c.url.endsWith('/dispatch')?normal.write.body:c.url.endsWith('/resolve')?normal.resolve.body:c.url.includes('/printed')?{}:{items:[],total:0}}));return h;}
test('real HTTP normal snapshot, first/replay and readonly proof pass the exact validator',()=>{const h=realSetup(),r=h.api.create(1,h.storage).prepare(normal.originalBody,normal.snapshot.body.display);assert.equal(h.api.validateSnapshot(normal.snapshot.body,1,1,1).snapshot.delivery.id,1);assert.equal(h.api.validateCompleted(normal.write.body,r,1).delivery_id,1);assert.equal(h.api.validateCompleted(normal.replay.body,r,1).delivery_id,1);assert.equal(h.api.validateResolve(normal.resolve.body,r,1).status,'completed');for(const mutate of [p=>p.dispatch_receipt.final_items=[],p=>p.dispatch_receipt.movements=[],p=>p.dispatch_receipt.request.expected_version=99,p=>p.current_actor_id=2]){const p=json(normal.write.body);mutate(p);assert.throws(()=>h.api.validateCompleted(p,r,1),/不完整/);}});
test('actual normal preview→one command uses unchanged real body, closes only its window and preserves completed proof',async()=>{const h=realSetup();await h.state.dispatchDelivery({id:1,version:1});assert.equal(await h.state.sendDeliveryDispatchPreview(),true);const command=h.calls.find(c=>c.url.endsWith('/dispatch'));assert.deepEqual(json(command.data),normal.originalBody);assert.equal(h.calls.filter(c=>c.url.endsWith('/dispatch')).length,1);assert.equal(h.calls.some(c=>/apply-pick|prepare-accompany/.test(c.url)),false);assert.equal(h.state.modal,null);assert.equal(h.prints.filter(x=>x==='activate').length,1);assert.equal(h.api.create(1,h.storage).get(normal.originalBody.idempotency_key).state,'confirmed');assert.match(h.state.deliveryDispatchNotice.message,/已完成/)});
test('real completed readonly response after lost ack restores from fresh page without business command or print',async()=>{const h=realSetup(),controller=h.api.create(1,h.storage),r=controller.prepare(normal.originalBody,normal.snapshot.body.display);controller.unknown(r.key);const page=realSetup(h.storage);page.state.refreshDeliveryDispatchRecovery();assert.equal(page.state.deliveryDispatchRecords.length,1);assert.equal(await page.state.queryDeliveryDispatchResult(page.state.deliveryDispatchRecords[0]),true);assert.equal(page.calls.length,1);assert.match(page.calls[0].url,/resolve$/);assert.deepEqual(json(page.calls[0].data.original_request),normal.originalBody);assert.equal(page.prints.length,0);assert.equal(page.state.deliveryDispatchNotice.record.state,'confirmed');assert.equal(page.state.deliveryDispatchRecords.length,0);});
test('valid real late completed command cannot activate print, close another modal or confirm under B',async()=>{const h=realSetup(),d=deferred();await h.state.dispatchDelivery({id:1,version:1});h.handler(()=>d.promise);const action=h.state.sendDeliveryDispatchPreview();await Promise.resolve();await Promise.resolve();h.state.user={id:2};h.state.authGeneration=2;h.state.modal={type:'delivery',name:'B'};d.resolve({data:normal.write.body});await action;assert.equal(h.state.modal.name,'B');assert.equal(h.state.deliveryDispatchNotice,null);assert.equal(h.prints.includes('activate'),false);assert.notEqual(h.api.create(1,h.storage).get(normal.originalBody.idempotency_key).state,'confirmed');});
test('completed result survives print registration/list failure and cannot resend',async()=>{const h=realSetup();await h.state.dispatchDelivery({id:1,version:1});h.handler(async c=>{if(c.url.endsWith('/dispatch'))return{data:normal.write.body};throw Error('auxiliary unavailable')});assert.equal(await h.state.sendDeliveryDispatchPreview(),true);assert.match(h.state.deliveryDispatchNotice.message,/已完成/);assert.match(h.state.deliveryDispatchNotice.auxiliary,/刷新失败/);assert.equal(h.api.create(1,h.storage).get(normal.originalBody.idempotency_key).state,'confirmed');assert.equal(await h.state.sendDeliveryDispatchRecord(h.state.deliveryDispatchNotice.record,true),false);assert.equal(h.calls.filter(c=>c.url.endsWith('/dispatch')).length,1);});
test('confirmed storage failure after real readonly proof preserves completed memory and blocks repeat command',async()=>{const h=realSetup(),a=h.api.create(1,h.storage),r=a.prepare(normal.originalBody,normal.snapshot.body.display);a.unknown(r.key);const original=h.storage.setItem;h.storage.setItem=(k,v)=>{if(k.startsWith('erp-delivery-dispatch-confirmed:'))throw Error('quota');original(k,v)};assert.equal(await h.state.queryDeliveryDispatchResult(r),true);assert.equal(h.state.deliveryDispatchNotice.record.state,'confirmed');assert.match(h.state.deliveryDispatchNotice.auxiliary,/未能保存确认/);assert.equal(await h.state.sendDeliveryDispatchRecord(r,true),false);assert.equal(h.calls.filter(c=>c.url.endsWith('/dispatch')).length,0);});
test('finite request timeout leaves full unknown body and clears busy without retry; late transport resolution cannot succeed',async()=>{let timeout;const h=realSetup(storage(),{setTimeout:f=>{timeout=f;return 1},clearTimeout:()=>{}});await h.state.dispatchDelivery({id:1,version:1});const d=deferred();h.handler(()=>d.promise);const pending=h.state.sendDeliveryDispatchPreview();await new Promise(setImmediate);assert.equal(typeof timeout,'function');timeout();await pending;assert.equal(h.state.deliveryDispatchBusy,false);assert.equal(h.api.create(1,h.storage).get(normal.originalBody.idempotency_key).state,'unknown');d.resolve({data:normal.write.body});await Promise.resolve();assert.equal(h.state.deliveryDispatchNotice,null);assert.equal(h.calls.filter(c=>c.url.endsWith('/dispatch')).length,1);});
test('actual preview HTML mounts with real Vue and explicit click sends the one real command',async()=>{
 const {parseHTML}=require('linkedom'), source=parseHTML(html).document;
 function find(scope){const direct=scope.querySelector('[data-delivery-dispatch-preview]');if(direct)return direct;for(const t of scope.querySelectorAll('template')){const nested=find(t.content);if(nested)return nested;}return null;}
 const template='<template v-if="modal">'+find(source).outerHTML.replace('v-else-if=','v-if=')+'</template>',dom=parseHTML('<html><body><div id="test"></div></body></html>');
 const runtime=vm.createContext({console,document:dom.document,window:dom.window,Element:dom.window.Element,HTMLElement:dom.window.HTMLElement,SVGElement:dom.window.SVGElement,Node:dom.window.Node,setTimeout,clearTimeout});
 vm.runInContext(fs.readFileSync(path.join(root,'static/vendor/vue-3.5.40.global.prod.js'),'utf8'),runtime);
 const h=realSetup();await h.state.dispatchDelivery({id:1,version:1});
 const functions=Object.fromEntries(Object.entries(h.state).filter(([,v])=>typeof v==='function')),data=Object.fromEntries(Object.entries(h.state).filter(([,v])=>typeof v!=='function'));
 const app=runtime.Vue.createApp({data:()=>data,methods:functions,template}),mounted=app.mount(dom.document.querySelector('#test'));
 const button=dom.document.querySelector('[data-delivery-dispatch-send]');assert.ok(button);assert.match(dom.document.body.textContent,/30/);assert.equal(h.calls.filter(c=>c.url.endsWith('/dispatch')).length,0);
 button.dispatchEvent(new dom.window.Event('click'));await new Promise(setImmediate);await runtime.Vue.nextTick();
 assert.equal(h.calls.filter(c=>c.url.endsWith('/dispatch')).length,1);assert.equal(dom.document.querySelector('[data-delivery-dispatch-send]'),null);assert.equal(mounted.deliveryDispatchNotice.record.state,'confirmed');app.unmount();
});
test('actual saved-draft button verifies real persistent identity/version/lines and only opens preview',async()=>{const h=realSetup();h.state.modal={type:'delivery'};h.state.deliveryForm={editingId:1,version:1,customer_id:1,lines:normal.originalBody.snapshot.items.map(i=>({delivery_item_id:i.delivery_item_id,delivered_quantity:i.customer_quantity}))};h.state.deliveryFormIsDirty=()=>false;assert.equal(await h.state.dispatchCurrentDeliveryDraft(),false);assert.equal(h.state.modal.type,'deliveryDispatch');assert.equal(h.calls.filter(c=>c.method==='put').length,0);});
test('actual close persists closing before transport; failed close/refresh can query or reclose but cannot execute old/new same-delivery command',async()=>{const h=realSetup(),a=h.api.create(1,h.storage),r=a.prepare(normal.originalBody,normal.snapshot.body.display);a.unknown(r.key);h.handler(async c=>{assert.match(c.url,/close$/);assert.equal(a.get(r.key).state,'closing');assert.deepEqual(json(c.data.original_request),normal.originalBody);throw{response:{status:500},message:'close ack unknown'};});assert.equal(await h.state.closeDeliveryDispatchRequest(r),false);assert.equal(a.get(r.key).state,'closing');const page=realSetup(h.storage);page.state.refreshDeliveryDispatchRecovery();assert.equal(page.state.deliveryDispatchRecords[0].state,'closing');page.state.deliveryDispatchNotRecorded[r.key]=true;assert.equal(await page.state.sendDeliveryDispatchRecord(r,true),false);assert.equal(page.calls.length,0);assert.throws(()=>page.api.create(1,page.storage).prepare({...normal.originalBody,idempotency_key:'new-key-after-close-unknown'},normal.snapshot.body.display),/已有待核对/);});
test('actual closing intent storage failure prevents close POST',async()=>{const h=realSetup(),a=h.api.create(1,h.storage),r=a.prepare(normal.originalBody,normal.snapshot.body.display);h.storage.setItem=()=>{throw Error('quota')};assert.equal(await h.state.closeDeliveryDispatchRequest(r),false);assert.equal(h.calls.length,0);assert.notEqual(a.get(r.key).state,'closed');});
test('late print-registration error after another modal opens cannot overwrite its notice or refresh its list',async()=>{const h=realSetup(),d=deferred();await h.state.dispatchDelivery({id:1,version:1});h.handler(c=>c.url.endsWith('/dispatch')?Promise.resolve({data:normal.write.body}):d.promise);const sending=h.state.sendDeliveryDispatchPreview();await new Promise(setImmediate);assert.equal(h.state.deliveryDispatchNotice.record.state,'confirmed');h.state.modal={type:'customer'};h.state.deliveryDispatchNotice={newWindow:true};d.reject(Error('late auxiliary'));await sending;assert.equal(h.state.modal.type,'customer');assert.equal(h.state.deliveryDispatchNotice.newWindow,true);assert.equal(h.calls.filter(c=>c.method==='get').length,1);});
test('actual recovery card Vue click performs readonly resolve and shows original completion without auto print',async()=>{
 const {parseHTML}=require('linkedom'),source=parseHTML(html).document;function find(scope,selector){const direct=scope.querySelector(selector);if(direct)return direct;for(const t of scope.querySelectorAll('template')){const nested=find(t.content,selector);if(nested)return nested;}return null;}
 const template='<div>'+find(source,'[data-delivery-dispatch-success]').outerHTML+find(source,'[data-delivery-dispatch-recovery]').outerHTML+'</div>',dom=parseHTML('<html><body><div id="test"></div></body></html>');
 const runtime=vm.createContext({console,document:dom.document,window:dom.window,Element:dom.window.Element,HTMLElement:dom.window.HTMLElement,SVGElement:dom.window.SVGElement,Node:dom.window.Node,setTimeout,clearTimeout});vm.runInContext(fs.readFileSync(path.join(root,'static/vendor/vue-3.5.40.global.prod.js'),'utf8'),runtime);
 const h=realSetup(),a=h.api.create(1,h.storage),r=a.prepare(normal.originalBody,normal.snapshot.body.display);a.unknown(r.key);h.state.refreshDeliveryDispatchRecovery();h.state.printDelivery=()=>assert.fail('no automatic print');
 const functions=Object.fromEntries(Object.entries(h.state).filter(([,v])=>typeof v==='function')),data=Object.fromEntries(Object.entries(h.state).filter(([,v])=>typeof v!=='function'));const app=runtime.Vue.createApp({data:()=>data,methods:functions,template}),mounted=app.mount(dom.document.querySelector('#test'));
 assert.match(dom.document.body.textContent,/原发货结果待核对/);assert.match(dom.document.body.textContent,/30/);dom.document.querySelector('[data-delivery-dispatch-recovery] .primary').dispatchEvent(new dom.window.Event('click'));await new Promise(setImmediate);await runtime.Vue.nextTick();
 assert.equal(h.calls.length,1);assert.match(h.calls[0].url,/resolve$/);assert.equal(dom.document.querySelector('[data-delivery-dispatch-recovery]'),null);assert.match(dom.document.querySelector('[data-delivery-dispatch-success]').textContent,/原发货已完成/);assert.equal(mounted.deliveryDispatchNotice.record.state,'confirmed');app.unmount();
});
test('actual entire HTML template and inline script parse, with LAN-safe module not requiring WebCrypto',()=>{const {parseHTML}=require('linkedom'),{document}=parseHTML(html);const runtime=vm.createContext({console,document});vm.runInContext(fs.readFileSync(path.join(root,'static/vendor/vue-3.5.40.global.prod.js'),'utf8'),runtime);const errors=[];runtime.Vue.compile(document.querySelector('#app').innerHTML,{onError:e=>errors.push(e.message)});assert.deepEqual(errors,[]);for(const script of document.querySelectorAll('script:not([src])'))if(script.textContent.trim())new vm.Script(script.textContent);const h=realSetup();assert.equal(h.window.crypto,undefined);assert.equal(h.api.validateCommand(normal.originalBody,1).snapshot_hash,normal.originalBody.snapshot_hash);});
test('same actor re-login with new authentication generation does not inherit old busy or accept old success',async()=>{const h=realSetup(),d=deferred();await h.state.dispatchDelivery({id:1,version:1});h.handler(()=>d.promise);const sending=h.state.sendDeliveryDispatchPreview();await new Promise(setImmediate);assert.equal(h.state.deliveryDispatchIsBusy(),true);h.state.authGeneration=2;h.state.modal=null;assert.equal(h.state.deliveryDispatchIsBusy(),false);d.resolve({data:normal.write.body});await sending;assert.equal(h.state.deliveryDispatchNotice,null);assert.notEqual(h.api.create(1,h.storage).get(normal.originalBody.idempotency_key).state,'confirmed');h.handler(async()=>({data:packet(72)}));await h.state.dispatchDelivery({id:72,version:1});assert.equal(h.state.modal.type,'deliveryDispatch');});
test('actual first completed dispatch retains one stock-warning prompt after its own modal closes; readonly recovery does not repeat it',async()=>{const h=realSetup();h.state.hasPermission=p=>p==='warehouse.view';const ordinary=h.calls;h.handler(async c=>({data:c.url.includes('dispatch-snapshot')?normal.snapshot.body:c.url.endsWith('/dispatch')?normal.write.body:c.url.includes('/stock-warnings')?{items:[{product_code:'warning-fixture',available_quantity:0,warning_quantity:10}]}:c.url.includes('/printed')?{}:{items:[],total:0}}));await h.state.dispatchDelivery({id:1,version:1});assert.equal(await h.state.sendDeliveryDispatchPreview(),true);assert.equal(ordinary.filter(c=>c.url.endsWith('/stock-warnings')).length,1);assert.equal(h.toasts.filter(t=>t.startsWith('alert:')).length,1);assert.equal(h.state.deliveryDispatchNotice.record.state,'confirmed');const page=realSetup(h.storage);page.state.hasPermission=()=>true;await page.state.queryDeliveryDispatchResult(h.state.deliveryDispatchNotice.record);assert.equal(page.calls.filter(c=>c.url.includes('/stock-warnings')).length,0);});
test('actual page list entry restores original pending request even with an empty server list, before readonly query',async()=>{const first=realSetup(),a=first.api.create(1,first.storage),record=a.prepare(normal.originalBody,normal.snapshot.body.display);a.unknown(record.key);const page=realSetup(first.storage);assert.equal(await page.state.loadDeliveries(),true);assert.equal(page.state.deliveries.length,0);assert.equal(page.state.deliveryDispatchRecords.length,1);assert.deepEqual(json(page.state.deliveryDispatchRecords[0].body),normal.originalBody);await page.state.queryDeliveryDispatchResult(page.state.deliveryDispatchRecords[0]);assert.equal(page.calls.filter(c=>c.method==='post').length,1);assert.equal(page.calls.filter(c=>c.method==='put').length,0);});

function fixture(name){return JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/delivery-dispatch-recovery',name+'.json'),'utf8'));}
function event(archive,suffix,status=200){const found=archive.events.find(e=>e.url.endsWith(suffix)&&e.response.status===status);assert.ok(found,archive.fixtureNode+':'+suffix);return found.response.body;}
function archivedSetup(archive,shared=storage()){const h=setup(shared,{key:archive.originalBody.idempotency_key});h.state.user={id:archive.actorId};h.handler(async c=>({data:c.url.includes('dispatch-snapshot')?archive.snapshot.body:c.url.endsWith('/resolve')?event(archive,'/resolve'):c.url.endsWith('/close')?event(archive,'/close'):c.url.endsWith('/dispatch')?event(archive,'/dispatch'):{items:[],total:0}}));return h;}
function archivedRecord(h,x){return h.api.create(x.actorId,h.storage).prepare(x.originalBody,x.snapshot.body.display);}
test('real close wins: durable closure unlocks only after proof, late unknown cannot downgrade and next dispatch still needs new preview',async()=>{const x=fixture('close-wins'),h=archivedSetup(x),r=archivedRecord(h,x);h.api.create(x.actorId,h.storage).unknown(r.key);assert.equal(await h.state.closeDeliveryDispatchRequest(r),true);const closed=h.api.create(x.actorId,h.storage).get(r.key);assert.equal(closed.state,'closed');assert.equal(h.state.deliveryDispatchRecords.length,0);assert.match(h.state.deliveryDispatchNotice.message,/已结束/);assert.equal(h.prints.length,0);assert.equal(h.calls.length,1);assert.match(h.calls[0].url,/close$/);h.api.create(x.actorId,h.storage).unknown(r.key);assert.equal(h.api.create(x.actorId,h.storage).get(r.key).state,'closed');assert.equal(await h.state.sendDeliveryDispatchRecord(r,true),false);assert.equal(h.calls.length,1);const newRecord=h.api.create(x.actorId,h.storage).prepare({...x.originalBody,idempotency_key:'after-closed-explicit-new-key'},x.snapshot.body.display);assert.equal(newRecord.state,'prepared');assert.equal(h.calls.length,1);const bad=json(event(x,'/close'));bad.closure_receipt.request.expected_version++;assert.throws(()=>h.api.validateClosed(bad,r,x.actorId),/不完整/);});
test('real execute wins before close: actual close shows original completion and never calls it cancellation or automatically prints',async()=>{const x=fixture('execute-wins-close'),h=archivedSetup(x),r=archivedRecord(h,x);h.api.create(x.actorId,h.storage).unknown(r.key);assert.equal(await h.state.closeDeliveryDispatchRequest(r),true);assert.equal(h.state.deliveryDispatchNotice.record.state,'confirmed');assert.match(h.state.deliveryDispatchNotice.message,/完成/);assert.doesNotMatch(h.state.deliveryDispatchNotice.message,/已结束|取消/);assert.equal(h.prints.length,0);assert.equal(h.calls.filter(c=>c.url.endsWith('/dispatch')).length,0);assert.deepEqual(json(h.state.deliveryDispatchNotice.record.receipt),event(x,'/close').dispatch_receipt);});
test('real close commit ack loss: refresh resolves closure with zero execute, while earlier not-recorded keeps closing and forbids continue',async()=>{const x=fixture('close-committed-ack-loss');x.originalBody=json(x.events.find(e=>e.url.endsWith('/close')).request.original_request);const h=archivedSetup(x),r=archivedRecord(h,x);h.handler(async()=>{throw{response:{status:500,data:event(x,'/close',500)},message:'real close ack loss'}});assert.equal(await h.state.closeDeliveryDispatchRequest(r),false);assert.equal(h.api.create(x.actorId,h.storage).get(r.key).state,'closing');const page=archivedSetup(x,h.storage);page.handler(async c=>({data:c.url.endsWith('/resolve')?x.events.find(e=>e.url.endsWith('/resolve')&&e.response.body.status==='not_recorded').response.body:{items:[],total:0}}));await page.state.loadDeliveries();assert.equal(page.state.deliveryDispatchRecords[0].state,'closing');await page.state.queryDeliveryDispatchResult(r);assert.match(page.toasts.at(-1),/不可继续/);assert.equal(await page.state.sendDeliveryDispatchRecord(r,true),false);page.handler(async()=>({data:x.events.find(e=>e.url.endsWith('/resolve')&&e.response.body.status==='closed').response.body}));assert.equal(await page.state.queryDeliveryDispatchResult(r),true);assert.equal(page.state.deliveryDispatchNotice.record.state,'closed');assert.equal(page.calls.filter(c=>c.url.endsWith('/dispatch')).length,0);assert.equal(page.prints.length,0);});
test('real closure verified but terminal storage failure retains closing until another readonly proof can be persisted',async()=>{const x=fixture('close-wins'),h=archivedSetup(x),r=archivedRecord(h,x),set=h.storage.setItem;h.storage.setItem=(k,v)=>{if(k.startsWith('erp-delivery-dispatch-confirmed:'))throw Error('quota');set(k,v)};assert.equal(await h.state.closeDeliveryDispatchRequest(r),true);assert.equal(h.api.create(x.actorId,h.storage).get(r.key).state,'closing');assert.match(h.state.deliveryDispatchNotice.auxiliary,/未能/);assert.throws(()=>h.api.create(x.actorId,h.storage).prepare({...x.originalBody,idempotency_key:'storage-failed-new-key'},x.snapshot.body.display),/已有待核对/);h.storage.setItem=set;assert.equal(await h.state.queryDeliveryDispatchResult(r),true);assert.equal(h.api.create(x.actorId,h.storage).get(r.key).state,'closed');});
test('real business commit then ack loss flows through actual empty-list refresh and readonly result without another dispatch',async()=>{const x=fixture('committed-ack-loss'),h=archivedSetup(x);await h.state.dispatchDelivery({id:x.originalBody.snapshot.delivery.id,version:x.originalBody.expected_version});h.handler(async()=>{throw{response:{status:500,data:x.write.body},message:'real committed response loss'}});await h.state.sendDeliveryDispatchPreview();const record=h.api.create(x.actorId,h.storage).list()[0];assert.equal(record.state,'unknown');const page=archivedSetup(x,h.storage);await page.state.loadDeliveries();assert.equal(page.state.deliveryDispatchRecords.length,1);assert.equal(await page.state.queryDeliveryDispatchResult(page.state.deliveryDispatchRecords[0]),true);assert.equal(page.state.deliveryDispatchNotice.record.state,'confirmed');assert.equal(page.calls.filter(c=>c.url.endsWith('/dispatch')).length,0);assert.equal(page.prints.length,0);assert.deepEqual(json(page.calls.find(c=>c.url.endsWith('/resolve')).data.original_request),x.originalBody);});
test('real consumption sources: legacy semi minimum, accompany components and both legal direct forms pass; partial credit cannot fake complete',()=>{for(const name of ['legacy-semi','accompany','ordinary-direct','component-direct']){const x=fixture(name),h=archivedSetup(x),r=archivedRecord(h,x);assert.equal(h.api.validateCompleted(x.write.body,r,x.actorId).delivery_id,r.deliveryId);const bad=json(x.write.body);bad.dispatch_receipt.movements=[];bad.dispatch_receipt.direct_component_allocations=[];bad.dispatch_receipt.direct_completion_coverage=[];assert.throws(()=>h.api.validateCompleted(bad,r,x.actorId),/不完整/);}const h=realSetup(),r=archivedRecord(h,normal),bad=json(normal.write.body);bad.dispatch_receipt.movements[0].requirement_quantity--;assert.throws(()=>h.api.validateCompleted(bad,r,1),/不完整/);});

test('final real HTTP dual quantities, pick apply, unordered and subkit meet the frozen proof contract without summing unlike units',()=>{for(const name of ['order-dual','pick-apply','unordered-dual','subkit']){const x=fixture(name),h=archivedSetup(x),r=archivedRecord(h,x),success=x.successfulWrite||x.write;assert.equal(success.status,200,name);assert.equal(h.api.validateCompleted(success.body,r,x.actorId).delivery_id,r.deliveryId);if(x.resolve)assert.equal(h.api.validateResolve(x.resolve.body,r,x.actorId).status,'completed');const bad=json(success.body);bad.dispatch_receipt.movements=[];bad.dispatch_receipt.direct_component_allocations=[];bad.dispatch_receipt.direct_completion_coverage=[];assert.throws(()=>h.api.validateCompleted(bad,r,x.actorId),/不完整/);}
 const x=fixture('order-dual'),h=archivedSetup(x),r=archivedRecord(h,x);assert.equal(x.originalBody.snapshot.items[0].customer_quantity,100);assert.equal(x.originalBody.snapshot.items[0].physical_quantity,200);const bad=json(x.write.body);bad.dispatch_receipt.movements[0].requirement_quantity++;assert.throws(()=>h.api.validateCompleted(bad,r,x.actorId),/不完整/);
});
test('portable real HTTP fixtures are tied to one final source and preserve archive bytes without credentials',()=>{const manifest=fixture('manifest'),crypto=require('node:crypto');assert.equal(manifest.sourceCandidate,'5111aa0ff93760e235c5b05d83a4e5709f349839');assert.equal(manifest.files.length,13);for(const file of manifest.files){const raw=fs.readFileSync(path.join(root,'tests/fixtures/delivery-dispatch-recovery',file.file));assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),file.sha256);const archive=JSON.parse(raw);assert.equal(archive.sourceCandidate,manifest.sourceCandidate);assert.deepEqual(archive.sourceHashes,file.sourceHashes);assert.doesNotMatch(raw.toString(),/"(?:cookie|authorization|set-cookie|password|access_token)"\s*:/i);}});
