// Synthetic localhost only: no formal database, credentials or network forwarding.
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=process.env.ERP_UI_ARTIFACT_DIR||path.join(require('os').tmpdir(),'erp-group-location');fs.mkdirSync(out,{recursive:true});
let product={id:7,customer_id:1,version:2,product_code:'P007',product_name:'隔离测试纸箱',box_type:'普通箱',material_id:3,material_code:'R4',layer_count:3,flute_type:'B',length_mm:100,width_mm:100,height_mm:100,report_width_mm:100,report_length_mm:200,production_notes:'测试说明',sale_unit_price:'99',common_box_readiness:{ready:false,missing_fields:['材质']},drawings:[]};
const pallet={contract_version:'standard-pallet-v1',width_mm:1200,depth_mm:1000,height_mm:150};
const lot={lot_id:18,version:4,product_id:7,customer_id:1,inventory_type:'finished',inventory_code:'P007',product_name:'隔离测试纸箱',customer_name:'隔离客户',customer_short_name:'测试',quantity:29,physical_quantity:29,available_quantity:29,unit:'个',lot_number:'FG-TEST',status:'active',specification:'100×100×100'};
const location={location_id:92,location_code:'A2',location_name:'三楼 A2货架 2层1格',employee_location_name:'三楼 A2货架 2层1格',floor_code:'3F',area_code:'A',map_rack_id:'rack-1',map_feature_id:'zone-1',address_kind:'rack_slot',level_no:2,slot_no:1,source_version:'CURRENT_MAP',warehouse_type:'finished',storage_type:'rack',is_active:true,occupancy_status:'occupied',position_status:'mapped',map_position:{left_pct:20,top_pct:20,width_pct:6,height_pct:8,version:1,z_index:1,source_type:'manual',layout_kind:'logical_anchor'},loose_items:[lot],pallet:null,pallets:[]};
const rack={id:'rack-1',layout_id:'fixture',rack_code:'A2',name:'A2',x_mm:4000,y_mm:3000,z_mm:0,width_mm:3000,depth_mm:1000,height_mm:3000,levels:3,level_heights_mm:[1000,1000,1000],level_cell_counts:[2,2,2],cargo_rows:1,bays:2,rotation_deg:0,color:'#466875',access_side:'south',min_aisle_width_mm:1000,source:'manual',status:'confirmed',version:1};
const zone={id:'zone-1',layout_id:'fixture',feature_code:'A',name:'A区',feature_kind:'zone',subtype:'warehouse',points:[[1000,1000],[14000,1000],[14000,9000],[1000,9000]],storage_mode:'rack',elevation_mm:0,storage_height_mm:3000,color:'#dcf4e6',area_mm2:104000000,source:'manual',status:'confirmed',version:1,erp_area_code:'A',formal_binding_status:'bound',formal_policy_status:'published',formal_construction_status:'enabled',capacity_eligible:true};
const layout={layout_id:'fixture',name:'隔离仓库',floor_code:'3F',source_name:'synthetic',source_units:'mm',bounds_mm:{min_x:0,min_y:0,max_x:20000,max_y:12000,width:20000,height:12000},structures:[],features:[zone],placements:[],racks:[rack],assets:[],revision:'fixture-1',standard_pallet:pallet,projection_notice:'',alignment_status:'aligned',alignment_applied:true};
const dashboard={generated_at:'2026-09-12T15:00:00+08:00',read_only:true,standard_pallet:pallet,scope:{notice:''},summary:{active_lots:1,occupied_pallets:0,long_age_lots:0,unlocated_lots:0},floors:[{floor_code:'3F',occupied_locations:1,active_lots:1}],locations:[location,{...location,location_id:93,slot_no:2,location_name:'三楼 A2货架 2层2格',employee_location_name:'三楼 A2货架 2层2格',occupancy_status:'empty',loose_items:[]}],unlocated_inventory:[],distribution:{areas:[]}};
const html=fs.readFileSync(root+'/static/index.html','utf8').replace('        async mounted() {','        async fixtureDisabledMounted() {').replace('app.mount("#app");','window.erpFixture=app.mount("#app");');
const requests=[];const posts=[];const placement={id:'lot:18',inventory_lot_id:18,inventory_version:4,warehouse_location_id:92,warehouse_location_name:'三楼 A2货架 2层1格',product_code:'P007',product_name:'隔离测试纸箱',quantity:29,movable_quantity:29,can_place:true,output_unit:'个',receipt_placement:{label:'待归位',color:'orange'}};
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');requests.push([req.method,u.pathname]);
 if(u.pathname.startsWith('/api/warehouse/goods/')){res.statusCode=503;res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({detail:'隔离数量验证未加载库存资料编辑器'}));}
 if(u.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json');let body={items:[],total:0,counts:{},permissions:[]};
  if(req.method==='POST'){let chunks='';req.on('data',b=>chunks+=b);req.on('end',()=>{posts.push({url:u.pathname,payload:JSON.parse(chunks)});if(u.pathname.endsWith('/move-batches')&&posts.filter(p=>p.url.endsWith('/move-batches')).length===1){res.statusCode=503;res.end(JSON.stringify({detail:'模拟响应中断'}));}else{res.end(JSON.stringify({ok:true}));}});return;}
  if(u.pathname==='/api/warehouse/lots/18')body={id:18,quantity_available:29,quantity_reserved:0,quantity_damaged:0,location:{id:92,warehouse_floor:3}};
  if(u.pathname==='/api/production/placement-stock')body={items:[placement],total:100,pending_total:1};
  if(u.pathname==='/api/production/completions')body={items:[{...placement,status:'posted',origin:'manual',current_inventory_quantity:29,current_inventory_locations:[{inventory_lot_id:18,current_inventory_status:'located',current_warehouse_location_id:92,current_warehouse_location_name:placement.warehouse_location_name,current_inventory_quantity:29}]}],total:100};
  if(u.pathname==='/api/production/temporary-locations')body={items:[92,93].map(id=>({id,warehouse_floor:3,area_id:9,area_code:'EDIT-050',area_master_name:'南A2',map_rack_id:'rack-1',rack_code:'A',rack_display_name:'L001',storage_type:'rack',level_no:2,slot_no:id===92?1:2,location_name:'三楼 A2货架 2层'+(id===92?1:2)+'格',is_empty:id===93,layout_version:1}))};
  if(u.pathname==='/api/master/products/7'){if(req.method==='PUT')product={...product,common_box_readiness:{ready:true}};body=product;}
  if(u.pathname==='/api/warehouse/location-candidates')body={items:dashboard.locations.map(l=>({id:l.location_id,location_code:l.location_code,location_name:l.location_name,warehouse_floor:3,floor_code:'3F',area_code:'A',storage_type:'rack',is_empty:l.location_id===93}))};
  if(u.pathname==='/api/auth/me')body={user:{id:1,role:'admin',ui_mode:'standard'},permissions:['warehouse.view','warehouse.execute','warehouse.correct','warehouse.stocktake.submit']};
  if(u.pathname==='/api/warehouse/twin-dashboard/overview')body=dashboard;
  if(u.pathname==='/api/warehouse/twin-operations/product-quantities/18')body={items:[],total_quantity:29,reserved_quantity:0,order_totals:[],orders:[]};
  if(u.pathname.startsWith('/api/warehouse/twin-layout/floors/'))body=layout;
  if(u.pathname==='/api/orders/cost-preview')body={cost_status:'calculated',estimated_cost:'1.2'};
  return res.end(JSON.stringify(body));
 }
 if(u.pathname==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(html);}
 let relative=u.pathname;if(relative==='/warehouse.html')relative='/static/factory-twin-assets/warehouse-twin.html';if(relative.startsWith('/factory-twin-assets/'))relative='/static'+relative;
 const file=path.resolve(root,'.'+decodeURIComponent(relative));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||!fs.statSync(file).isFile()){res.statusCode=404;return res.end();}
 res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html; charset=utf-8':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream');res.end(fs.readFileSync(file));
});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
 try{const page=await browser.newPage({viewport:{width:1440,height:900}});page.on('pageerror',e=>errors.push(e.stack || e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>!!window.erpFixture);
 await page.evaluate(p=>{const a=window.erpFixture;a.user={id:1,role:'admin',permissions:['*']};a.hasPermission=()=>true;a.pageAllowed=()=>true;a.activePage='production';a.productionTab='history';a.authGeneration=1;a.pages.productionHistory=2;a.productionHistoryFilters.product_code='P007';a.productionHistory=[{...p,status:'posted',origin:'manual',current_inventory_quantity:29,current_inventory_locations:[{inventory_lot_id:18,current_inventory_status:'located',current_warehouse_location_id:92,current_warehouse_location_name:p.warehouse_location_name,current_inventory_quantity:29}]}];},placement);
 await page.waitForTimeout(800);await page.waitForFunction(()=>!window.erpFixture.productionHistoryLoading);await page.evaluate(async()=>{const a=window.erpFixture;await a.loadProductionHistory();a.productionHistoryTotal=100;a.pages.productionHistory=2;await a.$nextTick();});
 await page.getByRole('button',{name:placement.warehouse_location_name,exact:true}).click();
 const frame=page.frameLocator('iframe[title="生产仓库地图"]');await frame.getByRole('button',{name:'移动当前产品',exact:true}).waitFor();
 assert.equal(await page.evaluate(()=>window.erpFixture.productionTab),'history');assert.equal(await frame.locator('.twin-top-ledger').count(),0);
 await page.screenshot({path:out+'/history-focused-rack.png'});
 await frame.getByRole('button',{name:'移动当前产品',exact:true}).click();await frame.getByText('已选单个产品，可选择空货位或已有货物的货位。数量默认全部，可修改。',{exact:true}).waitFor();
 await page.locator('.production-map-mask>header').getByRole('button',{name:'返回原生产页面',exact:true}).click();await page.waitForFunction(()=>!window.erpFixture.productionMap);
 assert.deepEqual(await page.evaluate(()=>({page:window.erpFixture.activePage,tab:window.erpFixture.productionTab,num:window.erpFixture.pages.productionHistory,q:window.erpFixture.productionHistoryFilters.product_code})),{page:'production',tab:'history',num:2,q:'P007'});assert.equal(posts.length,0,'Opening and choosing move source does not save');
 await page.evaluate(p=>{const a=window.erpFixture;a.productionTab='placement';a.productionPlacement=[p];a.productionPlacementState='all';a.pages.productionPlacement=2;},placement);
 await page.waitForTimeout(500);await page.evaluate(()=>{window.erpFixture.productionPlacementTotal=100;window.erpFixture.pages.productionPlacement=2;});
 await page.getByRole('button',{name:'地图选位归位',exact:true}).click();await frame.getByRole('button',{name:'确定此货位',exact:true}).waitFor();
 await frame.getByRole('button',{name:'三楼 A2货架 2层2格：查看货位',exact:true}).last().click();await frame.getByRole('button',{name:'确定此货位',exact:true}).click();await page.waitForFunction(()=>window.erpFixture.productionMap?.target?.id===93);assert.equal(posts.length,0);
 await page.screenshot({path:out+'/map-placement-ready.png'});
 await frame.getByRole('button',{name:'三楼 A2货架 2层1格：查看货位',exact:true}).last().click();await page.waitForFunction(()=>window.erpFixture.productionMap?.target===null);assert(await page.locator('.production-map-mask>footer').getByRole('button',{name:'确认归位',exact:true}).isDisabled());
 await page.locator('.production-map-mask>header').getByRole('button',{name:'返回原生产页面',exact:true}).click();await page.waitForFunction(()=>!window.erpFixture.productionMap);assert.equal(posts.length,0,'Cancel after selecting must not write');
 await page.getByRole('button',{name:'地图选位归位',exact:true}).click();await frame.getByRole('button',{name:'确定此货位',exact:true}).waitFor();await frame.getByRole('button',{name:'三楼 A2货架 2层2格：查看货位',exact:true}).last().click();await frame.getByRole('button',{name:'确定此货位',exact:true}).click();await page.waitForFunction(()=>window.erpFixture.productionMap?.target?.id===93);
 await page.locator('.production-map-mask>footer').getByRole('button',{name:'确认归位',exact:true}).click();await page.waitForFunction(()=>!window.erpFixture.productionMap);
 assert.equal(posts.length,1);assert.equal(posts[0].url,'/api/production/placement-stock/18/transfer');assert.deepEqual({...posts[0].payload,idempotency_key:'key'},{idempotency_key:'key',expected_version:4,quantity:29,location_id:93,expected_layout_version:1});
 assert.equal(await page.evaluate(()=>window.erpFixture.productionTab),'placement');assert.equal(await page.evaluate(()=>window.erpFixture.pages.productionPlacement),2);assert.deepEqual(errors,[]);
 await page.getByRole('button',{name:placement.warehouse_location_name+' ↗',exact:true}).click();await frame.getByRole('button',{name:'移动当前产品',exact:true}).waitFor();await frame.getByRole('button',{name:'移动当前产品',exact:true}).click();
 await frame.locator('.twin-move-target-cascade select').nth(1).selectOption('A');await frame.locator('.twin-target-picker summary').click();await frame.locator('.twin-move-target-list button').filter({hasText:'2层2格'}).click();await frame.getByRole('button',{name:'确认移动',exact:true}).click();await frame.getByText(/整批提交失败：模拟响应中断/).waitFor();
 await page.locator('.production-map-mask>header').getByRole('button',{name:'返回原生产页面',exact:true}).click();await frame.getByText('移货结果尚未确定，请用当前保留的移货记录重试核对，再返回生产页面。',{exact:true}).waitFor();assert(await page.evaluate(()=>!!window.erpFixture.productionMap));
 await frame.getByRole('button',{name:'清空列表',exact:true}).click();await frame.getByRole('button',{name:'提交 1 条移货',exact:true}).click();await frame.getByText('移动完成；地图已刷新。',{exact:true}).waitFor();
 assert.equal(posts.length,3);assert.deepEqual(posts[1],posts[2],'uncertain retry preserves the exact idempotent payload');assert.equal(posts[1].payload.items[0].lot_id,18);assert.equal(posts[1].payload.items[0].target_location_id,93);
 await page.locator('.production-map-mask>header').getByRole('button',{name:'返回原生产页面',exact:true}).click();await page.waitForFunction(()=>!window.erpFixture.productionMap);assert.equal(await page.evaluate(()=>window.erpFixture.productionTab),'placement');assert.equal(await page.evaluate(()=>window.erpFixture.pages.productionPlacement),2);
 const quantityPage=await browser.newPage({viewport:{width:1440,height:900}});quantityPage.on('pageerror',e=>errors.push(e.stack || e.message));
 const searchItem={...lot,product_identity_key:'quantity-test',quantity:120,available_quantity:80,reserved_quantity:40,location_id:92,location_name:'三楼 A2货架 2层1格',floor_code:'3F',area_code:'A',position_status:'mapped',pallet_id:null};
 let quantityReads=0;
 await quantityPage.route('**/api/warehouse/twin-operations/locate?**',route=>route.fulfill({json:{items:[searchItem],resources:[],floor_summaries:[],result_count:1,inventory_result_count:1,pagination:{has_more:true,next_after_lot_id:18,counts_scope:'page'}}}));
 await quantityPage.route('**/api/warehouse/twin-operations/product-quantities/18',route=>{quantityReads++;return route.fulfill({json:{items:[searchItem,{...searchItem,lot_id:19,location_id:93,location_name:'三楼 A2货架 2层2格',quantity:80,available_quantity:20,reserved_quantity:60}],total_quantity:200,reserved_quantity:100,order_totals:[{unit:'个',ordered_quantity:100,delivered_quantity:0,remaining_quantity:100}],orders:[{order_item_id:1,order_number:'YL-TEST',unit:'个',ordered_quantity:100,remaining_quantity:100}]}});});
 await quantityPage.goto('http://127.0.0.1:'+server.address().port+'/warehouse.html');
 await quantityPage.getByRole('textbox',{name:'全仓查货',exact:true}).fill('P007');
 const productButton=quantityPage.locator('.twin-search-result-list button').filter({hasText:'P007'}).first();
 await productButton.waitFor();assert.equal(quantityReads,0,'Searching alone must not enable quantity overlays');
 await productButton.click();const summary=quantityPage.getByRole('region',{name:'所选产品全仓数量'});
 await summary.getByText(/全仓实存 200/).waitFor();await summary.getByText(/有效订单订购 100/).waitFor();
 assert.equal(await quantityPage.getByLabel('所选产品货位数量').count(),2);await summary.locator('summary').filter({hasText:'各栈板'}).click();assert.equal(await summary.getByRole('button').count(),2);
 await quantityPage.screenshot({path:out+'/product-actual-200-order-100.png'});
 await quantityPage.getByRole('textbox',{name:'全仓查货',exact:true}).fill('');await summary.waitFor({state:'detached'});assert.equal(await quantityPage.getByLabel('所选产品货位数量').count(),0);
 assert.deepEqual(errors,[]);await quantityPage.close();
 fs.writeFileSync(out+'/result.json',JSON.stringify({ok:true,errors,posts,requests},null,2));console.log('PASS Chrome: rack focus, move source, preserved history context, map selection, cancellation, one placement, map move and uncertain same-key retry with CAS/layout/idempotency');
 }catch(e){const p=browser.contexts()[0]?.pages()[0];if(p)await p.screenshot({path:out+'/failure.png'});fs.writeFileSync(out+'/error.json',JSON.stringify({message:e.message,errors,posts,requests},null,2));throw e;}finally{await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
