const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {parseHTML}=require('linkedom');
const code=fs.readFileSync(require.resolve('../../static/ui/product-workbench.js'),'utf8'),html=fs.readFileSync(process.env.PRODUCT_ACTION_HTML||require.resolve('../../static/index.html'),'utf8');
const tick=()=>new Promise(r=>setImmediate(r)),deferred=()=>{let resolve,reject;const promise=new Promise((r,j)=>{resolve=r;reject=j});return {promise,resolve,reject}};
const stocks=()=>({summary:Object.fromEntries(['finished','semi_finished','processed_component'].map(k=>[k,{actual:0,available:0,reserved:0,unit:'张'}])),groups:Object.fromEntries(['finished','semi_finished','processed_component'].map(k=>[k,{positions:[]}]))});
const detail=(id=1,policy=null)=>({product:{id,product_id:id,customer_id:7,customer_name:'合成客户',product_code:'TEST-'+id,drawings:{status:'none',items:[]}},production:{molds:[],bom:[],process_steps:[]},inventory:{...stocks(),items:[]},orders:{items:[{order_id:71,product_id:id,order_number:'SYNTHETIC-71'}]},actions:{can_requisition:true,stock_only:false,policy_id:policy}});
function harness(read=async()=>({data:{items:[]}})){
 const {window}=parseHTML('<html><body><div id="root"></div></body></html>');let mixin,next=0,logout=0;const timers=new Map(),requests=[],nav=[],forms=[];
 const transport=async(p,o)=>{requests.push({p,o,local:true});return read(p,o)};
 const box={window:null,document:window.document,location:{search:'',href:''},AbortController,URLSearchParams,console,latestRequestControllers:new Map(),createIdempotencyKey:()=> 'test-key-'+(++next),setTimeout:(fn,ms)=>{timers.set(++next,{fn,ms});return next},clearTimeout:id=>timers.delete(id),erpAuthRequired:()=>{logout++},erpForbidden:()=>{},erpCheckingSession:false,FormData:class{constructor(f){this.f=f}get(k){return this.f.querySelector(`[name="${k}"]`)?.value||null}}};box.window=box;
 box.axios={defaults:{withCredentials:true},create:opts=>({get:transport}),get:async(p,o)=>{try{requests.push({p,o,local:false});return await read(p,o)}catch(e){if(e.response?.status===401)logout++;throw e}}};
 vm.createContext(box);vm.runInContext(code,box);box.ERPProductWorkbench.install({mixin:m=>mixin=m,component(){},_component:{methods:{openLowStockLocations(){}}}});
 function actual(name){const re=new RegExp('^          (?:async )?'+name+'\\([^\\n]*\\) \\{','m'),m=html.match(re);assert.ok(m,name);const end=html.indexOf('\n          },',m.index);return vm.runInContext('({'+html.slice(m.index,end+13).trim().replace(/,$/,'')+'})',box)[name]}
 const c={user:{id:1},authGeneration:1,activePage:'dashboard',canRequisition:true,customerOptions:[{id:7}],allMaterials:[{}],stockPolicyWarnings:[],stockReplenishmentProducts:[],stockReplenishmentCompanions:[],stockReplenishmentForm:{idempotency_key:'original',items:[]},stockReplenishmentSaveState:{uncertain:true},stockPolicyDraftQuantities:{},modal:null,toasts:[],homeEntry:null,productWorkbenchState:null,beginLatestRequest:actual('beginLatestRequest'),finishLatestRequest:actual('finishLatestRequest'),cancelLatestRequest:actual('cancelLatestRequest'),isCancelledRequest:actual('isCancelledRequest'),pageAllowed:()=>true,checkWarehouseNavigation:async()=>true,resetSingleScreenExpansion(){},syncDesktopWorkspaceUrl(){},cancelSupplierRequisitionPreview(){},cancelCustomerHeatOrderRequests(){},cancelQueuedPageSearch(){},leaveWarehouseWorkspaceUrl(){},loadPage:async p=>nav.push(p),showToast(...v){this.toasts.push(v)},errorMessage:e=>e.message,loadCustomerOptions:async()=>{},loadMaterials:async()=>{},addBlankStockReplenishmentLine(){this.stockReplenishmentForm.items.push({});forms.push(this.stockReplenishmentForm)},applyStockProduct(line){line.applied=true},syncStockReplenishmentSupplier(){},hasPermission:()=>false,rememberModalOpener:()=>null,cancelOrderTraceChildRequests(){},displayOrderNumber:d=>d.order_number,focusAccessibleModal(){},...mixin.methods};
 for(const name of ['go','openStockReplenishment','loadStockProducts','addStockPolicyDraft','openOrderDetail','loadOrderCustomerCharges'])c[name]=actual(name);
 return {box,c,timers,requests,nav,forms,logout:()=>logout,actual,root:window.document.getElementById('root'),window};
}
function mount(h,onAction=(kind,data,action)=>h.c.productWorkbenchAction(kind,data,action),policy=null){const instance=h.box.ERPProductWorkbench.mount({container:h.root,request:async p=>detail(p.includes('/2')?2:1,policy),onAction});return instance;}
function click(h,s){const e=h.root.querySelector(s);assert.ok(e,s);e.dispatchEvent(new h.window.Event('click',{bubbles:true}));}
async function start(h,instance){await instance.show(1);click(h,'[data-requisition]');click(h,'[data-purpose="stock"]');await tick();}
test('normal action handoff survives actual go unmount and creates only one intended draft line',async()=>{const h=harness(async p=>({data:p.includes('/products')?{items:[{id:1}]}:{items:[]}})),instance=mount(h);h.c.loadPage=async p=>{h.nav.push(p);instance.destroy()};await start(h,instance);await tick();assert.equal(h.c.activePage,'requisition');assert.equal(h.c.modal?.type,'stockReplenishment');assert.equal(h.c.stockReplenishmentForm.items.length,1);assert.equal(h.c.stockReplenishmentForm.items[0].reference_product_id,1);assert.equal(h.requests.some(r=>r.o?.method==='POST'),false)});
test('actual component double click stays one action and old product error cannot pollute B',async()=>{const wait=deferred(),h=harness();let calls=0;const instance=mount(h,async()=>{calls++;await wait.promise});await start(h,instance);click(h,'[data-requisition]');click(h,'[data-purpose="stock"]');assert.equal(calls,1);await instance.show(2);wait.reject(Error('A failed'));await tick();assert.doesNotMatch(h.root.textContent,/A failed/);instance.destroy()});
test('actor change while go loads cannot reset B form or open old draft',async()=>{const wait=deferred(),h=harness();h.c.loadPage=()=>wait.promise;const p=h.c.productWorkbenchAction('requisition',detail());await tick();const b={idempotency_key:'B',items:[{quantity:99}]};h.c.user={id:2};h.c.authGeneration=2;h.c.stockReplenishmentForm=b;h.c.modal={type:'B'};wait.resolve();await p;assert.equal(h.c.stockReplenishmentForm,b);assert.equal(h.c.modal.type,'B')});
test('actual go pending warehouse permission cannot return user from new page to old action target',async()=>{const wait=deferred(),h=harness();h.c.activePage='warehouse';h.c.checkWarehouseNavigation=()=>wait.promise;const p=h.c.productWorkbenchAction('requisition',detail());await tick();h.c.activePage='dashboard';await h.c.go('home');wait.resolve(true);await p;assert.equal(h.c.activePage,'home');assert.equal(h.c.modal,null)});
test('same target manual navigation cancels handoff and refused navigation never opens draft',async()=>{for(const allowed of [true,false]){const wait=deferred(),h=harness();h.c.pageAllowed=()=>allowed;h.c.loadPage=()=>wait.promise;const p=h.c.productWorkbenchAction('requisition',detail());await tick();if(allowed){h.c.loadPage=async()=>{};await h.c.go('requisition')}wait.resolve();await p;assert.equal(h.c.modal,null)}});
test('ignored abort bootstrap does not replace policy list of another form',async()=>{const wait=deferred(),h=harness(()=>wait.promise);const p=h.c.productWorkbenchAction('requisition',detail());await tick();h.c.stockReplenishmentForm={idempotency_key:'B',items:[]};h.c.modal={type:'stockReplenishment'};h.c.stockPolicyWarnings=[{id:22}];wait.resolve({data:{items:[{id:11}]}});await p;assert.equal(h.c.stockPolicyWarnings[0].id,22)});
test('late local 401 cannot log out new account while current 401 is still handled',async()=>{for(const stale of [true,false]){const wait=deferred(),h=harness(()=>wait.promise);const p=h.c.productWorkbenchAction('requisition',detail());await tick();if(stale){h.c.user={id:2};h.c.authGeneration=2}wait.reject(Object.assign(Error('session lost'),{response:{status:401,data:{detail:'login'}}}));await p.catch(()=>{});assert.equal(h.logout(),stale?0:1);assert.equal(h.requests[0].local,true)}});
test('finite action deadline releases busy, rejects late response and permits fresh retry',async()=>{const wait=deferred(),h=harness(()=>wait.promise),instance=mount(h);await start(h,instance);const timer=[...h.timers.values()].find(v=>v.ms>0&&v.ms<=60000);if(!timer){wait.resolve({data:{items:[]}});await tick();instance.destroy();assert.fail('action deadline required')}timer.fn();await tick();assert.equal(h.c.stockReplenishmentForm.items.length,0);wait.resolve({data:{items:[{id:1}]}});await tick();assert.equal(h.c.stockReplenishmentForm.items.length,0);assert.equal(h.root.querySelector('[data-requisition]')?.hasAttribute('disabled')||false,false);await start(h,instance);await tick();assert.equal(h.c.stockReplenishmentForm.items.length,1);instance.destroy()});
test('normal order handoff opens actual read-only detail with a local request',async()=>{const h=harness(async p=>({data:{id:71,order_number:'SYNTHETIC-71'}})),instance=mount(h);h.c.loadPage=async()=>instance.destroy();await instance.show(1);click(h,'[data-tab="orders"]');click(h,'[data-order="0"]');await tick();assert.equal(h.c.activePage,'orders');assert.equal(h.c.modal?.type,'orderDetail');assert.equal(h.c.orderDetail.id,71);assert.equal(h.requests[0].local,true)});
test('actual synchronous axios interceptor only affects the captured current session including anonymous bootstrap',async()=>{
 const source=html.slice(html.indexOf('      axios.defaults.withCredentials = true;'),html.indexOf('      const { createApp } = Vue;'));
 let request,response,options,identity,logout=0,forbidden=0,repair=0;
 const sandbox={window:null,Promise,axios:{defaults:{},interceptors:{request:{use(f,e,o){request=f;options=o}},response:{use(f,e){response=e}}}},erpAuthRequired:()=>logout++,erpForbidden:()=>forbidden++,TMEntryProduct:{offerRepair:()=>repair++}};sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(source,sandbox);
 assert.equal(typeof request,'function');assert.equal(options.synchronous,true);
 const initial=request({url:'/anonymous'});sandbox.erpRequestIdentity=()=>identity;identity={actor:1,generation:1};
 const reject=async(config,status)=>{const e={config,response:{status,data:{detail:'test'}}};await assert.rejects(response(e));};
 await reject(initial,401);assert.equal(logout,0);
 const a=request({url:'/A'});identity={actor:2,generation:2};await reject(a,401);await reject(a,403);assert.equal(logout,0);assert.equal(forbidden,0);assert.equal(repair,0);
 const b=request({url:'/B'});await reject(b,401);await reject(b,403);assert.equal(logout,1);assert.equal(forbidden,1);assert.equal(repair,2);
});
test('policy draft continuation after its product load cannot touch a replacement form',async()=>{
 const wait=deferred();const h=harness(async p=>p.includes('/replenishment-draft')?{data:{items:[{stock_policy_id:31,quantity:8,customer_id:7}],draft_ready:true}}:p.includes('/products')?wait.promise:{data:{items:[]}});
 let synced=0;h.c.syncStockReplenishmentSupplier=()=>synced++;
 const p=h.c.productWorkbenchAction('requisition',detail(1,31));await tick();const b={idempotency_key:'B-policy',items:[]};h.c.stockReplenishmentForm=b;h.c.modal={type:'stockReplenishment'};wait.resolve({data:{items:[{id:1}]}});await p;
 assert.equal(h.c.stockReplenishmentForm,b);assert.equal(h.c.stockReplenishmentProducts.length,0);assert.equal(synced,0);assert.equal(h.c.toasts.length,0);
});
test('normal policy handoff uses the original draft then current products without business POST',async()=>{
 const h=harness(async p=>({data:p.includes('/replenishment-draft')?{items:[{stock_policy_id:31,quantity:8,customer_id:7,reference_product_id:1}],draft_ready:true}:p.includes('/products')?{items:[{id:1}]}:{items:[]}}));
 const instance=mount(h,undefined,31);h.c.loadPage=async()=>instance.destroy();await start(h,instance);await tick();assert.equal(h.c.stockReplenishmentForm.items.length,1);assert.equal(h.c.stockReplenishmentForm.items[0].stock_policy_id,31);assert.equal(h.c.stockReplenishmentForm.items[0].quantity,8);assert.equal(h.requests.every(r=>r.local),true);
});
test('same actor replaces form while go is pending so old opening cannot reset it',async()=>{const wait=deferred(),h=harness();h.c.loadPage=()=>wait.promise;const p=h.c.productWorkbenchAction('requisition',detail());await tick();const b={idempotency_key:'B-before-open',items:[{quantity:99}]};h.c.stockReplenishmentForm=b;h.c.modal={type:'stockReplenishment'};wait.resolve();await p;assert.equal(h.c.stockReplenishmentForm,b)});
test('actual customer and material selectors in cold bootstrap use local context and original pagination',async()=>{
 const h=harness(async p=>({data:p.includes('/customers')?{items:[{id:7}],total_pages:1,page:1}:p.includes('/materials')?{items:[{id:81}],total:1}:p.includes('/products')?{items:[{id:1}]}:{items:[]}}));
 h.c.customerOptions=[];h.c.customerOptionsIdentity='';h.c.allMaterials=[];h.c.materialSort='common';h.c.activeSupplierNames=[];h.c.hasPermission=p=>p==='customers.view';
 h.c.loadCustomerOptions=h.actual('loadCustomerOptions');h.c.loadMaterials=h.actual('loadMaterials');h.c.fetchAllMaterials=h.actual('fetchAllMaterials');
 await h.c.productWorkbenchAction('requisition',detail());assert.equal(h.c.customerOptions[0].id,7);assert.equal(h.c.allMaterials[0].id,81);assert.equal(h.c.stockReplenishmentForm.items.length,1);assert.equal(h.requests.every(r=>r.local),true);assert.equal(h.requests.find(r=>r.p.includes('/materials')).o.params.page_size,200);
});
test('order charge late reply cannot replace a newer modal on the same target page',async()=>{
 const wait=deferred(),h=harness(async p=>p.includes('/customer-charges')?wait.promise:{data:{id:71,order_number:'SYNTHETIC-71'}});h.c.hasPermission=p=>p==='finance.view';h.c.orderCustomerCharges=[{id:81}];
 const p=h.c.productWorkbenchAction('order',{order_id:71});await tick();const newer={type:'newer'};h.c.modal=newer;wait.resolve({data:{items:[{id:17}]}});await p;assert.equal(h.c.modal,newer);assert.equal(h.c.orderCustomerCharges[0].id,81);
});
test('actual mobile onOrder callback scrolls only while its account page and origin are current',async()=>{
 const mobileHtml=fs.readFileSync(require.resolve('../../static/mobile_erp.html'),'utf8');const entry=mobileHtml.match(/window\.ERPProductWorkbench\?\.mountMobile\(\{container:byId\('productWorkbench'\),userId:user\.id,onOrder:async[\s\S]*?\n\s*\}\}\);/)[0];
 for(const stale of [false,true]){const h=harness(),wait=deferred();let scrolls=0;h.root.id='productWorkbench';for(const id of ['lookupInput','lookupCategory','lookupUnfulfilled','lookupResults']){const e=h.box.document.createElement('input');e.id=id;if(id==='lookupResults')e.scrollIntoView=()=>scrolls++;h.box.document.body.append(e)}
 h.box.byId=id=>h.box.document.getElementById(id);h.box.user={id:1};h.box.state={activePage:'lookup',shell:{user:{id:1}}};h.box.runUnifiedSearch=()=>wait.promise;h.box.fetch=async p=>({ok:true,json:async()=>p.includes('/products/')?detail():{items:[detail().product],total:1,page:1,page_size:12,has_more:false}});
 vm.runInContext(entry,h.box);h.root.querySelector('[name=q]').value='TEST';h.root.querySelector('form').dispatchEvent(new h.window.Event('submit',{cancelable:true}));await tick();click(h,'[data-product]');await tick();click(h,'[data-tab="orders"]');click(h,'[data-order="0"]');await tick();if(stale){h.box.user={id:2};h.box.state.activePage='home';h.box.state.shell.user.id=2;h.box.ERPProductWorkbench.destroyMobile()}wait.resolve();await tick();assert.equal(scrolls,stale?0:1);h.box.ERPProductWorkbench.destroyMobile();}
});
test('actual go handoff after component unmount shows a current failure once in the root',async()=>{
 const h=harness(async()=>({data:{items:[]}})),instance=mount(h);h.c.loadPage=async()=>instance.destroy();await start(h,instance);await tick();assert.equal(h.c.activePage,'requisition');assert.equal(h.root.textContent,'');assert.equal(h.c.toasts.length,1);assert.match(h.c.toasts[0][0],/此产品当前不能生成报料草稿/);assert.match(h.c.toasts[0][0],/重新打开/);
});
test('current permission refusal never fills an old form even if an old stock modal remains',async()=>{const h=harness(),old=h.c.stockReplenishmentForm;h.c.modal={type:'stockReplenishment'};h.c.canRequisition=false;await h.c.productWorkbenchAction('requisition',detail());assert.equal(h.c.stockReplenishmentForm,old);assert.equal(old.items.length,0);assert.equal(h.requests.length,0)});

// Merge611: execute both formal target-first loading and action-owned continuations.
test('merge611 actual home warning entry reads target before options then loads original page',async()=>{
 const target=deferred(),options=deferred(),h=harness(async p=>p.endsWith('/replenishment-draft')?target.promise:{data:{items:[]}});
 h.c.openLowStockReplenishment=h.actual('openLowStockReplenishment');h.c.stockPolicyDraftQuantity=h.actual('stockPolicyDraftQuantity');h.c.validateStockReplenishmentForm=h.actual('validateStockReplenishmentForm');h.c.canSubmitBusinessRequest=false;h.c.allMaterials=[];h.c.loadMaterials=()=>options.promise;
 const p=h.c.openLowStockReplenishment({policy_id:31,suggested_new_requisition_sheet_quantity:8});await tick();const original=h.c.stockReplenishmentForm;
 assert.deepEqual(h.nav,[]);assert.equal(h.requests.length,1);assert.match(h.requests[0].p,/31\/replenishment-draft$/);assert.equal(original._pendingDrafts,1);assert.match(h.c.validateStockReplenishmentForm(),/正在读取/);
 target.resolve({data:{items:[{stock_policy_id:31,quantity:8}],draft_ready:true}});await tick();assert.equal(original.items[0].quantity,8);assert.equal(original._pendingDrafts,0);assert.deepEqual(h.nav,[]);assert.equal(h.requests.some(r=>r.p==='/api/requisition/stock-policies'),false);
 options.resolve();await p;assert.deepEqual(h.nav,['requisition']);
});
test('merge611 bootstrap target policy forwards exact current context and handles null warnings',async()=>{
 const h=harness();let used=0;const context={current:()=>true,bind(){},async get(p){used++;return {data:{items:[],draft_ready:true}}}};
 await h.c.openStockReplenishment({warningOnly:true,policy:{id:31},productAction:context});assert.equal(used,1);assert.equal(h.requests.length,0);assert.equal(h.c.stockReplenishmentForm._pendingDrafts,0);assert.equal(h.c.stockReplenishmentForm.items.length,0);
});
for(const change of ['close-reopen','account'])test('merge611 pending belongs to original form after '+change,async()=>{
 const target=deferred(),h=harness(()=>target.promise);const p=h.c.openStockReplenishment({warningOnly:true,policy:{id:31}});await tick();const original=h.c.stockReplenishmentForm;assert.equal(original._pendingDrafts,1);
 if(change==='close-reopen'){h.c.modal=null;await h.c.openStockReplenishment({warningOnly:true});}else{h.c.user={id:2};h.c.authGeneration++;h.c.stockReplenishmentForm={items:[],_pendingDrafts:7};h.c.modal={type:'stockReplenishment'};}
 const newer=h.c.stockReplenishmentForm;const pending=newer._pendingDrafts;target.resolve({data:{items:[{stock_policy_id:31,quantity:8,customer_id:7}],draft_ready:true}});await p;
 assert.equal(original._pendingDrafts,0);assert.equal(original.items.length,0);assert.equal(newer._pendingDrafts,pending);assert.equal(newer.items.length,0);assert.equal(h.c.toasts.length,0);
});
test('merge611 empty and failed target clear pending without creating a line',async()=>{
 for(const failed of [false,true]){const h=harness(async()=>{if(failed)throw Error('target unavailable');return {data:{items:[],draft_ready:true}}});await h.c.openStockReplenishment({warningOnly:true,policy:{id:31}});assert.equal(h.c.stockReplenishmentForm._pendingDrafts,0);assert.equal(h.c.stockReplenishmentForm.items.length,0);if(failed)assert.match(h.c.toasts[0][0],/target unavailable/);}
});

test('merge611 home permission wait changing account cannot reopen an old target form',async()=>{
 const allowed=deferred(),h=harness();h.c.activePage='warehouse';h.c.checkWarehouseNavigation=()=>allowed.promise;h.c.openLowStockReplenishment=h.actual('openLowStockReplenishment');h.c.stockPolicyDraftQuantity=h.actual('stockPolicyDraftQuantity');h.c.canSubmitBusinessRequest=false;
 const p=h.c.openLowStockReplenishment({policy_id:31,suggested_new_requisition_sheet_quantity:8});await tick();const b={items:[{quantity:99}],idempotency_key:'B'};h.c.user={id:2};h.c.authGeneration++;h.c.stockReplenishmentForm=b;h.c.modal={type:'B'};allowed.resolve(true);await p;assert.equal(h.c.stockReplenishmentForm,b);assert.equal(h.c.modal.type,'B');assert.equal(h.requests.length,0);
});
