const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const {chromium}=require('playwright');
const root=process.cwd(),out='D:/tm-uat/shelf-label-paper-20260927';
const svg='data:image/svg+xml;base64,'+Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="white"/><path d="M5 5h30v30H5zM65 5h30v30H65zM5 65h30v30H5zM50 50h40v40H50z" fill="black"/></svg>').toString('base64');
const server=http.createServer((req,res)=>{const u=new URL(req.url,'http://localhost');
 if(u.pathname.includes('/mobile-label')){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({title:'三楼 北货架G1',position:'02层-01格',qr_data_url:svg,...(u.searchParams.has('lot_id')?{print_title:'D02-A架',print_position:'02层 01格',print_floor:'三楼',product:{customer:'研光',code:'YL0006',name:'外包装纸箱',specification:'100×200×300'}}:{})}));}
 const file=path.join(root,u.pathname);if(!file.startsWith(root+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':'text/html; charset=utf-8');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage();await page.goto(`http://127.0.0.1:${server.address().port}/static/shelf-label.html?location_ids=1,2,3`);await page.waitForFunction(()=>!document.getElementById('print').disabled);await page.emulateMedia({media:'print'});
 const pageSize=await page.evaluate(()=>[...document.styleSheets].flatMap(s=>[...s.cssRules]).find(r=>r.constructor.name==='CSSPageRule').style.size);assert.equal(pageSize,'40mm 80mm','physical label must match 40x80 printer stock');
 async function verify(){return page.evaluate(()=>[...document.querySelectorAll('.label-page')].map(p=>{const box=p.getBoundingClientRect();const children=[...p.querySelectorAll('h1,strong,img,.value')].map(n=>{const r=n.getBoundingClientRect();return {text:n.textContent||n.alt,visible:r.width>0&&r.height>0,inside:r.left>=box.left-.5&&r.right<=box.right+.5&&r.top>=box.top-.5&&r.bottom<=box.bottom+.5};});return{width:box.width,height:box.height,children};}));}
 let evidence=await verify();assert.equal(evidence.length,3);for(const p of evidence){assert(Math.abs(p.width-40*96/25.4)<1);assert(Math.abs(p.height-80*96/25.4)<1);assert(p.children.every(c=>c.visible&&c.inside),JSON.stringify(p));}
 await page.pdf({path:out+'/rack-labels.pdf',preferCSSPageSize:true,printBackground:true});await page.locator('.label-page').first().screenshot({path:out+'/rack-label.png'});
 await page.goto(`http://127.0.0.1:${server.address().port}/static/shelf-label.html?location_id=1&lot_id=1`);await page.waitForFunction(()=>!document.getElementById('print').disabled);evidence.push(...await verify());assert(evidence.at(-1).children.every(c=>c.visible&&c.inside),JSON.stringify(evidence.at(-1)));await page.pdf({path:out+'/product-label.pdf',preferCSSPageSize:true,printBackground:true});await page.locator('.label-page').screenshot({path:out+'/product-label.png'});
 fs.writeFileSync(out+'/chrome-evidence.json',JSON.stringify(evidence,null,2));console.log('PASS: 40x80 paper, three independent location pages, product text and QR bounds');
 }finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
