const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process');
const {parseHTML}=require('linkedom');
const root=path.resolve(__dirname,'../..'),here=__dirname,html=process.env.BASELINE?cp.execFileSync('git',['show',process.env.BASELINE+':static/index.html'],{cwd:root,encoding:'utf8',maxBuffer:12e6}):fs.readFileSync(path.join(root,'static/index.html'),'utf8');
const {test}=require('node:test');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject}},tick=()=>new Promise(r=>setImmediate(r));
const actualOld={id:1,order_number:'older-shape-only-invalid-new-ack',status:'draft'};
let serial=0;
function storage(){const map=new Map(),calls=[];return {map,calls,getItem(k){calls.push(['get',k]);return map.get(k)||null},setItem(k,v){calls.push(['set',k]);map.set(k,String(v))},removeItem(k){calls.push(['remove',k]);map.delete(k)},key(i){return [...map.keys()][i]??null},get length(){return map.size}}}
function page(store=storage(),response=async()=>({data:structuredClone(actualOld)})){
 const {window}=parseHTML('<html><body></body></html>');const controllers=new Map(),posts=[],gets=[],timers=new Map(),box={window:null,document:window.document,location:{search:'',href:''},AbortController,URLSearchParams,console,Promise,localStorage:store,sessionStorage:store,modalA11ySessionActive:false,blankBomEditor:()=>({}),blankMasterChangeConfirm:()=>({}),createIdempotencyKey:()=>`probe-${++serial}`,latestRequestControllers:controllers,requestAnimationFrame:()=>{},setTimeout:(f,ms)=>{const k=++serial;timers.set(k,{f,ms});return k},clearTimeout:k=>timers.delete(k)};box.window=box;box.open=()=>true;
 box.axios={defaults:{withCredentials:true},post:async(p,b,o)=>{posts.push({p,body:structuredClone(b),options:o||null});return response(p,b,o)},get:async(p,o)=>{gets.push(p);return {data:{items:[]}}}};box.axios.create=()=>box.axios;box.confirm=()=>true;box.TextEncoder=TextEncoder;vm.createContext(box);vm.runInContext(fs.readFileSync(path.join(root,'static/ui/stock-replenishment-save-recovery.js'),'utf8'),box);
 function actual(name){const re=new RegExp('^\\s*(?:async )?'+name+'\\([^\\n]*\\) \\{','m'),m=html.match(re);assert.ok(m,name);const e=html.indexOf('\n          },',m.index);return vm.runInContext('({'+html.slice(m.index,e+13).trim().replace(/,$/,'')+'})',box)[name]}
 const c={user:{id:1},authGeneration:1,canRequisition:true,canSubmitBusinessRequest:false,stockReplenishmentSaveState:{saving:false,committed:false,uncertain:false,result:null},stockReplenishmentSavedNotice:{visible:false,result:null,readError:''},stockReplenishmentForm:{},stockReplenishmentProducts:[],stockReplenishmentCompanions:[],stockPolicyDraftQuantities:{},stockPolicyWarnings:[],customerOptions:[{id:1}],allMaterials:[{id:1}],modal:null,stockReplenishmentRecoveryRecords:[],stockReplenishmentRecoveryError:"",stockReplenishmentRecoveryBusy:"",stockReplenishmentRecoveryEpoch:0,pages:{},activePage:'requisition',requisitionWorkspace:'board',requisitionTab:'submitted',toasts:[],loading:false,pdfWarehouseLocator:{visible:false},beginLatestRequest(k){const a=new AbortController();controllers.set(k,a);return a},finishLatestRequest(k,a){if(controllers.get(k)===a)controllers.delete(k)},isCancelledRequest:e=>e?.name==='AbortError',showToast(...x){this.toasts.push(x)},errorMessage:e=>e.message,loadCustomerOptions:async()=>{},loadMaterials:async()=>{},loadRequisition:async()=>{},loadReportedDocuments:async()=>{},invalidatePageCache(){},_productFormDirty:()=>false,resetModalA11ySession(){},pageAllowed:()=>true,go:async function(p){this.activePage=p;return true},canViewCosts:false,hasPermission:()=>false,$nextTick:async()=>{},filteredRequisitionPending:[],requisitionItems:[]};
 for(const n of ['saveStockReplenishmentDraft','saveModal','openStockReplenishment','closeModal','openLowStockReplenishment','openBusinessRequests','viewSavedStockReplenishment','validateStockReplenishmentForm','stockReplenishmentMaterialSuppliers','externalPurchaseQuantityStep','syncExternalStockPurchaseQuantity','refreshStockReplenishmentRecovery','stockReplenishmentRequest','sendStockReplenishmentRecord','queryStockReplenishmentResult','continueStockReplenishmentResult','viewStockReplenishmentRecovery','printStockReplenishmentRecovery','stockReplenishmentCurrentText'])if(html.match(new RegExp('^\\s*(?:async )?'+n+'\\(', 'm')))c[n]=actual(n);
 return {c,box,posts,gets,timers,store,actual};
}
async function valid(p,key){await p.c.openStockReplenishment();p.c.stockReplenishmentForm.idempotency_key=key;p.c.stockReplenishmentForm.customer_id=1;p.c.stockReplenishmentForm.items=[{_key:'display-only',target_inventory_type:'semi_finished',quantity:8,customer_id:1,reference_product_id:7,material_code:'K3K',material_supplier_name:'合成供应商',layer_count:5,flute_type:'AB',report_length_mm:300,report_width_mm:200,crease_type:null}];assert.equal(p.c.validateStockReplenishmentForm(),'');}

const body=(key='wire-key')=>({source_type:'customer_request',idempotency_key:key,expected_actor_id:1,customer_id:1,items:[{target_inventory_type:'semi_finished',reference_product_id:7,customer_id:1,quantity:8,layer_count:1,flute_type:'NONE',report_length_mm:139.5,report_width_mm:200,crease_type:'净',crease_left_mm:9,external_purchase_quantity:'11.000000'}],replenishment_plans:[{size:139.5,quantity:2}]});
function helper(){return page().box.TmStockReplenishmentRecovery;}
test('旧摘要规范：纯UTF8 SHA，默认/null，小数与Decimal原精度（无crypto.subtle）',()=>{const a=helper(),b=body(),n=a.normalize(b);assert.equal(n.items[0].crease_left_mm,null);assert.equal(n.items[0].sheet_type,'net_sheet');assert.equal(n.items[0].external_purchase_quantity,'11.000000');assert.equal(n.items[0].report_length_mm,139.5);const canonical=structuredClone(n);canonical.items[0].report_length_mm='139.5';canonical.replenishment_plans[0].size='139.5';assert.equal(a.requestHash(b,1),crypto.createHash('sha256').update(a.stable({actor_id:1,payload:canonical})).digest('hex'));assert.equal(a.sha256('中文原请求'),crypto.createHash('sha256').update('中文原请求').digest('hex'));});
test('首发送前持久化，双击一POST，坏2xx不成功并保留完整body',async()=>{for(const ack of [null,{}, {id:7}]){const w=deferred(),p=page(storage(),()=>w.promise);await valid(p,'bad-ack');const a=p.c.saveModal();const b=await p.c.saveStockReplenishmentDraft();assert.equal(b._in_flight,true);assert.equal(p.posts.length,1);assert.equal(p.c.stockReplenishmentRecoveryRecords.length,0);assert.ok(p.store.length>0);w.resolve({data:ack});assert.equal(await a,false);assert.equal(p.c.stockReplenishmentSaveState.committed,false);p.c.refreshStockReplenishmentRecovery();const r=p.c.stockReplenishmentRecoveryRecords[0];assert.equal(r.body.items[0].quantity,8);assert.equal(r.body.expected_actor_id,1);assert.equal(r.state,'unknown');assert.equal(r.hadUnknown,true);}});
test('存储失败/容量不足：实际保存没有POST',async()=>{for(const op of ['getItem','setItem']){const s=storage(),p=page(s);await valid(p,'no-storage');s[op]=()=>{throw Error('storage unavailable')};await assert.rejects(p.c.saveStockReplenishmentDraft());assert.equal(p.posts.length,0);}});
test('unknown500→关闭/实际重开→刷新同storage入口保留原内容且不隐式POST',async()=>{const s=storage(),p=page(s,async()=>{throw Object.assign(Error('commit acknowledgement lost'),{response:{status:500}})});await valid(p,'refresh-original');await p.c.saveModal();await p.c.openStockReplenishment();assert.equal(p.c.stockReplenishmentRecoveryRecords[0].key,'refresh-original');const q=page(s);await q.c.openStockReplenishment();assert.equal(q.c.stockReplenishmentRecoveryRecords[0].body.items[0].quantity,8);assert.equal(q.posts.length,0);assert.equal(q.c.modal.type,'stockReplenishment');assert.equal(q.c.stockReplenishmentForm.items.length,0);});
test('有限等待超时结束busy，忽略abort的合法迟到成功不能清记录',async()=>{const f=fixture('plain-current-shape'),w=deferred(),p=page(storage(),()=>w.promise);await currentForm(p,f);const promise=p.c.saveModal();const api=p.box.TmStockReplenishmentRecovery,r=api.createStore(p.store,1).list()[0];assert.equal(api.validateComplete(f.write.body,r).source.id,f.write.body.id);const timer=[...p.timers.values()].find(t=>t.ms===60000);assert.ok(timer);timer.f();assert.equal(await promise,false);assert.equal(p.c.stockReplenishmentSaveState.saving,false);assert.equal(p.c.stockReplenishmentRecoveryRecords[0].state,'unknown');w.resolve({data:f.write.body});await tick();assert.equal(p.c.stockReplenishmentSaveState.committed,false);assert.equal(p.c.stockReplenishmentRecoveryRecords[0].key,f.originalBody.idempotency_key);});
test('A发送→B开窗→合法晚A成功：不关B、不污染结果、不清A原记录',async()=>{const f=fixture('plain-current-shape'),w=deferred(),p=page(storage(),()=>w.promise);await p.c.openStockReplenishment();p.c.stockReplenishmentForm=structuredClone(f.originalBody);p.c.stockReplenishmentForm._pendingDrafts=0;assert.equal(p.c.validateStockReplenishmentForm(),'');const a=p.c.saveStockReplenishmentDraft();const api=p.box.TmStockReplenishmentRecovery,r=api.createStore(p.store,1).list()[0];assert.equal(api.validateComplete(f.write.body,r).source.id,f.write.body.id);p.c.user={id:2};p.c.authGeneration++;p.c.stockReplenishmentSaveState={saving:false,committed:false,uncertain:false,result:null};await p.c.openStockReplenishment();const modal=p.c.modal;w.resolve({data:f.write.body});assert.equal((await a)._stale,true);assert.equal(p.c.modal,modal);assert.equal(p.c.stockReplenishmentSavedNotice.visible,false);assert.equal(api.createStore(p.store,1).list()[0].key,f.originalBody.idempotency_key);});
test('fresh绑定not_saved可更正；曾unknown相同Rejected仍保留；伪hash不解除',async()=>{const a=helper();for(const unknown of [false,true]){const s=storage(),st=a.createStore(s,1),r=st.prepare(body());const live=unknown?st.unknown(r):r;const error={response:{headers:{'x-stock-replenishment-rejected':'1'},data:{detail:{save_result:{status:'not_saved',current_actor_id:1,idempotency_key:r.key,request_hash:r.hash}}}}};assert.equal(a.notSaved(error,live),!unknown);error.response.data.detail.save_result.request_hash='0'.repeat(64);assert.equal(a.notSaved(error,live),false);if(unknown)assert.throws(()=>st.reject(live));else st.reject(live);assert.equal(st.list().length,unknown?1:0);}});
test('多标签确认独立凭据优先：交错晚unknown不覆盖确认，清理失败不可重新POST',()=>{const a=helper(),s=storage(),A=a.createStore(s,1),B=a.createStore(s,1),r=A.prepare(body());const old=B.get(r.key);A.unknown(r);const confirmed=A.confirm(r,{id:3,order_number:'original'},{outcome:'draft_saved'});s.removeItem=()=>{throw Error('remove failure')};assert.throws(()=>A.remove(confirmed));assert.equal(B.unknown(old).state,'confirmed');assert.equal(B.list()[0].result.id,3);assert.equal(B.prepare(body()).state,'confirmed');assert.throws(()=>B.prepare(body('different-new-key')));assert.equal(a.createStore(s,2).list().length,0);});
test('not_recorded只读核对后可显式同body续发；未知后409不换键',async()=>{let count=0;const p=page(storage(),async(url)=>{if(url.endsWith('/resolve'))return {data:{status:'not_recorded',current_actor_id:1,idempotency_key:'not-found',request_match:false,save_receipt:null,current:null,trace:null}};count++;throw Object.assign(Error('unknown or conflict'),{response:{status:count===1?500:409}})});await valid(p,'not-found');await p.c.saveModal();const r=p.c.stockReplenishmentRecoveryRecords[0];await p.c.queryStockReplenishmentResult(r);const shown=p.c.stockReplenishmentRecoveryRecords[0];assert.equal(shown.notRecorded,true);assert.equal(p.posts.filter(x=>!x.p.endsWith('/resolve')).length,1);await p.c.continueStockReplenishmentResult(shown);const writes=p.posts.filter(x=>!x.p.endsWith('/resolve'));assert.equal(writes.length,2);assert.deepEqual(writes[0].body,writes[1].body);assert.equal(p.c.stockReplenishmentRecoveryRecords[0].hadUnknown,true);});

test('同源未知锁按多行来源交集；无关产品可从实际新空窗独立保存（不自动合并）',async()=>{const a=helper(),s=storage(),st=a.createStore(s,1),r=st.prepare(body('A'));st.unknown(r);const B=body('B');B.items[0].reference_product_id=8;assert.equal(a.sameSource(r.body,B),false);assert.equal(st.prepare(B).key,'B');const C=body('C');C.items[0].quantity=99;assert.throws(()=>st.prepare(C));const D=body('D');D.items.push({...D.items[0],reference_product_id:9});assert.throws(()=>st.prepare(D));const fallback=body('fallback');fallback.items[0].reference_product_id=null;const other=structuredClone(fallback);other.idempotency_key='fallback-other';other.items[0].quantity=100;assert.equal(a.sameSource(fallback,other),true);other.items[0].report_width_mm=201;assert.equal(a.sameSource(fallback,other),false);const p=page(s);await p.c.openStockReplenishment();assert.equal(p.c.modal.type,'stockReplenishment');assert.equal(p.posts.length,0);assert.equal(st.list().length,2);});

const fixture=name=>JSON.parse(fs.readFileSync(path.join(root,'tests/fixtures/stock-replenishment-save-recovery',name+'.json'),'utf8'));
test('真实HTTP旧模型金样本：float139.5/中文嵌套/Decimal原精度与safeRejected完整绑定',()=>{const a=helper(),f=fixture('hash-normalization');assert.equal(a.stable(a.normalize(f.originalBody)),a.stable(f.normalizedRequest));assert.equal(a.requestHash(f.originalBody,f.actorId),f.hash);const st=a.createStore(storage(),f.actorId),r=st.prepare(f.originalBody);assert.equal(a.notSaved({response:{...f.write,data:f.write.body}},r),true);});
test('真实HTTP普通/直接外购/override全部proof通过，不硬等建议量与冻结采购量',()=>{const a=helper();for(const name of ['plain','plain-current-shape','direct-external','external-override','material-layer-hint','cardboard-dimension','independent-derived-current','independent-external-hints']){const f=fixture(name),r=a.createStore(storage(),f.actorId).prepare(f.originalBody);assert.equal(a.validateComplete(f.write.body,r).source.id,f.write.body.id);if(f.replay)assert.equal(a.validateComplete(f.replay.body,r).source.id,f.write.body.id);assert.equal(a.validateResolve(f.resolve.body,r).source.id,f.write.body.id);if(name==='external-override')assert.notEqual(r.body.items[0].quantity,f.write.body.save_receipt.lines[0].saved_quantity);}});
test('真实commit500→actual新页面恢复→readonly resolve：零新增业务POST、原号保留、无自动打印',async()=>{const f=fixture('committed-ack-loss'),s=storage(),p=page(s,async()=>{throw Object.assign(Error('actual archived commit500'),{response:f.write})});const st=p.box.TmStockReplenishmentRecovery.createStore(s,f.actorId),r=st.prepare(f.originalBody,{customer:'真实合成客户',products:'原产品 × '+f.originalBody.items[0].quantity});p.c.user={id:f.actorId};p.c.modal={type:'stockReplenishment'};const result=await p.c.sendStockReplenishmentRecord(r,{fresh:true,state:p.c.stockReplenishmentSaveState,form:p.c.stockReplenishmentForm,modal:p.c.modal,store:st}).catch(()=>null);assert.equal(result,null);const q=page(s,async url=>{assert.match(url,/\/resolve$/);return {data:f.resolve.body}});q.c.user={id:f.actorId};await q.c.openStockReplenishment();const before=q.posts.length;await q.c.queryStockReplenishmentResult(q.c.stockReplenishmentRecoveryRecords[0]);assert.equal(q.posts.length-before,1);assert.equal(q.posts.filter(x=>x.p==='/api/requisition/stock-replenishment/orders').length,0);assert.equal(q.c.stockReplenishmentSavedNotice.result.order_number,f.resolve.body.save_receipt.source.order_number);assert.deepEqual(q.c.stockReplenishmentSavedNotice.result._current,f.resolve.body.current);assert.equal(st.list().length,0);assert.equal(q.gets.filter(x=>x.includes('/print')).length,0);});

test('精准reject交错：A已读prepared，B写unknown并续发前读，A清主键不能丢未知原body或放新同源',()=>{const a=helper(),s=storage(),A=a.createStore(s,1),B=a.createStore(s,1),r=A.prepare(body('race')),oldRemove=s.removeItem;let inserted=false;s.removeItem=k=>{if(k.startsWith('erp-stock-replenishment-save:')&&!inserted){inserted=true;B.unknown(r);assert.equal(B.get(r.key).state,'unknown');}oldRemove(k)};assert.throws(()=>A.reject(r));assert.equal(A.list()[0].body.items[0].quantity,8);assert.equal(A.list()[0].hadUnknown,true);assert.throws(()=>A.prepare(body('different-race-key')));assert.equal(A.confirm(r,{id:1},{outcome:'draft_saved'}).state,'confirmed');assert.equal(B.unknown(r).state,'confirmed');});

async function currentForm(p,f){await p.c.openStockReplenishment();p.c.stockReplenishmentForm=structuredClone(f.originalBody);p.c.stockReplenishmentForm._pendingDrafts=0;assert.equal(p.c.validateStockReplenishmentForm(),'');}
test('真实当前HTML普通首保存成功与列表失败分开；完整回执单号保留，不重POST',async()=>{const f=fixture('plain-current-shape');for(const failure of [false,true]){const p=page(storage(),async()=>({data:f.write.body}));await currentForm(p,f);if(failure)p.c.loadRequisition=async()=>{throw Error('read failed')};const result=await p.c.saveModal();assert.equal(result,true);assert.equal(p.c.stockReplenishmentSaveState.committed,true);assert.equal(p.c.stockReplenishmentSavedNotice.result.id,f.write.body.id);assert.equal(p.posts.length,1);assert.equal(p.box.TmStockReplenishmentRecovery.stable(p.box.TmStockReplenishmentRecovery.normalize(p.posts[0].body)),p.box.TmStockReplenishmentRecovery.stable(f.write.body.save_receipt.request));assert.match(p.c.toasts.at(-1)[0],/已保存/);assert.equal(!!p.c.stockReplenishmentSavedNotice.readError,failure);}});
test('合法成功后列表await失败迟到不污染新窗口；query完成迟到不清原key',async()=>{const f=fixture('plain-current-shape'),w=deferred(),p=page(storage(),async()=>({data:f.write.body}));await currentForm(p,f);p.c.loadRequisition=()=>w.promise;const a=p.c.saveStockReplenishmentDraft();await tick();await p.c.openStockReplenishment();const newer=p.c.modal,notice=p.c.stockReplenishmentSavedNotice;w.reject(Error('old list failed'));assert.equal((await a)._stale,true);assert.equal(p.c.modal,newer);assert.equal(notice.readError,'');const resolve=deferred(),q=page(storage(),()=>resolve.promise),api=q.box.TmStockReplenishmentRecovery,st=api.createStore(q.store,1),r=st.unknown(st.prepare(f.originalBody));q.c.refreshStockReplenishmentRecovery();const request=q.c.queryStockReplenishmentResult(r);q.c.modal={type:'other-current'};resolve.resolve({data:f.resolve.body});await request;assert.equal(st.list()[0].state,'unknown');assert.equal(q.c.modal.type,'other-current');assert.equal(q.c.stockReplenishmentRecoveryBusy,'');});

test('真实freshRejected实际发送可更正，与曾unknown后同回包仍保留及legacy原单入口分开',async()=>{const f=fixture('fresh-rejected');for(const hadUnknown of [false,true]){const p=page(storage(),async()=>{throw Object.assign(Error('safe rejected'),{response:{...f.write,data:f.write.body}})}),api=p.box.TmStockReplenishmentRecovery,st=api.createStore(p.store,1);let r=st.prepare(f.originalBody);if(hadUnknown){r=st.unknown(r);r.notRecorded=true;}await assert.rejects(p.c.sendStockReplenishmentRecord(r,{fresh:!hadUnknown,store:st}));assert.equal(st.list().length,hadUnknown?1:0);assert.equal(p.c.stockReplenishmentSaveState.uncertain,hadUnknown);}const legacy=fixture('legacy-null'),p=page(storage(),async()=>({data:legacy.resolve.body})),st=p.box.TmStockReplenishmentRecovery.createStore(p.store,1),r=st.unknown(st.prepare(legacy.originalBody));p.c.refreshStockReplenishmentRecovery();await p.c.queryStockReplenishmentResult(r);const row=p.c.stockReplenishmentRecoveryRecords[0];assert.equal(row.trace.source_id,legacy.resolve.body.trace.source_id);assert.equal(row.state,'unknown');assert.equal(row.notRecorded,false);assert.equal(p.posts.filter(x=>!x.p.endsWith('/resolve')).length,0);});

test('独立真实voided/外购hint结果：原成功与当前状态分列、原单查看与打印lateGET不影响新窗',async()=>{const f=fixture('independent-derived-current'),p=page(storage(),async()=>({data:f.resolve.body})),api=p.box.TmStockReplenishmentRecovery,st=api.createStore(p.store,1),r=st.unknown(st.prepare(f.originalBody));p.c.refreshStockReplenishmentRecovery();await p.c.queryStockReplenishmentResult(r);const saved=p.c.stockReplenishmentSavedNotice.result;assert.equal(saved._current.status,'voided');assert.match(p.c.stockReplenishmentCurrentText(saved._current),/已作废/);assert.equal(saved.status,'draft');assert.equal(saved._save_recovery,true);for(const action of ['viewStockReplenishmentRecovery','printStockReplenishmentRecovery']){const w=deferred();let opened=0;p.box.axios.get=async url=>{p.gets.push(url);return w.promise};p.c.openStockReplenishmentPrint=()=>{opened++};p.c.modal=null;const read=p.c[action]({state:'confirmed',result:saved});await tick();p.c.modal={type:'new-window'};w.resolve({data:f.write.body});await read;assert.equal(opened,0);assert.equal(p.c.modal.type,'new-window');}assert.equal(p.posts.filter(x=>!x.p.endsWith('/resolve')).length,0);});
