// Isolated synthetic UI only. Never targets the formal ERP or changes business data.
const fs=require('fs'),path=require('path'),http=require('http');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'../..'),out=process.env.ERP_UI_ARTIFACT_DIR||path.join(require('os').tmpdir(),'tianming-unified-ui-validation');fs.mkdirSync(out,{recursive:true});
let html=fs.readFileSync(root+'/static/index.html','utf8').replace('        async mounted() {','        async fixtureDisabledMounted() {').replace('app.mount("#app");','window.erpFixture=app.mount("#app");');
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end(html);}if(url.pathname.startsWith('/api/')){res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({items:[],total:0,counts:{},permissions:[]}));}if(!url.pathname.startsWith('/static/')){res.statusCode=404;return res.end();}const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(path.resolve(root)+path.sep)||!fs.existsSync(file)){res.statusCode=404;return res.end();}res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream');res.end(fs.readFileSync(file));});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
try{const page=await browser.newPage({viewport:{width:1366,height:768}});page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>!!window.erpFixture);
await page.evaluate(()=>{const a=window.erpFixture; a.user={id:1,username:'isolated-ui',role:'admin',real_name:'隔离排版检查',permissions:['*']};a.hasPermission=()=>true;a.pageAllowed=()=>true;a.canViewCosts; a.activePage='orders';a.customerOptions=[{id:1,name:'苏州工业园区测试客户有限公司',chinese_short_name:'测试客户'}];a.allCustomers=a.customerOptions;
 a.emailQueueMode=true;a.emailQueueFilter='ready';a.pdfQueueVisible=false;a.modal={type:'orderPdfImport',title:'订单 PDF 核对'};
 a.loadOrderImportReminderForDraft=async()=>{};
 a.orderImportDrafts=Array.from({length:8},(_,d)=>({source_name:'PO20260900'+d+'.pdf',file_hash:'fixture-'+d,customer_name:'苏州工业园区测试客户有限公司',matched_customer_id:1,customer_po:'PO20260900'+d,order_date:'2026-09-02',delivery_date:'2026-09-19',recognition_status:'recognized',email_queue_status:'ready',confirmed:false,items:Array.from({length:14},(_,i)=>({client_line_id:'line-'+i,line_no:i+1,normalized_product_code:'Z.001.000'+(205+i),raw_product_code:'Z.001.000'+(205+i),product_name:'30入装格挡长片15片',raw_product_name:'30入装格挡长片15片',specification:'1159 × 428mm',matched_product_id:1,quantity:30,unit_price:'2.35',_inventory:{loading:false,stale:false,finished:{candidates:[],allocations:[],selected_candidates:[]},semi:{whole:{candidates:[],manual_candidates:[],allocations:[],selected_candidates:[]}},authoritative:{order_quantity:30,finished_planned_quantity:29,production_required_quantity:1,requisition_sheet_quantity:1}}}))}));
 a.commonBoxReadiness=()=>({ready:true,missing_fields:[]});a.inventoryDecisionRequired=()=>'';a.pdfInventoryIssueText=()=>'';a.pdfInventoryDisplayState=()=> 'partial';a.pdfInventoryHasButton=()=>true;
});
await page.waitForTimeout(700);await page.screenshot({path:out+'/pdf-1366.png'});
console.log('pdf',await page.evaluate(()=>({body:document.body.scrollHeight,window:innerHeight,modal:document.querySelector('.pdf-order-import-modal')?.getBoundingClientRect().toJSON(),text:document.querySelector('.pdf-order-import-modal')?.innerText.slice(-500)})));
await page.evaluate(()=>{window.erpFixture.pdfQueueVisible=true;});await page.screenshot({path:out+'/email-1366.png'});
await page.evaluate(()=>{const a=window.erpFixture;a.pdfQueueVisible=false;const item=a.orderImportDrafts[0].items[0];item._inventory.finished.candidates=[{lot_id:1,lot_number:'FG-ISOLATED',quantity_available:29,warehouse_location:{id:1,location_name:'北H1-1-1层2格',warehouse_floor:3}}];item._inventory.finished.allocations=[{candidate:item._inventory.finished.candidates[0],requested_qty:29}];a.pdfOpenInventory(item);});await page.waitForTimeout(100);await page.screenshot({path:out+'/inventory-1366.png'});

await page.evaluate(()=>{const a=window.erpFixture;a.modal=null;a.activePage='finance';a.financeView='current';a.loadFinance=async()=>{a.financeCurrentRows=a._fixtureCurrent.slice(0,a.pageSize);};a.financeCurrentState={loading:false,error:'',loaded:true};a._fixtureCurrent=Array.from({length:30},(_,i)=>({customer_id:i+1,customer_name:'测试客户'+i,statement_month:'2026-09',period_start:'2026-09-01',period_end:'2026-09-30',statement_count:1,pending_reconciliation_amount:12500,pending_invoice_amount:500,reconciled_receivable_amount:100,invoiced_amount:100,statements:[]}));a.financeCurrentRows=a._fixtureCurrent.slice(0,8);a.financeCurrentTotal=30;});
const checks=[];
async function shot(name){await page.waitForTimeout(400);await page.screenshot({path:out+'/'+name+'.png'});const m=await page.evaluate(()=>{const el=document.querySelector('.main');return {scroll:el.scrollHeight,client:el.clientHeight,bottom:el.getBoundingClientRect().bottom,pageSize:window.erpFixture.pageSize};});checks.push({name,...m});}
await shot('finance-current-1366');
await page.evaluate(()=>{const a=window.erpFixture;a.financeView='expenses';a.financeExpensePane='list';a.loadFinanceCosts=async()=>{a.financeCostItems=a._fixtureCosts.slice(0,a.pageSize);};a.reloadOrdersForUiModeChange=async()=>{if(a.financeView==='expenses')await a.loadFinanceCosts();else await a.loadFinance();};a.financeCostState={loading:false,error:'',saving:false};a.financeCostMeta.categories=[];a._fixtureCosts=Array.from({length:20},(_,i)=>({id:i+1,document_date:'2026-09-12',description:'工资费用测试'+i,source_reference:'隔离测试记录',cost_category_label:'人员工资',cost_center_name:'工厂',amount:12500,status:'draft',status_label:'草稿'}));a.financeCostItems=a._fixtureCosts.slice(0,8);a.financeCostTotal=20;});
await shot('finance-expenses-1366');
await page.evaluate(()=>{window.erpFixture.financeExpensePane='entry';});await shot('finance-entry-1366');
await page.evaluate(()=>{window.erpFixture.financeExpensePane='fixed';});await shot('finance-fixed-1366');
await page.evaluate(()=>{const a=window.erpFixture;a.financeView='payables';a.supplierSettlements=Array.from({length:8},(_,i)=>({id:i+1,supplier_name:'测试供应商'+i,statement_number:'TEST-'+i,period_start:'2026-09-01',period_end:'2026-09-30',status:'draft',erp_amount:12500,adjusted_amount:12500,lines:[],adjustments:[],invoices:[],payments:[],_historyItems:[],available_credits:[]}));});await shot('finance-supplier-1366');
await page.locator('.workspace-fold-trigger').filter({hasText:'测试供应商0'}).click();await shot('finance-supplier-dialog-1366');
await page.keyboard.press('Escape');

await page.evaluate(()=>{const a=window.erpFixture;a.activePage='requisition';a.requisitionTab='submitted';a.requisitionLoading=false;a.reportedState={loading:false,error:''};a._fixtureReported=Array.from({length:40},(_,i)=>({stable_id:'supplier_order:'+i,source_type:'supplier_order',document_id:1,sequence:i+1,report_length_mm:1159,report_width_mm:428,crease_display:'净料',requisition_qty:1400,unit:'张',material_code:'R616R',flute_type:'AB',customer_short_name:'测试客户',product_code:'Z.001.000205',reported_at:'2026-09-12T10:26:00+08:00',supplier_name:'测试供应商',status:'active'}));a.requisitionItems=a._fixtureReported.slice(0,12);a.requisitionTotal=40;a.loadReportedDocuments=async()=>{a.requisitionItems=a._fixtureReported.slice(0,a.screenPageSize(12));return true;};a.reloadOrdersForUiModeChange=async()=>{if(a.activePage==='requisition')await a.loadReportedDocuments();else if(a.activePage==='production'&&a.productionTab==='history')await a.loadProductionHistory();else if(a.financeView==='expenses')await a.loadFinanceCosts();else await a.loadFinance();};});
await shot('reported-1366');
await page.evaluate(()=>{const a=window.erpFixture;a.activePage='production';a.productionTab='history';a.productionHistoryLoading=false;a.productionHistoryError='';a._fixtureHistory=Array.from({length:40},(_,i)=>({id:i+1,completed_at:'2026-09-12T10:00:00+08:00',customer_name:'测试客户有限公司',customer_short_name:'测试客户',customer_order_number:'PO-TEST-'+i,product_code:'Z.001.000205',product_name:'30入装格挡长片15片',actual_output_quantity:5600,planned_output_quantity:5600,status:'completed',current_inventory_status:'located',current_warehouse_location_name:'三楼 · 北H1-1 · 1层2格',can_adjust_actual_quantity:true}));a.productionHistory=a._fixtureHistory.slice(0,8);a.productionHistoryTotal=40;a.loadProductionHistory=async()=>{a.productionHistory=a._fixtureHistory.slice(0,a.productionHistoryPageSize());};});await shot('production-history-1366');
await page.evaluate(()=>{const a=window.erpFixture;a.productionTab='preparation';a.loadStockPreparation=async()=>true;a.stockPrepBusy=false;a.stockPrepError='';a.stockPrepCounts={arrange:2};a.stockPrepTotal=1;const children=[{product_id:1,code:'Z.001.000205',name:'长片15片',customer_name:'测试客户',per_set:3,unit:'只',location:'一楼 · 原料区 · 1号位',available:1400,receipt_item_id:1,key:'r:1',can_plan:true},{product_id:2,code:'Z.001.000205',name:'短片20片',customer_name:'测试客户',per_set:4,unit:'只',location:'一楼 · 原料区 · 2号位',available:1860,receipt_item_id:2,key:'r:2',can_plan:true}];a.stockPrepRows=[{key:'kit:1',entry_type:'kit',children,plan:{available_sets:1860,recipe:{parent_id:3,code:'Z.001.000205',name:'30入装格挡',customer_name:'测试客户',children}}}];a.productionLocations=[{id:7,warehouse_floor:3,area_code:'B1',area_name:'北B1',location_name:'北B1 · 1层2格',layout_version:1}];a.ensureProductionLocations=async()=>true;a.previewStockGroup=async()=>{const d=a.stockPrepDialog;d.preview={sets:1860,recipe:d.row.plan.recipe,shortages:[],inputs:[{receipt_id:1,product_id:1,quantity:1395,expected_output:5580,source_location:children[0].location},{receipt_id:2,product_id:2,quantity:1860,expected_output:7440,source_location:children[1].location}]};};});await shot('production-kit-1366');
await page.getByRole('button',{name:'整组安排',exact:true}).click();await shot('production-kit-dialog-1366');await page.locator('.stock-production-dialog').getByRole('button',{name:'关闭',exact:true}).click();
for(const viewport of [{width:1366,height:768},{width:1920,height:1080}]){
 await page.setViewportSize(viewport);
 for(const mode of ['standard','large']){
  await page.evaluate(({mode})=>{const a=window.erpFixture;a.uiMode=mode;document.body.classList.toggle('ui-large',mode==='large');a.workspaceCapacities={};a.workspaceLocalSizes={};a.pdfFitCapacity=0;a.activePage='production';a.productionTab='history';a.productionHistory=a._fixtureHistory.slice(0,8);}, {mode});await shot('history-'+viewport.width+'-'+mode);
  await page.evaluate(()=>{const a=window.erpFixture;a.activePage='requisition';a.requisitionTab='submitted';a.requisitionItems=a._fixtureReported.slice(0,12);});await shot('reported-'+viewport.width+'-'+mode);
  await page.evaluate(()=>{const a=window.erpFixture;a.activePage='finance';a.financeView='expenses';a.financeExpensePane='list';a.financeCostItems=a._fixtureCosts.slice(0,8);});await shot('expenses-'+viewport.width+'-'+mode);
  await page.evaluate(()=>{const a=window.erpFixture;a.modal={type:'orderPdfImport',title:'订单 PDF 核对'};a.pdfQueueVisible=false;a.orderImportDrafts[0].items[0]._show_inventory_details=false;});await shot('pdf-'+viewport.width+'-'+mode);
  const bounds=await page.locator('.pdf-order-import-modal').boundingBox();checks.push({name:'pdf-dialog-'+viewport.width+'-'+mode,bottom:bounds.y+bounds.height,limit:viewport.height});
  await page.evaluate(()=>window.erpFixture.modal=null);
 }
}
console.log('viewport-checks',checks);fs.writeFileSync(out+'/viewport-checks.json',JSON.stringify(checks,null,2));
console.log('errors',errors);fs.writeFileSync(out+'/browser-errors.json',JSON.stringify(errors));require('assert/strict').equal(errors.length,0);for(const c of checks){if(c.client)require('assert/strict').ok(c.scroll<=c.client+2,c.name+' needs scrolling');if(c.limit)require('assert/strict').ok(c.bottom<=c.limit,c.name+' exceeds viewport');}
}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);server.close();process.exitCode=1;});
