const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),test=require('node:test'),assert=require('node:assert/strict'),{webcrypto}=require('node:crypto');
const ts=require(process.env.ERP_UI_TYPESCRIPT_LIBRARY),exportsObject={};
vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(__dirname,'../src/utils/orderDrawings.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:exportsObject,crypto:webcrypto,Uint8Array,Error});
const d=exportsObject,fixture=()=>Object.assign(new Blob(['explicit isolated unit fixture'],{type:'image/png'}),{name:'drawing.png'}),token='a'.repeat(32);
test('normal upload stores content identity and defaults only to order',async()=>{let calls=0;const s=d.newDrawingState();assert.equal(await d.uploadDrawing(s,fixture(),async file=>{calls++;assert.equal(file.name,'drawing.png');return {token}},()=>true),true);assert.equal(calls,1);assert.equal(s.saveOption,'order_only');assert.equal(s.digest.length,64);assert.equal(s.busy,false);assert.equal(d.drawingFields(s,{edit:false,overwrite:false}).drawing_save_option,'order_only')});
test('customer/product removal invalidates an in-flight response',async()=>{let resolve;const s=d.newDrawingState(),pending=d.uploadDrawing(s,fixture(),()=>new Promise(r=>resolve=r),()=>true);while(!resolve)await new Promise(r=>setImmediate(r));d.invalidateDrawing(s);resolve({token});assert.equal(await pending,false);assert.equal(s.token,'');assert.equal(s.filename,'');assert.equal(s.busy,false)});
test('context change cannot apply an upload even without explicit reset',async()=>{let current=true,resolve;const s=d.newDrawingState(),pending=d.uploadDrawing(s,fixture(),()=>new Promise(r=>resolve=r),()=>current);while(!resolve)await new Promise(r=>setImmediate(r));current=false;resolve({token});assert.equal(await pending,false);assert.equal(s.token,'');assert.equal(s.busy,false)});
test('failed replacement retains prior uploaded drawing and blocks save until retry/reset',async()=>{const s=d.newDrawingState();await d.uploadDrawing(s,fixture(),async()=>({token}),()=>true);assert.equal(await d.uploadDrawing(s,fixture(),async()=>{throw Error('服务不可用')},()=>true),false);assert.equal(s.token,token);assert.match(s.error,/不可用/);assert.throws(()=>d.drawingFields(s,{edit:true,overwrite:true}),/不可用/);d.invalidateDrawing(s);assert.equal(s.error,'')});
test('permission deny and override permission cannot be bypassed by setting option',()=>{const s=d.newDrawingState();s.token=token;s.saveOption='save_to_product';assert.throws(()=>d.drawingFields(s,{edit:false,overwrite:false}),/编辑权限/);s.saveOption='overwrite_product';assert.throws(()=>d.drawingFields(s,{edit:true,overwrite:false}),/覆盖权限/);assert.equal(d.drawingFields(s,{edit:true,overwrite:true}).drawing_save_option,'overwrite_product')});
for(const file of [{name:'drawing.html',size:10},{name:'drawing.svg',size:10},{name:'drawing.png',size:0},{name:'drawing.pdf',size:20*1024*1024+1}])test('invalid size/type never reaches upload '+file.name+' '+file.size,async()=>{let calls=0;const s=d.newDrawingState();assert.equal(await d.uploadDrawing(s,file,async()=>{calls++;return {token}},()=>true),false);assert.equal(calls,0);assert.notEqual(s.error,'')});
for(const unsafe of ['https://untrusted.invalid/file.png','//untrusted.invalid/file.png','/static/private-uploads/file.png','/api/orders/items/1/drawing/content/../file.png','/api/orders/items/1/drawing/content/file.png?x=1'])test('preview rejects non-business path '+unsafe,()=>assert.throws(()=>d.trustedDrawingPath(unsafe),/受保护/));
test('saved content readback detects changed bytes',async()=>{const content=fixture(),hash=await d.contentDigest(content);await d.verifyDrawingContent(hash,content);await assert.rejects(d.verifyDrawingContent(hash,new Blob(['changed'])),/回读不一致/)});
test('draft and final protected paths are accepted',()=>{const s=d.newDrawingState();s.token=token;s.filename='EXAMPLE.PDF';assert.equal(d.draftDrawingPath(s).endsWith('/content/preview.pdf'),true);assert.equal(d.trustedDrawingPath('/api/orders/items/23/drawing/content/file.png'),'/api/orders/items/23/drawing/content/file.png');assert.equal(d.trustedDrawingPath('/api/master/products/drawings/3/content/original.pdf'),'/api/master/products/drawings/3/content/original.pdf')});

test('protected retained legacy suffix stays readable without expanding draft upload types',()=>{assert.equal(d.trustedDrawingPath('/api/orders/items/1/drawing/content/file.bin'),'/api/orders/items/1/drawing/content/file.bin');assert.throws(()=>d.trustedDrawingPath('/api/orders/draft-drawing/'+token+'/content/preview.bin'),/类型不支持/)});
