'use strict';
// Pure contract verification. Fictional objects are unit inputs, never a runtime gateway.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const test=require('node:test'),assert=require('node:assert/strict'),ts=require(process.env.ERP_UI_TYPESCRIPT_LIBRARY);
const source=fs.readFileSync(path.join(__dirname,'../src/utils/orderInventory.ts'),'utf8'),mod={exports:{}};
vm.runInNewContext(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports:mod.exports});
const u=mod.exports,plain=x=>JSON.parse(JSON.stringify(x));
const product={id:1,customer_id:1,product_code:'UNIT-ONLY',is_active:true,report_length_mm:800,report_width_mm:600,material_code:'KA-AB',flute_type:'AB',pieces_per_box:2,default_cutting_mode:'一开二'};
const finished=(id,qty,a=1,b=1)=>({lot_id:id,version:2,quantity_available:qty,quantity_contract:{customer_id:1,product_id:1,customer_basis:a,physical_basis:b,physical_unit:'只'}});
const sheet=(id,qty,yieldFactor=1)=>({lot_id:id,version:3,source:'signature',selectable:true,customer_bound:true,available_stock_quantity:qty,stock_yield_per_sheet:yieldFactor});
function line(id,qty,cs=[]){const state=u.newInventoryLine(1,qty);state.parts.finished.candidates=cs;return {id,product,quantity:qty,state}}
function authority(l,need){return {client_line_id:l.id,product_id:1,order_quantity:l.quantity,coverage_state:'none',interaction_state:'ready',requisition_components:[{component_type:'whole',required_piece_quantity:need,remaining_required_piece_quantity:need,requisition_sheet_quantity:Math.ceil(need/2)}]}}
test('shared finished lot counted once in draft order; stock conserved',()=>{const a=line('a',7,[finished(1,10)]),b=line('b',7,[finished(1,10)]);u.finishedPlans([a,b]);assert.equal(a.state.plan.finished[0].requested_qty,7);assert.equal(b.state.plan.finished[0].requested_qty,3);assert.equal(a.state.allocations[0].stock_quantity+b.state.allocations[0].stock_quantity,10)});
test('physical half sets from two lots combine into whole customer units',()=>{const a=line('a',2,[finished(1,1,1,2),finished(2,3,1,2)]);u.finishedPlans([a]);assert.deepEqual(plain(a.state.allocations.map(r=>r.stock_quantity)),[1,3]);assert.equal(a.state.allocations.reduce((s,r)=>s+r.credited_quantity,0),2)});
test('fractional customer group not invented; unused physical stays available',()=>{const a=line('a',7,[finished(1,4,5,2)]),b=line('b',5,[finished(1,4,5,2)]);u.finishedPlans([a,b]);assert.equal(a.state.allocations[0].stock_quantity,2);assert.equal(b.state.allocations[0].stock_quantity,2);assert.equal(a.state.allocations[0].credited_quantity,5)});
test('unbound/general sheet defaults opt-in; explicit adoption records batch acknowledgment only',()=>{const a=line('a',5),c={...sheet(1,10),customer_bound:false,source:'general_signature',warning_codes:['GENERAL_SEMI_FINISHED_STOCK']};a.state.parts.whole.candidates=[c];a.state.authority=authority(a,5);u.semiPlans([a]);assert.equal(a.state.plan.semi.length,0);a.state.parts.whole.mode='exact';a.state.parts.whole.selected=[1];u.semiPlans([a]);assert.deepEqual(plain(a.state.plan.semi[0].warning_acknowledged_codes),['GENERAL_SEMI_FINISHED_STOCK']);assert.equal(a.state.plan.semi[0].override,true)});
test('shared semi sheets rounded per-line to physical stock without double use',()=>{const a=line('a',5),b=line('b',5);for(const l of [a,b]){l.state.parts.whole.candidates=[sheet(1,4,2)];l.state.authority=authority(l,5)}u.semiPlans([a,b]);assert.equal(a.state.plan.semi[0].requested_qty,5);assert.equal(b.state.plan.semi[0].requested_qty,2);assert.equal(a.state.allocations[0].stock_quantity+b.state.allocations[0].stock_quantity,4)});
test('explicit no sheets leaves finished deduction intact',()=>{const a=line('a',8,[finished(1,3)]);u.finishedPlans([a]);a.state.parts.whole.candidates=[sheet(2,10)];a.state.parts.whole.mode='skipped';a.state.authority=authority(a,10);u.semiPlans([a]);assert.equal(a.state.plan.finished[0].requested_qty,3);assert.equal(a.state.plan.semi.length,0)});
test('different component needs come from authority, not finished-unit assumptions',()=>{const a=line('a',9);a.state.parts.cover.candidates=[sheet(1,20)];a.state.parts.base.candidates=[sheet(2,20)];a.state.authority={...authority(a,0),requisition_components:[{component_type:'cover',required_piece_quantity:3},{component_type:'base',required_piece_quantity:7}]};u.semiPlans([a]);assert.deepEqual(plain(a.state.plan.semi.map(e=>e.requested_qty)),[3,7])});
test('stock customer/product/ratio identity mismatch rejected',()=>{for(const field of ['customer_id','product_id','customer_basis']){const c=finished(1,10);c.quantity_contract[field]=9;const a=line('a',5,[finished(2,10),c]);assert.throws(()=>u.finishedPlans([a]),/不一致/)}});
test('duplicate or no-longer-selectable adopted batches rejected',()=>{const a=line('a',5,[finished(1,10)]);a.state.parts.finished.mode='exact';a.state.parts.finished.selected=[1,1];assert.throws(()=>u.finishedPlans([a]),/重复/);a.state.parts.finished.selected=[99];assert.throws(()=>u.finishedPlans([a]),/已变化/)});
test('invalid quantities and version cannot become a reservation',()=>{for(const value of [-1,1.5,NaN]){const c=finished(1,10);c.version=value;assert.throws(()=>u.finishedPlans([line('a',5,[c])]),/版本/)}assert.throws(()=>u.finishedPlans([line('a',2.5,[finished(1,10)])]),/订单数量/)});
test('authoritative response must include exact stable row identity/quantity',()=>{const a=line('a',5),b=line('b',5);assert.throws(()=>u.applyInventoryAuthority([a,b],[authority(a,5)]),/缺少/);assert.throws(()=>u.applyInventoryAuthority([a],[{...authority(a,5),product_id:2}]),/身份/);assert.throws(()=>u.applyInventoryAuthority([a],[{...authority(a,5),order_quantity:6}]),/数量/)});
test('cover/base and composite use real product structure',()=>{assert.deepEqual(plain(u.inventoryComponents({...product,box_style:'A3'})),['cover','base']);assert.deepEqual(plain(u.inventoryComponents({...product,is_composite:true})),[]);assert.equal(u.semiCandidateRequest({...product,report_length_mm:null},1,'whole'),null);assert.equal(u.semiCandidateRequest(product,1,'whole').pieces_per_box,2)});
test('direct customer-generic recommendation retains audit flags without override',()=>{const a=line('a',5),c={...sheet(1,10),source:'customer_generic',automatic_recommendation:true,direct_deduction_eligible:true,warning_codes:['CUSTOMER_GENERIC_SEMI_FINISHED_STOCK']};a.state.parts.whole.candidates=[c];a.state.authority=authority(a,5);u.semiPlans([a]);assert.equal(a.state.plan.semi[0].direct_deduction,true);assert.equal(a.state.plan.semi[0].override,false);assert.deepEqual(plain(a.state.plan.semi[0].warning_acknowledged_codes),['CUSTOMER_GENERIC_SEMI_FINISHED_STOCK'])});
test('manual browse never becomes an automatic adoption',()=>{assert.equal(u.safeCandidate('whole',{...sheet(1,10),source:'manual',automatic_recommendation:true,direct_deduction_eligible:true}),false)});
test('current formal positive integer cutting labels supported and invalid labels rejected',()=>{assert.equal(u.semiCandidateRequest({...product,default_cutting_mode:'一开12'},1,'whole').stock_yield_per_sheet,12);assert.equal(u.semiCandidateRequest({...product,default_cutting_mode:'7'},1,'whole').stock_yield_per_sheet,7);assert.throws(()=>u.semiCandidateRequest({...product,default_cutting_mode:'一开0'},1,'whole'),/不能猜测/)});
